### PR TITLE
Fixed issue #16185: Typo "be have"

### PR DESCRIPTION
**Pull request by jmantysalo**
Fixed issue #<Mantis issue number>: 16185

### CODE REVIEW

**Comment by cdorin93** [comment]
Hmm - what about: "Name should contain at least 1 character" ? :thinking: . Wouldn't that sound better? Indeed, the current form is not nice / user friendly

**Comment by Shnoulle** [comment]
Name can not be empty ?

**Comment by Shnoulle** [comment]
My opinion : never shown : https://github.com/LimeSurvey/LimeSurvey/blob/334af4225e4c3dcfead5adcaa7ba188cb2d35b83/application/models/UserGroup.php#L62

**Comment by jmantysalo** [comment]
> My opinion : never shown :

Good point. So the error message is currently just a placeholder, if we later want to require slightly longer name.

Well, at least a good case to see if GitHub, PR and mirroring change to translations page works. If I can do this, maybe even something more usefull is doable too.

**Comment by Shnoulle** [comment]
PS : i think even if you set to 3 : there are already some translation by Yii :)

**Pull request merged**
