### PR TITLE
Fix notice "Trying to access array offset on value of type bool"

### PR DESCRIPTION
**Pull request by fg-ok**
Fixed issue #0: Array access on unexpected boolean variable caused notices

### CODE REVIEW

**Comment by glimz** [comment]
Hello, I cannot find any bug report for your PR? For tracking purposes, can you create one, so we can test your PR and merge it if everything is ok?

**Comment by fg-ok** [comment]
My colleague wrote me about the notice and wanted to create a bug report.
I'm still waiting (because of that the PR is still a draft) but already fixed the issue pro-active. I think I should and will create the according bug report myself and change the request then.

Thanks for asking and sorry for the confusion. :)

**Comment by skwzrd** [comment]
I got this error in version 5.1.15. Using this fix works!

**Comment by fg-ok** [comment]
I'm just too lazy to create an extensive bug report in LimeSurveys bugtracker to address the issue.

**Comment by Shnoulle** [comment]
PS : think it's more clear with `$bShowGraph = !is_empty($aattr["statistics_showgraph"]);`

**Comment by fg-ok** [comment]
> PS : think it's more clear with `$bShowGraph = !is_empty($aattr["statistics_showgraph"]);`

Sounds legit. Will update my commit

**Comment by c-schmitz** [comment]
Thank you.

**Pull request merged**
