### PR TITLE
Added .row to date question views

### PR DESCRIPTION
**Pull request by tammoterhark**
Denis asked me to make pull request directly to limesurvey.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Yes but to answers_html branch ;)

**Comment by tammoterhark** [comment]
My god, this is difficult. I forked LimeSurvey, but this branch is not in there. Should I define that branch myself?

**Comment by Shnoulle** [comment]
It's not the default

I have to finalize something and send you the instrcution here
(maybe i make the patch too)

**Comment by tammoterhark** [comment]
I did not see it when I typed git branch but it is there anyway. I will checkout against that branch. Can you manage the two previous PR's or do I need to do them again?

**Comment by tammoterhark** [comment]
Thanks, sorry for my ignorance...

**Comment by Shnoulle** [comment]
It's better if you can do it yourself :)

**Comment by Shnoulle** [comment]
````
git remote add official https://github.com/LimeSurvey/LimeSurvey.git
git fetch official
git checkout -b official_answers_html official/answers_html
git push origin
````

And now : the real fork is official_answers_html : you can , maybe, find a better name

**Comment by tammoterhark** [comment]
I did:
```
git remote add upstream https://github.com/LimeSurvey/LimeSurvey.git
git fetch upstream
git merge upstream answers_html
git push
```
Is that a lot different?

**Comment by Shnoulle** [comment]
No it must be OK too , but i always use official for LimeSurvey official .

And i'm afraid of the master merge from Shnoulle version (if you do it too in your fork)

**Comment by Shnoulle** [comment]
PS : when you do the pull request : remind to choose the good branch from this repo.

**Comment by tammoterhark** [comment]
Good branch = answers_html ?

**Comment by Shnoulle** [comment]
Last tested clean branch : https://github.com/LimeSurvey/LimeSurvey/tree/answers_html

**Comment by Shnoulle** [comment]
I add some css to base and base_awesome : to better see the margin issue.
https://github.com/LimeSurvey/LimeSurvey/commit/3283a89206c38e6b8494554f7189c358f72a2db0#diff-b335d07f1b8b253b4135656fb302b179R16

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/552

**Pull request closed without merging**
