### PR TITLE
New feature #8331: Set appearance options for queXML export

### PR DESCRIPTION
**Pull request by adamzammit**
Dev: Updated queXMLPDF class to latest upstream
Dev: Added new view for setting queXMLPDF appearance options before exporting
Dev: Removed references to limesurvey_lang class

### CODE REVIEW

**Comment by adamzammit** [comment]
@mfaber 
Hi Mirko,

It would be great to get your feedback on this feature. I think it makes the export to queXMLPDF from LimeSurvey a lot more valuable.

Adam

**Comment by mfaber** [comment]
Hi Adam: i cannot get this to work. when trying to export i get a php error. i also cant find the new settings tab. Could also be a problem on my side...

PHP Error:
 Declaration of quexmlpdf::setPageFormat() should be compatible with TCPDF::setPageFormat($format, $orientation = 'P')

E:\survey\htdocs\github\LimeSurvey\application\libraries\admin\quexmlpdf.php(33)

21 require_once($tcpdf['base_directory'].'/tcpdf.php');
22 
23 /**
24  * A TCPDF based class to produce queXF compatible questionnaire PDF files and banding description XML from queXML
25  *
26  * @author    Adam Zammit <adam.zammit@acspri.org.au>
27  * @copyright (c) 2010 Australian Consortium for Social and Political Research Incorporated (ACSPRI)
28  * @since     2010-09-02
29  * @link      http://www.acspri.org.au/software
30  * @link      http://quexml.sourceforge.net
31  * @link      http://quexf.sourceforge.net
32  */
33 class quexmlpdf extends pdf {
34 
35   /**
36    * Define an inch in MM
37    *
38    * @const float Defaults to 25.4
39    */
40   const INCH_IN_MM = 25.4;
41 
42   /**
43    * Language for translation
44    */
45   protected $language = "en";

**Comment by adamzammit** [comment]
@mfaber 
Thanks for testing this - it looks like an error that occurs with PHP strict in newer versions of PHP. I have updated the pull request and it should work now.

**Comment by mfaber** [comment]
IMHO this is a very useful addition. In fact something I had in mind coding myself but did not get around doing. So thanks a lot!! One more feature request, tho: a "reset to default values" button on the settings page. I tend to play around with the settings and then need an hour to get back to something useful ;)

**Comment by adamzammit** [comment]
Good idea. I've done that. Please give it another check when you get a chance.

**Comment by mfaber** [comment]
Very useful feature and works well. Thanks!! 
I'd be in favor to merge this into master as the chance that serious bugs are introduced is likely near zero. But I'm not sure about the policy. 
@c-schmitz: Please advise...

**Comment by c-schmitz** [comment]
:-)

**Pull request merged**
