### PR TITLE
Fixed issue #17787: open_base_dir + debug can throw error when load s…

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #17787: open_base_dir + debug can throw error when load some question type.
Dev: try to load any files in any directory are always an error

### CODE REVIEW

**Comment by Shnoulle** [comment]
@olleharstedt see https://github.com/LimeSurvey/LimeSurvey/commit/cb8043fee0ac1b3ac1513c571984a1c313e3ba2b

I don't understand here this can never work except for core question theme … 

1. This don't take application/view/surveys/questions theme
2. directory for uploaded theme is broken : always (here). since it's not related to rootdir.

Maybe we need to remove whole system if it's unused ?

**Comment by olleharstedt** [comment]
Hm, can never work, but does it work? o0

**Comment by olleharstedt** [comment]
Can you write testing instructions for this commit, please?

**Comment by Shnoulle** [comment]
1. Set open_base_dir to /var/:/tmp/:/home/ for example
2. Activate debug mode
3. Import included survey
4. preview question

https://bugs.limesurvey.org/view.php?id=17787

**Comment by Shnoulle** [comment]
> What I can see, it's using rootdir. But you mean it shouldn't?

1. https://github.com/LimeSurvey/LimeSurvey/blob/0bb1de73246e9dd913420ba7bc20cbb2ec9520c5/application/models/QuestionTemplate.php#L124
2. https://github.com/LimeSurvey/LimeSurvey/blob/0bb1de73246e9dd913420ba7bc20cbb2ec9520c5/application/config/config-defaults.php#L733

no rootdir …

Just put a log or tracevar at https://github.com/LimeSurvey/LimeSurvey/blob/0bb1de73246e9dd913420ba7bc20cbb2ec9520c5/application/models/QuestionTemplate.php#L125

**Comment by c-schmitz** [comment]
Thank you!

**Pull request merged**
