### PR TITLE
Fixed issue #16474: Remote control import_group broken

### PR DESCRIPTION
**Pull request by gabrieljenik**
Fixed and Added test case

### CODE REVIEW

**Comment by cdorin93** [comment]
Oh no, travis is red :(

**Comment by gabrieljenik** [comment]
There was some conflict on helpers loading.
Initially we changed how a helper is loaded on TestHelper, as to avoid duplicates with RemoteControlHandle.
Still, that created a duplicate with this commit: https://github.com/LimeSurvey/LimeSurvey/commit/5550194b51343c08f7fb3dbc22754ba04d808773#diff-fac7e21d70e934b24d9330f951f13c5df1badba6f41fa52c894364fb09db4d8cR52

I guess at some point we need to standarize how the path of the import is declared.

**Comment by gabrieljenik** [comment]
Now it s green!

**Comment by martijnhaex** [comment]
What is the status of this PR? 

Currently in our project want the use this RPC call to add default (mandatory) questions to a Survey.
ISO adding a Group add importing question by question.

**Comment by olleharstedt** [comment]
> What is the status of this PR, when can this be released?
> 
> Currently in our project want the use this RPC call to add default (mandatory) questions to a Survey.
> ISO adding a Group add importing question by question.

It will be released in the next patch release on Monday.

**Pull request merged**
