### PR TITLE
Fixed issue #17569: Unable to edit answer in single choice question after activate survey

### PR DESCRIPTION
**Pull request by gabrieljenik**
Making LS5 to allow answer options updates as it was on LS3.

### CODE REVIEW

**Comment by olleharstedt** [comment]
Hm, is this still behaving correctly when survey is activated? Not possible to hack the POST?

**Comment by Shnoulle** [comment]
> Hm, is this still behaving correctly when survey is activated?

It's the issue 17569 : in 3.X (since 1.40 maybe): it available because it's not an issue : it don't broke database

**Comment by olleharstedt** [comment]
> > Hm, is this still behaving correctly when survey is activated?
> 
> It's the issue 17569 : in 3.X (since 1.40 maybe): it available because it's not an issue : it don't broke database

Oh, so it's possible to add new answer options without problems, even in activated survey? Even for ranking question type?

**Comment by Shnoulle** [comment]
> > > Hm, is this still behaving correctly when survey is activated?
> > 
> > 
> > It's the issue 17569 : in 3.X (since 1.40 maybe): it available because it's not an issue : it don't broke database
> 
> Oh, so it's possible to add new answer options without problems, even in activated survey? Even for ranking question type?

Yes and yes. For ranking it's the reason of this attribute : https://github.com/LimeSurvey/LimeSurvey/blob/7c8357130f627e314ccc493d8a2e694c1ffd1108/application/helpers/questionHelper.php#L526 (`'readonly_when_active'=>true`)

**Comment by olleharstedt** [comment]
Alright, thanks. :)

**Comment by olleharstedt** [comment]
Any PR that removes more code than it adds is a successful PR. :star2:

**Pull request merged**
