### PR TITLE
Dev: TODOS replace Question->insertRecords()

### PR DESCRIPTION
**Pull request by TonisOrmisson**
Replaced the Question->insertRecords() with the Yii way.

Updated the Question model rules of missing attributes to be allow to push the data directly to ->attributes

### CODE REVIEW

**Comment by Shnoulle** [comment]
👍 Working on TSV import : using tracevar to show error is really awfull. This disable using getErrors but more http://www.yiiframework.com/doc/api/1.1/CHtml#errorSummary-detail :)

Another solutiuin with less update (i must test it) : insertRecords can return id or object. If there are error return object, then view can use it

**Comment by TonisOrmisson** [comment]
@Shnoulle thanks. i added the tracevar because it was here 
https://github.com/LimeSurvey/LimeSurvey/pull/823/files#diff-57d8ed613df5c805f7b2c706aca6ca52R363
and I did not know whether it was neccessary. 

I know about errorSummary() but its not this is a different sory. I just wanted to replace ....

Should I remove the tracevar at all then?

**Comment by TonisOrmisson** [comment]
Ah ok, its only if save faile

**Comment by Shnoulle** [comment]
About tracevar : yes it was here, before with current insertRecords : there are no clean solution to show the error to the user in a cleanest way (using errorSummary or do our own system). 

Then : since we don't have a system to show the error : we need something using Yii::log … and tracevar is the quickest

**Comment by TonisOrmisson** [comment]
this type of logging then somewhere in LSActiveRecord->afterSave() to to cover all models similarly? Anyway I removed from here

**Comment by Shnoulle** [comment]
No, i don't think : i think controller must use if(object->save) and add the error in a clean way for view :).
And currently : all error can be loggued with 
```
                'fileError' => array(
                    'class' => 'CFileLogRoute',
                    'levels' => 'info, warning, error',
                    'except' => 'exception.CHttpException.404',
                ),
```
(for example)
Maybe : send object to view. view can do 

```
if($object->hasErrors()) { 
  echo "There are error";
  echo CHtml::errorSummary($object);
}
```

**Comment by TonisOrmisson** [comment]
Yes totally agree. 
In this specific case though the yii logging is not working because there is no log written :)
If it's a one-model action then errorSummary() is great, but if you are doing bulk actions then errorSummary() is no good, a custom solution is needed. 

Anyway, its not a subject for this PR, a question of general loging logic and I do not want to go into that now :)

**Pull request merged**
