### PR TITLE
Fixed issue #11947: Session.php is considered a virus under ASL/clamav

### PR DESCRIPTION
**Pull request by BertHankes**
Dev: Just a tweak to keep ASL happy

### CODE REVIEW

**Comment by Shnoulle** [comment]
The previous pull request was closed ?

**Comment by BertHankes** [comment]
Yes, because of the wrong PR title... 
But then again... i'm not certain that it was me that closed the previous PR.

**Comment by Shnoulle** [comment]
OK, got it : you do the PR directly in github ? Because second line in https://github.com/LimeSurvey/LimeSurvey/pull/606/commits/1b92a1f6b7ba41d0541f71916ea67f11da494288 must be first, and the first line must be removed :).

See what @c-schmitz tell for this.

**Comment by BertHankes** [comment]
I can't get the grasp of this nomenclatura :-( bare with me!
I just edited the PR

**Comment by BertHankes** [comment]
And yes: I just work on github.com (it is just not in my system and everyday work)

**Pull request merged**
