### PR TITLE
Fixed issue #15195: Expiration date can be set before start date

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]
Code is OK

Must really test if it's OK when return error in GUI and remotecontrol

**Comment by gabrieljenik** [comment]
Master implementation implements front end validations.
#2558

Let's review that before implementing the same on here.

**Review by Shnoulle — APPROVED** [review]

**Comment by gabrieljenik** [comment]
[15195-ConParche.webm](https://user-images.githubusercontent.com/4942495/192534081-334f7646-d733-454b-9257-be401e2bcaf7.webm)

Tested OK.

Wasn't tested on remote control. Still taking into account this has already been merged on master, we can safely merge here as well. What do you think?

@Shnoulle Remove the "Discussion" tag if you feel is OK :)

Thanks

**Comment by Shnoulle** [comment]
> Wasn't tested on remote control. Still taking into account this has already been merged on master, we can safely merge here as well. What do you think?

Yep

**Pull request merged**
