### PR TITLE
DEV: remove xdebug from running tests (travis)

### PR DESCRIPTION
**Pull request by TonisOrmisson**
should be a bit quicker
https://docs.travis-ci.com/user/speeding-up-the-build/

### CODE REVIEW

**Comment by olleharstedt** [comment]
Do we want this? It want debugging tests harder?

**Comment by TonisOrmisson** [comment]
How would you use xdebug in Travis envireonment?

the travis docs:

> PHP VM images on travis-ci.org provide several PHP versions which include XDebug. The XDebug extension is useful if you wish to generate code coverage reports in your Travis builds, but it has been shown to have a negative effect upon performance.
>
>You may wish to consider disabling the PHP XDebug extension for your builds if:
>
> you are not generating code coverage reports in your Travis tests; or
you are testing on PHP 7.0 or above and are able to use the PHP Debugger (phpdbg) which may be faster.

**Comment by olleharstedt** [comment]
D'uh, didn't realize it was only for travis. OK, great!

**Comment by TonisOrmisson** [comment]
just stumbled on it yesterday :)

**Pull request merged**
