### PR TITLE
Fixed issue #19501: Upgrade broke at 430 with ComfortUpdateChecker

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: check if already here

### CODE REVIEW

**Review by c-schmitz — APPROVED** [review]

**Comment by Shnoulle** [comment]
@c-schmitz the issue are not reproductible like this ;)

There are multiple ComfortUpdateChecker when you setup by default (i add index on the test server)

**Comment by Shnoulle** [comment]
PS : i think if you disable ComfortUpdateChecker before DB version 429 and update : it was added and then activated (or not ? unsure).

**Comment by tiborpacalat** [comment]
Denis, is there something else to be done here?

**Comment by Shnoulle** [comment]
> Denis, is there something else to be done here?

No i need to report the issue differently for master :)

**Pull request merged**
