### PR TITLE
New feature [PluginEvent]: Added a beforeResumeEmail plugin event to Save library

### PR DESCRIPTION
**Pull request by danguyf**
Dev: Added a beforeResumeEmail plugin event to Save library.

I should have included this with PR 2106. (This is my last PluginEvent PR related to email, honest!)

The same LS3 customer that I have who needs to be able to selectively alter the from and bounce of outgoing emails needs to intercept the emails sent when a survey is saved and the user is emailed how to resume it.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Yes, but if you need something in 3.X : i think best is to create a compatible event.

Else : currently i think i start forking 3.X, in december 5.X can be the official stable release and 3.X is the old stable. Since i need some event (for example : i need Expression event since month now …) : i add i can not move to 5./X in a 3.X fork …

**Comment by olleharstedt** [comment]
Hm, can you move this to dev branch, please? Normally we don't accept new features in an LTS version.

**Comment by Shnoulle** [comment]
> **Hm, can you move this to dev branch, please? Normally we don't accept new features in an LTS version.**

> Hm, can you move this to dev branch, please? Normally we don't accept new features in an LTS version.

Then : can close : master already have this event

**Comment by olleharstedt** [comment]
Thanks, Denis.

**Comment by danguyf** [comment]
No, the ENTIRE point of this PR is back-porting the event from LS5 to LS3 so that LS3 customers can make use of it and so that plugins can target LS3 and LS5 without complicated version-switching logic.

That this is submitted to 3.x-LTS is ENTIRELY INTENTIONAL.

Please reconsider.

**Comment by danguyf** [comment]
This adds a PluginEvent to LS3 that is found in LS4+, enabling plugins to target LS3+.  That seems worth adding to LS3, no?

**Comment by maziminke** [comment]
+1 for adding this to LS 3.x.

**Comment by DenisChenu** [comment]
My answer is for «Hm, can you move this to dev branch, please? Normally we don't accept new features in an LTS version.» only :).

Else my other comments are to be more plugin compatible from 3.X to 5.X (but register to unexisting plugin don't broke anything)

**Pull request closed without merging**
