### PR TITLE
Fixed issue #19526: debug=2 PHP8.1 : unable to send email without expiry

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: cast as string

### CODE REVIEW

**Comment by gabrieljenik** [comment]
cast as string or strval ? 
I think we usually use cast as string.
Probably they have the same results on most cases.
Wonder why you chose strval()

**Review by gabrieljenik — APPROVED** [review]
Code structure looks good

**Comment by gabrieljenik** [comment]
> cast as string or strval ? I think we usually use cast as string. Probably they have the same results on most cases. Wonder why you chose strval()

From AI:

In PHP, both casting a value to a string using (string) and using the strval() function serve the purpose of converting a value to a string. However, there are subtle differences between the two approaches:

Functionality: Both methods allow you to convert scalar values (like integers, floats, booleans, and objects that implement the __toString method) to strings. However, strval() cannot be used on arrays or objects that do not implement the __toString method, whereas (string) casting can be used in a broader range of contexts, including with arrays and objects that do not implement __toString.

Usage Context: strval() is a function call, making it explicit in the code that a conversion is taking place. On the other hand, (string) casting is an internal type casting method, which might be considered more concise and integrated within the language syntax.

Performance: In most practical scenarios, the performance difference between using strval() and (string) casting is negligible. However, in very specific performance-critical applications, there might be slight differences, though these are unlikely to be significant enough to impact the overall performance of your application.

Readability and Preference: Some developers prefer using (string) casting as it aligns with modern PHP practices and is seen as more readable and concise. Others might prefer strval() for its explicitness, especially in complex expressions where the type of conversion might not be immediately clear.

In summary, both strval() and (string) casting can be used interchangeably for converting values to strings in PHP. The choice between them often comes down to personal preference, readability considerations, and the specific requirements of your codebase.

**Comment by Shnoulle** [comment]
I always use strval, boolval etc … function, i really dislike cast system. I prefer function

**Pull request merged**
