### PR TITLE
Dev: Also deleted classes that are injected via coreClass

### PR DESCRIPTION
**Pull request by tammoterhark**

### CODE REVIEW

**Comment by Shnoulle** [comment]
I already fix double class : but not the ranking div .....

For table-bordered : if admin user add 

````
<table class="table-bordered">....</table>
````

To a question : he surely want it in question text. Then : please only apply to ls-answers part (or remove it if you prefer :) )

**Comment by tammoterhark** [comment]
I understand your hack, but I find it not elegant.

**Comment by Shnoulle** [comment]
I don't think it's a hack.

1. core HTML add table-bordered : because it's more clean to see the border by default (understand where is your mouse)
2. A template designer can prefer to hide this border : he can do it in template.css
3. The best way is to don't remove border, but hide it with transparent : border still here but not shown.

PS : in fact : i think "core list" must be bordered too (you know SkeletonQuest ;) ) : better see "where is my mouse : i i click here : it check THIS radio (and not another one).

Maybe the best is to leave border in default ?

**Comment by Shnoulle** [comment]
extra div done in https://github.com/LimeSurvey/LimeSurvey/commit/d38306bf57ff73174e32d02f974da16ffa330b09 thanks :)

**Comment by LouisGac** [comment]
Hack is a noble concept, it's the base of the OpenSource mentality.
https://en.wikipedia.org/wiki/Hacker_culture

You should not use it with this bad meaning, typical of Microsoft coders. 
https://en.wikipedia.org/wiki/Kludge#Computer_science

"_kludge_" is the word you choose use to speak about quick and dirty solutions.

**Comment by Shnoulle** [comment]
I like to be a hacker, not an issue, but here i think tammo think like a "bidouillage" in french. Here : i think it's the best way :)

**Comment by tammoterhark** [comment]
I just thought it was not elegant not to use table-bordered and to switch it off via ls-answers... 
http://en.bab.la/dictionary/french-english/bidouillage
I assume that you are right...

**Pull request closed without merging**
