### PR TITLE
Fixed issue #18201: Unable to import LSA file with MSSQL and debug set

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: check if $result['CONTRAINT_NAME'] exist before using it

### CODE REVIEW

**Comment by olleharstedt** [comment]
Heyyy, as I wrote on Cliq, why are you guys adding more PRs when there are 62 open already? :thinking: They should be tested, reviewed and merged. Any blockers?

**Comment by Shnoulle** [comment]
> Heyyy, as I wrote on Cliq, why are you guys adding more PRs when there are 62 open already? thinking They should be tested, reviewed and merged. Any blockers?

Because this one i need it … I already fix it in a fork, didn't update before fix is merged.

**Comment by Shnoulle** [comment]
Else : 

1. 3 current merge request assign to me (i semlf assign it)
2. 7 waiting my review : https://github.com/LimeSurvey/LimeSurvey/pulls?q=is%3Apr+is%3Aopen+user-review-requested%3A%40me

**Comment by olleharstedt** [comment]
Hmmmm.

Are you on Cliq, @Shnoulle ? What's a good channel to talk to both you and @gabrieljenik at the same time?

**Comment by Shnoulle** [comment]
You can ping me on cliq, i don't open it always.

**Comment by Shnoulle** [comment]
Tesed OK on my part (and don't see why it can throw issue)

**Pull request merged**
