### PR TITLE
Fixed issue #15529: Print answer wrongly includes hidden questions

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: check true/false loose comparison

### CODE REVIEW

**Comment by Shnoulle** [comment]
Can be cherry-picked to master

**Comment by Shnoulle** [comment]
@olleharstedt : you (LimeSurvey GMBH) cherry pick or i do it ?

**Comment by olleharstedt** [comment]
Hm, maybe GmbH is better for the LTS branch.

**Comment by Shnoulle** [comment]
Mmmm … you mean : fix in 4.X and LimeSurvey GMBH fix it in 3LTS ?

Denis
PS : i do the same fix for master just now

**Pull request merged**
