### PR TITLE
fix missing var

### PR DESCRIPTION
**Pull request by rouuuge**
Dev: only fixed missing var before variable

### CODE REVIEW

**Comment by olleharstedt** [comment]
Hi, thanks for your contribution! Does this fix a bug?

**Comment by rouuuge** [comment]
hi, I did not create a bug entry, because i tought that its just a small issue. there was this error in the console:

```
template-core.js:26 Uncaught TypeError: Assignment to constant variable.
    at Object.alertSurveyDialog (template-core.js:26)
    at 399578:1824
```

**Comment by maziminke** [comment]
@olleharstedt This is a pretty simple adjustment, just check the single line of adjusted code. Can be merged if you don't see any issues.

**Comment by olleharstedt** [comment]
> @olleharstedt This is a pretty simple adjustment, just check the single line of adjusted code. Can be merged if you don't see any issues.

I don't see any issues, but did anyone test it?

**Comment by maziminke** [comment]
@olleharstedt Did you actually look at the code adjustment :-)

It just initializes a JS variable correctly. How can this break anything?

**Comment by olleharstedt** [comment]
> It just initializes a JS variable correctly. How can this break anything?

It can break anything if some other code depends on this variable being global.

**Comment by c-schmitz** [comment]
@rouuuge Please provide feedback on how to reproduce the issue, because I cannot reproduce.

**Comment by c-schmitz** [comment]
No feedback.

**Pull request closed without merging**
