### PR TITLE
Fixed issue #16853: Inconsistent filter behaviour when create token

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: remove flattenText in controller
Dev: add some rules, leave LSYii_Validators

This one : allow tag, allow XSS by suiperadmin
The other one : disaloow tag and XSS for all users.

### CODE REVIEW

**Comment by Shnoulle** [comment]
have 2 other pull request : not same filter.

**Comment by Shnoulle** [comment]
PS : i do the master when 3 is merged

**Comment by Shnoulle** [comment]
Alternate : https://github.com/LimeSurvey/LimeSurvey/pull/1666

**Comment by cdorin93** [comment]
Hey @Shnoulle , saw that the fix was already pushed. Is it ok if I close the ticket :) ?

**Comment by Shnoulle** [comment]
Oh yes : not same filter used (XSS here)

**Pull request closed without merging**
