### PR TITLE
Fixed issue #18542: Plugins: PasswordRequirement plugin is not working properly

### PR DESCRIPTION
**Pull request by gabrieljenik**
Found bug while creating automated test on issue 18370

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]
:+1:

**Comment by olleharstedt** [comment]
> ✘ Create user expired

Hmm, this test was fixed or?

**Comment by gabrieljenik** [comment]
> > ✘ Create user expired
> 
> Hmm, this test was fixed or?

It was!

I will merge master again and check

**Comment by gabrieljenik** [comment]
It is very strange.
For commit [558396](https://github.com/LimeSurvey/LimeSurvey/pull/2847/commits/5583962906eee03e8eea9f35927ae25a03ee9e98), we have the following.

image

For push failed, but went good for pull?
Why do we have these 2 different push and pull? What do they mean?

**Comment by gabrieljenik** [comment]
Again. Pull is faiing, but push is good.
What's the difference in between them?

**Comment by gabrieljenik** [comment]
Test are green now. We should merge this first, then #2848

**Pull request merged**
