### PR TITLE
Fixed issue #18459: When filtering the survey list by a parent survey group, surveys assigned to a child survey group are not listed

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]

**Comment by Shnoulle** [comment]
OK the getParam('id') exist only in 3 :)

**Comment by gabrieljenik** [comment]
Green now :) Needed some merge from master

**Comment by tiborpacalat** [comment]
> Green now :) Needed some merge from master

It doesn't look green to me hm ...

https://github.com/LimeSurvey/LimeSurvey/actions/runs/5180786640

am I looking at the wrong run?

**Comment by tiborpacalat** [comment]
This is where it is failing still
Screenshot 2023-06-06 at 18 03 06

**Comment by gabrieljenik** [comment]
This is green now

**Pull request merged**
