### PR TITLE
Fixed model relations referring to in-existing objects, add unit test…

### PR DESCRIPTION
**Pull request by TonisOrmisson**
…s to check that

Fixed issue: 3 models had a broken relation referring to a class that did not exist

also added unit tests for a bunch of models to check that. 

The base BaseModelTestCase also allows some additional checks to be added easily for all models in the future

### CODE REVIEW

**Comment by gabrieljenik** [comment]
Nice..

**Comment by olleharstedt** [comment]
Looks good. Anything specific we should test?

**Comment by TonisOrmisson** [comment]
> Looks good. Anything specific we should test?

I'm not sure what you mean. 90% of the PR is added test code, the rest is a few bugs I stumbled on and what is now covered by the added tests.

**Comment by olleharstedt** [comment]
Merged into dev branch, will be live in release 5.5.

**Comment by Shnoulle** [comment]
> Merged into dev branch, will be live in release 5.5.

Dev branch don't broke API ?

I have 2 javascript workaround to put in dev (this week i think)

**Comment by olleharstedt** [comment]
> Dev branch don't broke API ?

If it does, we must bump major version, but preferably we collect all breaking commits in one go. Does this break API? Can you describe how?

**Comment by Shnoulle** [comment]
> > Dev branch don't broke API ?
> 
> If it does, we must bump major version, but preferably we collect all breaking commits in one go. Does this break API? Can you describe how?

https://github.com/LimeSurvey/LimeSurvey/commit/d820a52b72ddbb5abadd7b007ff65ee0e2d0d9d7

reverted by

https://github.com/LimeSurvey/LimeSurvey/commit/167f2d468ef4270d48cfe7845ef804bab6b62c1e

**Comment by olleharstedt** [comment]
@Shnoulle How is that related to this PR?

**Comment by Shnoulle** [comment]
Not to the PR only to «Merged into dev branch, will be live in release 5.5.» sentence.

Sorry …

**Comment by olleharstedt** [comment]
Alright, well, feel free to discuss further on Discord or Cliq. :)

**Comment by Shnoulle** [comment]
Discussion on the related PR :)

Close here.

**Pull request merged**
