### PR TITLE
New Feature: Export to SPSS sav core plugin (for develop branch)

### PR DESCRIPTION
**Pull request by adamzammit**
Dev: Updates database version to 444

### CODE REVIEW

**Comment by olleharstedt** [comment]
Do we have a Mantis ticket for this feature, where we can discuss it?

**Comment by adamzammit** [comment]
@olleharstedt - here it is: https://bugs.limesurvey.org/view.php?id=17226

**Review by c-schmitz — APPROVED** [review]

**Comment by olleharstedt** [comment]
As I mentioned in the ticket, I'm not sure about the fact that we have two vendor/ folders in the system now. How would we check this for third-party security updates, for example?

**Comment by Shnoulle** [comment]
Maybe add a way for "library" by and for plugin ?

See https://gitlab.com/SondagesPro/coreAndTools/limeMpdf for example.

This plugin do … nothing… just offer a librarie for other plugin.

Then in 5.X : upload/lib/ or something like that .

Core lib are in app/core/lib/

**Comment by Shnoulle** [comment]
Related feature request : https://bugs.limesurvey.org/view.php?id=14567

See https://programmer.spip.net/Installing-external-libraries for a usage sample on another tool.

**Comment by c-schmitz** [comment]
> As I mentioned in the ticket, I'm not sure about the fact that we have two vendor/ folders in the system now. How would we check this for third-party security updates, for example?

I agree. So if this is a core plugin it would need to use core folders, because we need to maintain any libraryies . If it isn't a core plugin then it doesn't need to, because the original author needs to take care of that.

**Comment by adamzammit** [comment]
Hi again,

It looks like the twofactor authentication plugin has it's own vendor directory too, following the same pattern as this feature request:

https://github.com/LimeSurvey/LimeSurvey/tree/master/application/core/plugins/TwoFactorAdminLogin/vendor

Do both of these have to change or should this be ok to proceed as is?

**Comment by olleharstedt** [comment]
Yeah, 2FA plugin should also not have its own composer folder, since it's core.

**Comment by Shnoulle** [comment]
remind to update the [Minor Semantic Versioning number](https://semver.org/) for plugin, theme and other :)

**Comment by adamzammit** [comment]
Ok I've make a new pull request with the dependencies being put in core: https://github.com/LimeSurvey/LimeSurvey/pull/1877

**Pull request closed without merging**
