### PR TITLE
DEV: remove getBaseLanguageFromSurveyID() and replace all occurances

### PR DESCRIPTION
**Pull request by TonisOrmisson**
getBaseLanguageFromSurveyID() is a deprecated method. 
looked up all occurances & replaced with $oSurvey->language

### CODE REVIEW

**Comment by Shnoulle** [comment]
👍 

I think direct usage of `Survey::model()->findByPk($iSurveyId)->language` is OK everywhere

Next step `Survey::model()->findByPk($iSurveyId)->getAllLanguages();` [getAllLanguage](https://github.com/LimeSurvey/LimeSurvey/blob/master/application/models/Survey.php#L404)

**Comment by Shnoulle** [comment]
conflict by other merge :(

**Comment by TonisOrmisson** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/748

**Comment by TonisOrmisson** [comment]
I had the feeling I had done all this today already :)

**Pull request closed without merging**
