### PR TITLE
New feature: allow selecting MySql engine (MyIsam vs InnoDB)

### PR DESCRIPTION
**Pull request by TonisOrmisson**
Something we discussed in one meeting.
I have tested the installation on local dev mariadb and multiple instances on Google Cloud SQL. 

I would appreciate any testing, & reviews enhancements. 
This probably needs a Warning note to describe what it means to select InnoDb

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
Seems like ot has problems with key lengths. I'll look into that.

**Comment by c-schmitz** [comment]
This needs to go to develop, instead.

**Comment by TonisOrmisson** [comment]
Its kind of a hard one. I am running this myself on a master version. my master-innodb. Since I want to run master, but allowing innodb. I do not want to run on develop :|

**Comment by TonisOrmisson** [comment]
I asked about develop branch plan yesterday on meeting. If there was a clear target plan for develop then I could push it to there

**Pull request closed without merging**
