### PR TITLE
Fixed issue #19081: Lato fonts are loaded from Google fonts instead of solely using the ones shipped with limesurvey itself

### PR DESCRIPTION
**Pull request by gabrieljenik**
Lato font url modified to load locally.

Other variations may need to be updated. Waiting on feedback before moving forward

### CODE REVIEW

**Comment by Shnoulle** [comment]
No generator ?

**Review by Shnoulle — APPROVED** [review]

**Comment by gabrieljenik** [comment]
> No generator ?

When discussing it was concluded it was an overkill

**Comment by Shnoulle** [comment]
Already approved

**Comment by Shnoulle** [comment]
`import url(../../../../../assets/fonts/lato.css)` with asset and without asset ? With debug=0 or 1 ?

**Review by Shnoulle — COMMENTED** [review]
Question about position of the file according to debug mode or not ?

See ['use_asset_manager' ](https://github.com/LimeSurvey/LimeSurvey/blob/d9fe0a0e4b3e19e4f2ffbd6b66cc7d25ad9041cd/application/core/LSYii_ClientScript.php#L182)

**Comment by gabrieljenik** [comment]
> `import url(../../../../../assets/fonts/lato.css)` with asset and without asset ? With debug=0 or 1 ?

Not sure I understand the comment. Still, how do you suggest to do the import?

**Comment by gabrieljenik** [comment]
> Question about position of the file according to debug mode or not ?
> 
> See ['use_asset_manager' ](https://github.com/LimeSurvey/LimeSurvey/blob/d9fe0a0e4b3e19e4f2ffbd6b66cc7d25ad9041cd/application/core/LSYii_ClientScript.php#L182)

But here is a CSS, no PHP... Not sure I get the comment.

**Comment by Shnoulle** [comment]
> > Question about position of the file according to debug mode or not ?
> > See ['use_asset_manager' ](https://github.com/LimeSurvey/LimeSurvey/blob/d9fe0a0e4b3e19e4f2ffbd6b66cc7d25ad9041cd/application/core/LSYii_ClientScript.php#L182)
> 
> But here is a CSS, no PHP... Not sure I get the comment.

asset_manager are related to CSS/script image, logo etc … any file you want in assets …

**Comment by gabrieljenik** [comment]
> If you use asset manager : themes/survey/bootswatch/ was copied to tmp/assets/[randomstring] don't know for fonts.

Oh, I see.... Let me review.

**Comment by Shnoulle** [comment]
OK it work because `themes/survey/bootswatch` and `tmp/assets/8aabd431` have same directory …

But unable to do it for uploaded theme :(

**Review by Shnoulle — APPROVED** [review]
OK for the purpose …

**Comment by gabrieljenik** [comment]
> OK it work because `themes/survey/bootswatch` and `tmp/assets/8aabd431` have same directory number …

Yes, there is a further explanation on mantis.

**Pull request merged**
