### PR TITLE
Fixed issue #17024: Missing string to translate

### PR DESCRIPTION
**Pull request by gabrieljenik**
Porting #16729 to LS4

### CODE REVIEW

**Comment by olleharstedt** [comment]
We didn't already have one of these dummy files...?

**Comment by Shnoulle** [comment]
I really think it's better to add such line near the place it was used, just before the twig call :)

**Comment by gabrieljenik** [comment]
> I really think it's better to add such line near the place it was used, just before the twig call :)

Where? Sorry I don;tunderstand.

**Comment by Shnoulle** [comment]
Here : the string are related to after survey complete ?

Then : aroyund here : https://github.com/LimeSurvey/LimeSurvey/blob/da4b348a1ef832e7b9eaec8c7687ecd6d5480db6/application/helpers/SurveyRuntimeHelper.php#L1335 

```
/* @var string[] language string used in  twig file
$language = array(
     "Your survey responses have not been recorded. This survey is not yet active." => gT("Your survey responses have not been recorded. This survey is not yet active."), // themes/survey/vanilla/views/subviews/content/submit_preview.twig:23  (2020-11-16)
);
$sHtml = Yii::app()->twigRenderer->renderTemplateFromFile("layout_global.twig", array('oSurvey' => $oSurvey, 'aSurveyInfo' => $this->aSurveyInfo, 'language'=>$language), true);
```

**Comment by gabrieljenik** [comment]
Hmmm not sure...
Having them all budled up together seems easier to handle.
Why putting it there? What use case?

**Comment by Shnoulle** [comment]
> Why putting it there? What use case?

For translator : https://translate.limesurvey.org/projects/limesurvey-3/fr/default/ really more easy …

Capture d’écran du 2021-02-17 17-59-50

**Comment by gabrieljenik** [comment]
I don't believe this is the right choice for this kind of messages.
A string that is used in a twig may be used on multiple twigs, but I guess it will be only inserted once on the php files. (Only for having the translator grep to find them).

So the references part may actually turn confusing.

Don't see such a clear benefit.
Actually I see more work in placing them on specific places on the php files, than on a generl file.

**Pull request merged**
