### PR TITLE
Use onchange instead of onkeyup event

### PR DESCRIPTION
**Pull request by fmorote**
Use onchange instead of onkeyup event, now copy&paste token with mouse activates submit button

### CODE REVIEW

**Comment by SamMousa** [comment]
Why not use oninput?
http://www.w3schools.com/tags/ev_oninput.asp

**Comment by Shnoulle** [comment]
And better : why not using .on from jquery ?

**Comment by SamMousa** [comment]
Well even if we use jquery we have to pick an event.

**Comment by Shnoulle** [comment]
Yes, but with jquery : using multiple event is very easy :) . And here a blur seems better maybe ?

**Comment by fmorote** [comment]
The oninput event is supported in Mozilla Firefox , chrome, safari, Opera, Internet Explorer from version 9. If LS does not suport <IE 9, not problem :smile:

**Comment by Shnoulle** [comment]
We don't support IE < 9 for admin part :). Only for public part.

**Comment by fmorote** [comment]
Works perfect for me, i apply the change

**Pull request merged**
