### PR TITLE
Alternative for slider

### PR DESCRIPTION
**Pull request by tammoterhark**
Still needs some adaptation in css...

### CODE REVIEW

**Comment by tammoterhark** [comment]
@Shnoulle

**Comment by Shnoulle** [comment]
Already answered : don't move HTML element for visual issue : visual is a css job.

**Comment by tammoterhark** [comment]
OK, I delete this branche.

**Comment by Shnoulle** [comment]
Have an idea too with js and .clone().addClass.

**Comment by tammoterhark** [comment]
Great!

**Pull request closed without merging**
