### PR TITLE
[WIP] Add min/max test

### PR DESCRIPTION
**Pull request by Shnoulle**
Need the other one

### CODE REVIEW

**Comment by Shnoulle** [comment]
@olleharstedt : maybe need your advice for https://github.com/LimeSurvey/LimeSurvey/pull/1290/commits/e028a3677c7a1b6635a9ffe6a41ad150a316f372 part (not finalized : to do : other id + move next for PHP)

**Comment by olleharstedt** [comment]
Hooray, a test! Will check tomorrow at work.

**Comment by Shnoulle** [comment]
Travis don't run 😿

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/1289#issuecomment-499789183

**Pull request closed without merging**
