### PR TITLE
Update answerOptionsEdit_view.twig

### PR DESCRIPTION
**Pull request by neilzone**
Fix typo: "Prefedined" to "Predefined"

Fixed issue # : 
New feature # :
Changed feature # :
Dev: 
Dev:

### CODE REVIEW

**Comment by Shnoulle** [comment]
Why not in master ?

**Comment by neilzone** [comment]
Sorry if I've put it against the wrong branch — I'd (wrongly) guessed you might want to it against dev, before moving to master in future / if accepted.

**Comment by Shnoulle** [comment]
master : current with only fix currently.
Dev: in develop with a lot of new feature

master is merged in develop, not develop in master :).

**Comment by dominikvitt** [comment]
Yes, this and your other PR should go to master.
Looks that deleting and recreating those PR's in master is only possible way to change it.
Also make sure that you pulled the latest master branch changes.

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/1257/files

**Pull request closed without merging**
