### PR TITLE
New feature: NUMBEROFGROUPS replacement field on welcome template (#11716) Updated

### PR DESCRIPTION
**Pull request by mfavetti**
This broke the admin panel because it had no default value. Just added one like totalquestions has.

### CODE REVIEW

**Comment by mfavetti** [comment]
Original: https://github.com/LimeSurvey/LimeSurvey/pull/545

**Comment by Shnoulle** [comment]
Think it's better to do , in template_replace

    $oSurvey=Survey::model()->findByPk($_surveyid);
    if($oSurvey){
      $totalgroups=$oSurvey->->getNumberOfGroups(); /* function to construct */
      /* Can add some other variable here */
    } else {
      $totalgroups="";
    }
    $coreReplacements['NUMBEROFGROUPS']=$totalgroups;

Because : i really think we must remove &$redata = array() and just use $replacements step by step. _Currently : think we must use only $this->varname or $this->areplacemet, but @LouisGac have already work on it in twig version_

**Comment by LouisGac** [comment]
thank you for watching the merge of your commits

**Comment by mfavetti** [comment]
@Shnoulle I'm a bit confused what you want. So currently, the count is pulled from:

QuestionGroup::model()->getTotalGroupsWithQuestions($surveyid) on line 1043 of frontend_helper.php
and is added to the session. (I just duplicated the functionality of the totalquestions replacement.)

The problem is that if that variable is not set in the session, there is an undefined variable notice for line 689 of replacements_helper.php so I added a default zero for totalgroups just like totalquestions has, which fixes the notice.

Instead you would like the totalgroups to be set in templatereplace() of replacements_helper.php (rather than in buildsurveysession() of frontend_helper.php)?

 I added another commit can you see if it's what you meant?

**Comment by Shnoulle** [comment]
PS : i prefer like this : yes : i think

1. remove this awfull &$redata must be done , and each var in &$redata was to be removed one by one.
2. filling session again and again seems a false bad idea on my POV.

prefer this one.

I test and merge

**Pull request merged**
