### PR TITLE
Backport of feature "Soft Mandatory Prompt - T144" to LS3

### PR DESCRIPTION
**Pull request by adamzammit**
Dev:   Based on:  https://github.com/LimeSurvey/LimeSurvey/commit/a4ec47355e05ce198b32fa307e71a34cebb6b413
Dev:    https://github.com/LimeSurvey/LimeSurvey/commit/f6a9b3082bd0cf8306129d73382ee23e0740dc64
Dev:    from LS4 branch

New feature #12088

I don't expect this to be merged as it is a new feature in the 3.x branch but wanted it here in case anyone else wants to use it.

### CODE REVIEW

**Comment by cdorin93** [comment]
Thanks for contribution, @adamzammit :+1:

**Comment by maziminke** [comment]
How many boxes of beer do I need to send to Hamburg to bribe the development team to accept this pull request for LS3.x?
:-)

**Comment by cdorin93** [comment]
You can send them - we will discuss after we finish the box**es** if more is needed :)

**Comment by olleharstedt** [comment]
Looks like a nice feature to merge.

**Comment by Shnoulle** [comment]
> Looks like a nice feature to merge.

If we backport new feature from 4X to 3.X : why didn't allowing new feature in 3.X ?

**Comment by Shnoulle** [comment]
And clearly : it's not the 1st one i backport (since there are workaround solution)

**Comment by Shnoulle** [comment]
PS : did the issue with this feature are backported too ? 

https://github.com/LimeSurvey/LimeSurvey/commit/f6a9b3082bd0cf8306129d73382ee23e0740dc64 

Else : can leave mandatory answer empty.

**Comment by olleharstedt** [comment]
Closing this, since LS5 is considered stable enough.

**Pull request closed without merging**
