### PR TITLE
Fixed issue #17093: Unable to fix invalid survey after import bad TSV

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: fix it after import, and add some other fix.
Dev: taken from database

### CODE REVIEW

**Comment by Shnoulle** [comment]
https://bugs.limesurvey.org/view.php?id=17093

**Comment by c-schmitz** [comment]
I was thinking that maybe this patch should go to develop branch instead. It is not urgent and might introduce instability.
There is also a workaround by running the integrity check.

**Comment by Shnoulle** [comment]
I don't see how it introduce instability?
Broken TSV are really hard to fix and happen a lot … 

The biggest issue are : page is totally broken, survey can not be edited / fixed ¿

Fix this line https://github.com/LimeSurvey/LimeSurvey/blob/cbb5e0735281c93f9132a9d21e9fbc8d79955ac5/application/controllers/admin/surveyadmin.php#L1695 by

````
 $aSurveyLanguageSettings = SurveyLanguageSetting::model()->findByPk(array('surveyls_survey_id' => $survey->sid, 'surveyls_language' => $sLang))->getAttributes();
 $oSurveyLanguageSettings = SurveyLanguageSetting::model()->findByPk(array('surveyls_survey_id' => $survey->sid, 'surveyls_language' => $sLang));
 if(empty($oSurveyLanguageSettings)) {
    // ? Create a new one dinamically ?
    $oSurveyLanguageSettings = new SurveyLanguageSetting;
    $oSurveyLanguageSettings->surveyls_language = $sLang;
    $oSurveyLanguageSettings->surveyls_survey_id = $survey->sid;
 }
 $aSurveyLanguageSettings = $oSurveyLanguageSettings->getAttributes();
```

?

**Comment by Shnoulle** [comment]
But i can create a function in develop …  (this function seems really needed)

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/1774

**Pull request closed without merging**
