### PR TITLE
fixed #12639 Quota end-url does not allow surrounding EM

### PR DESCRIPTION
**Pull request by TonisOrmisson**
https://bugs.limesurvey.org/view.php?id=12639

### CODE REVIEW

**Comment by Shnoulle** [comment]
In commit history : https://github.com/TonisOrmisson/LimeSurvey/commit/bd86ccfd2884e7acb439fe2e425fdbf824a1e126#diff-f9dd264368810c6303206b6b095991cfR77

Else Surey admin can add XSS even if they don't have the right to do, and we fix some other part.

**Comment by TonisOrmisson** [comment]
this is still there
https://github.com/LimeSurvey/LimeSurvey/pull/798/files#diff-f9dd264368810c6303206b6b095991cfL88

When I was changing the form to use Yii logic I also added Yii default url validation rule. But I did not realize that an url can be **surrounded** by EM also, so generic url validation is not an oprion.

**Comment by Shnoulle** [comment]
Ah yes , we have 2 rules ??? `array('quotals_url','LSYii_Validators','isUrl'=>true),` and `array('quotals_url','urlValidator'),` urlValidator didn't break Expression ? It's needed with isUrl=>true ?

**Comment by Shnoulle** [comment]
I think we must remove urlValidtor too , see http://www.yiiframework.com/doc/api/1.1/CUrlValidator#defaultScheme-detail

**Comment by TonisOrmisson** [comment]
no
urlValidator refers to custom:
https://github.com/LimeSurvey/LimeSurvey/pull/798/files#diff-f9dd264368810c6303206b6b095991cfR94

This cheks url to be mandatory if redirection is enabled. 
the CUrlValidator should defined as  `array('quotals_url','url'),` Which Is what I deleted

**Pull request merged**
