### PR TITLE
Just to check

### PR DESCRIPTION
**Pull request by Shnoulle**

### CODE REVIEW

**Comment by dominikvitt** [comment]
@Shnoulle I just merged it, please check

**Comment by Shnoulle** [comment]
My coomit don't seem broken … ?

**Comment by Shnoulle** [comment]
Surely need to rebuild admin js and css

**Comment by dominikvitt** [comment]
@Shnoulle You maybe don't know, but in develop branch we don't use gulp anymore to rebuild admin assets.
Instead you should use something like this: 
/usr/local/bin/yarn run build

It is defined in assets/packages/adminbasics/package.json

**Comment by Shnoulle** [comment]
Ok, thanks for information :)

**Pull request merged**
