### PR TITLE
Fixed issue #16375: Theme with valid config.xml (according to manual)…

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #16375: Theme with valid config.xml (according to manual) can not be extendable
Dev: create if not set
Dev: allow last_update or lastUpdate only for 4.X
Dev: then 3.X still an LTS

### CODE REVIEW

**Comment by olleharstedt** [comment]
How about someone tests this before merge?

**Comment by Shnoulle** [comment]
I don't see a way to add a test

**Comment by Shnoulle** [comment]
And 11 days between report, Marcel do a test because he have the issue too.

**Comment by olleharstedt** [comment]
No, but Sushma, our QA, should test it before merge. :)

**Comment by Shnoulle** [comment]
OK, for next time then :)

**Pull request merged**
