### PR TITLE
Fixed issue #15611: No HTML wrapper in public stats

### PR DESCRIPTION
**Pull request by gabrieljenik**
Created new twig views for statistics for using as frame (based on print view)

### CODE REVIEW

**Comment by Shnoulle** [comment]
Can not use only `/subviews/content/statistics_user.twig` ?

PS : this broke all potential theme not based on Vanilla : we must really create a real core theme (no new file in ` themes/survey/vanilla/views/` )

**Comment by gabrieljenik** [comment]
> Can not use only `/subviews/content/statistics_user.twig` ?

You mean dropping `layout_statistics_user.twig`?
How's that better? Wouldn't that still be incompatible with current themes?

**Comment by Shnoulle** [comment]
>  How's that better? Wouldn't that still be incompatible with current themes?

Ah right 👍 

I must report an issue : have a real notemplate system … then : we can really imporve LS core but allow template based on something other :)

**Review by eddylackmann — APPROVED** [review]

**Comment by Shnoulle** [comment]
No 3.LST fix ?

**Comment by gabrieljenik** [comment]
@cdorin93 should we create a new ticket for this?

**Comment by Shnoulle** [comment]
> @cdorin93 should we create a new ticket for this?

https://bugs.limesurvey.org/view.php?id=15612 :)

**Comment by gabrieljenik** [comment]
haha my bad! :)

**Pull request merged**
