### PR TITLE
Dev: feature : allow plugin to use another plugin translation

### PR DESCRIPTION
**Pull request by Shnoulle**
Just update name of name of component , can be improved by `gT($sToTranslate, $sEscapeMode = 'html', $sLanguage = null,$pluginClass = null)`

### CODE REVIEW

**Comment by olleharstedt** [comment]
OK to merge, no?

**Comment by Shnoulle** [comment]
Yes, it's just to know if you have any reason to use plugin->id :)

**Comment by olleharstedt** [comment]
No, looks fine. It's not yet possible to install more than one instance of a plugin (and never will be?).

**Comment by Shnoulle** [comment]
It's not possible to have 2 plugins with same ClassName :). I think PHP broke at 100% here … except when we allow plugin to have namespace (but then get_class return `\namespace\ClassName` : maybe i can check this for LS version 12 ?) 

Maybe it's possible to have 2 plugins with same name (since it's in a variable).

It's the reason why i choose ClassName (and never use $this->name now …)

**Comment by olleharstedt** [comment]
Good point.

**Pull request merged**
