### PR TITLE
Fixed issue #10299: template preview not found on Survey quick actions

### PR DESCRIPTION
**Pull request by BertHankes**
Fixed issue #10299: template preview not found on Survey quick actions

### CODE REVIEW

**Comment by Shnoulle** [comment]
No ;). If you want attribution automatcially : see 
https://github.com/LimeSurvey/LimeSurvey/pull/498/commits/7da08ef10976176166ece6f732dd02e605fd8e13

Compare with https://github.com/LimeSurvey/LimeSurvey/commit/b20a86840768e274bffd131555aaff02328542b2 foir example

;)

**Comment by BertHankes** [comment]
My first contribution.. bare with me!
better now?

**Comment by Shnoulle** [comment]
I think 2nd line is OK , but for next time : i think 1st line is OK

See screenshot (with direct edition on github)
capture du 2016-05-30 10-59-48

**Comment by LouisGac** [comment]
thank you for contributing. 
you did a great work.

**Comment by BertHankes** [comment]
For me a direct commit* feels like to risky for I'm not part of the Limesurvey team.
Learned a lot about the proces of github though.. so the next time I'll do better (I promise :-)

*I will look into that.. never noticed that option, but it does not feel right to me to use it!

**Comment by LouisGac** [comment]
BertHankes: don't worry. Respecting all the commit rules is important for team dev. 
The important thing for external dev is to contribute:  better to have a pull request fixing a bug with a wrong commit message than no pull request at all. 
So don't hesitate to contribute.

**Comment by BertHankes** [comment]
160529: I hope you won't forget me :-)

**Comment by c-schmitz** [comment]
I will just merge it now ;).

**Comment by BertHankes** [comment]
Tnx!

**Pull request merged**
