### PR TITLE
Fixed issue #17521: HTML is not escaped in timer messages

### PR DESCRIPTION
**Pull request by gabrieljenik**
Escaping text. Adding automatic test.

### CODE REVIEW

**Comment by c-schmitz** [comment]
Not sure if just quoting is correct. Should we allow maybe basic HTML here and only XSS-filter?

**Comment by olleharstedt** [comment]
Another alternative could be to include an `<xss>1</xss>` attribute for question attributes in the question config.xml files.

**Comment by olleharstedt** [comment]
This method filters model attributes: https://github.com/LimeSurvey/LimeSurvey/blob/master/application/core/LSYii_Validators.php#L113

**Comment by gabrieljenik** [comment]
> Another alternative could be to include an `<xss>1</xss>` attribute for question attributes in the question config.xml files.

What would this be for? XSS-on/off depends on the attribute or on the user?

**Comment by olleharstedt** [comment]
> What would this be for? XSS-on/off depends on the attribute or on the user?

Depending on the attribute. If the attribute is numeric, you don't need to filter it, for example.

**Comment by gabrieljenik** [comment]
> > What would this be for? XSS-on/off depends on the attribute or on the user?
> 
> Depending on the attribute. If the attribute is numeric, you don't need to filter it, for example.

I mean, why we should trust the XSS filtering setting on the question-theme.

**Pull request merged**
