### PR TITLE
Fixed issue #18798: Out-of-memory problem in statistics export

### PR DESCRIPTION
**Pull request by olleharstedt**
Fixed issue #<Mantis issue number>:
New feature #<Mantis issue number>:
Dev:

### CODE REVIEW

**Comment by twilligls** [comment]
Did a code review, looks fine to me. 
Needs to be properly tested now

**Comment by twilligls** [comment]
@tiborpacalat can you maybe test that?

**Comment by olleharstedt** [comment]
@gabrieljenik This PR broke the CI. Please redo and make sure the 5.x branch is merged into the PR.

**Comment by gabrieljenik** [comment]
Following up on #3231

**Pull request merged**
