### PR TITLE
Fixed issue #16979: Email continue not shown clearly after activation

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by olleharstedt** [comment]
Not sure I can test this without having a working email server setup?

**Comment by gabrieljenik** [comment]
mailtrap.io?

**Comment by Shnoulle** [comment]
mail can broke n : it try to sent again and again …

**Comment by Shnoulle** [comment]
Peek 22-02-2021 12-16


Just a minor issue when click on cancel : but it's another issue in my opinion

**Review by Shnoulle — APPROVED** [review]
👍

**Comment by olleharstedt** [comment]
Is this ported to LS4 too? Or already fixed?

**Pull request merged**
