### PR TITLE
$closeUrl undefined

### PR DESCRIPTION
**Pull request by mantis**
$closeUrl undefined

Fixed issue #<Mantis issue number>:
New feature #<Mantis issue number>:
Dev:

### CODE REVIEW

**Comment by olleharstedt** [comment]
Which bug does this issue fix?

**Comment by grangeway** [comment]
Olle,

When importing trying to import from LDAP in the latest version, it wasn't working as closeURL was not defined.

Thanks

**Comment by olleharstedt** [comment]
OK, can you report the bug please so we can relate the PR to an issue?

**Comment by grangeway** [comment]
Hi,

I can't see how to report a bug in github

**Comment by olleharstedt** [comment]
No, you'd have to do it here: https://bugs.limesurvey.org/my_view_page.php

**Comment by grangeway** [comment]
I'm not going to sign up for a separate system - feel free to accept this PR or not.

**Pull request closed without merging**
