### PR TITLE
Master fix num auto theme

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue : usage of bNumRealValue from config
 New feature : allow update of fix num auto in core themes

### CODE REVIEW

**Comment by Shnoulle** [comment]
@olleharstedt You ask, i do it …

**Comment by Shnoulle** [comment]
Need revert : https://github.com/LimeSurvey/LimeSurvey/commit/2e13dfb5b3155939851778e7f91c2a72231018de to be complete (else need only one option)

**Comment by olleharstedt** [comment]
OK, will try.

**Comment by olleharstedt** [comment]
Tried to revert and merge this, but for me it does not replicate the behaviour that was the point of Dominik's commit: To make "asd" get deleted.

**Comment by Shnoulle** [comment]
I NEVER say asd was deleted …

Let me check if current «fix» `123.123.123` to an empty value and do same in next commit

**Comment by olleharstedt** [comment]
> I NEVER say asd was deleted …

I think that was our problem. :laughing: 

Thanks for fixing it, it's all good now.

**Pull request merged**
