### PR TITLE
Update to yii1.1.20

### PR DESCRIPTION
**Pull request by Shnoulle**
Apply 2 fix for PHP7.2, one in yii, one not currently

### CODE REVIEW

**Comment by Shnoulle** [comment]
I leave https://github.com/LimeSurvey/LimeSurvey/commit/b4bde1dd8a32eca97f7131623e68a4d195fbb374#diff-9c2281f0a0d7741f169d7488c4df6a7eR218 : i don't think it's a security issue here (or a real issue)

**Comment by Shnoulle** [comment]
@c-schmitz : you merge it ? I want to fix whole create_function in Yii1 too (to have a cleaner update next time). but they need a PHP5.1 compat system … :/

**Comment by maziminke** [comment]
Are there any plans to switch to Yii 2 for the upcoming Limesurvey 4 version?

**Comment by c-schmitz** [comment]
@maziminke Not planned for v4. There is currently neither priority nor resources for that.

**Pull request merged**
