### PR TITLE
Fixed issue #18087: Focus is jumping in the survey structure

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by c-schmitz** [comment]
That actually made it worse. The Problem is that the tool menu disappears. It should be visible, imho. The user owns the survey, so according to permissions it should be visible, unless I am mistaken.

**Review by c-schmitz — CHANGES_REQUESTED** [review]
now the tools menu is not visible at all.

**Comment by Shnoulle** [comment]
Maybe all button must be show in editor view too …

**Comment by gabrieljenik** [comment]
Will continue discussion on Mantis

**Comment by c-schmitz** [comment]
Thanks, great work.

**Pull request merged**
