### PR TITLE
Dev: add a test for array/checkbox

### PR DESCRIPTION
**Pull request by Shnoulle**

### CODE REVIEW

**Comment by Shnoulle** [comment]
@olleharstedt 
Local checking : 

````
# sudo -u www-data DOMAIN=localhost phpunit tests/questions/ArrayNumberCheckboxTest.php 
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 10.87 seconds, Memory: 18.00MB

OK (1 test, 8 assertions)
````
But here broke at last , i try with a sleep(2) :)

**Comment by olleharstedt** [comment]
Great, Denis!

**Comment by Shnoulle** [comment]
It take me time, but now i have my local checker on virtualbox, i must set up one with KVM only now and a docker for travis :)

**Comment by olleharstedt** [comment]
What's KVM?

**Comment by olleharstedt** [comment]
Ah, virtualization.

**Comment by olleharstedt** [comment]
Instructions for setting up a travis clone locally are in tests/data/travis/travis_setup.sh.

**Comment by Shnoulle** [comment]
> Instructions for setting up a travis clone locally are in tests/data/travis/travis_setup.sh.

Yes, but usage of docker, and it's more easy for me to virtualize all and update directly in the fork :)

**Comment by olleharstedt** [comment]
:+1:

**Pull request merged**
