### PR TITLE
Fixed issue #18094: Broken view in uploader

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by Shnoulle** [comment]
conflict ;)
I can test on firefox / chrome / midori easily. You do the test on edge ?

**Comment by gabrieljenik** [comment]
We removed the Flex.
Still notice it wasn't introduced on this PR, but previously (aa00a0a5). 
Maybe for having file title to the right?

**Comment by Shnoulle** [comment]
> Maybe for having file title to the right?

Theme task, not from core .
core must do the minimum :)

**Review by Shnoulle — APPROVED** [review]

**Comment by Shnoulle** [comment]
PS : why we must use bs and not specific css 

Capture d’écran du 2022-06-20 17-58-19

**Pull request merged**
