### PR TITLE
FIxed issue #12178: fix quota-grid errors if no quotas

### PR DESCRIPTION
**Pull request by TonisOrmisson**
Seems it's broken if no quotas

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
Seems I had some files on different branch so I missed that during development. 
Need to review my dev environment set-up :|

**Comment by Shnoulle** [comment]
No issue with https://github.com/LimeSurvey/LimeSurvey/commit/fcf7408714b3bbd646a7baab831df91e5ea8b738 version

capture du 2017-03-07 23-28-21

Seems OK ?

**Comment by Shnoulle** [comment]
Oups, better understand : no quota, not no quota member ....

**Comment by TonisOrmisson** [comment]
@Shnoulle thanks!

**Comment by Shnoulle** [comment]
I have some other issue ( exemple : Auto load url to Y by default, status : it's unclear) but this one os OK :)

**Comment by Shnoulle** [comment]
@TonisOrmisson  , can you have a look at 

- https://bugs.limesurvey.org/view.php?id=12183
- Update `'active'=> gT("Status"),` to `'active'=> gT("Active"),` , OR : Yes to 'Active' and No to 'Inactive'

**Pull request merged**
