### PR TITLE
Master before question render add answer

### PR DESCRIPTION
**Pull request by Shnoulle**
Adding the ANSWER part for beforeRenderQuestion.
answer is clearly a RenderingQuestion part and seems very cooool to be updated.

### CODE REVIEW

**Comment by Shnoulle** [comment]
And question help is not inside event too : help is 'quanda help' only

**Comment by c-schmitz** [comment]
@Shnoulle Can you do it for 2.06 please?

**Comment by Shnoulle** [comment]
http://bugs.limesurvey.org/view.php?id=9500 : I'm not sure for the best solution : updating SurveyRunTime or replacement_helper.

Denis

**Comment by Shnoulle** [comment]
* 2.06 : https://github.com/LimeSurvey/LimeSurvey/commit/1d9b183aad911e2cdb85aeea4b8e1c1e0c60af73
* 2.05 : https://github.com/LimeSurvey/LimeSurvey/commit/9618b2f71965175b2965ed48b3b63296993e5d90 + https://github.com/LimeSurvey/LimeSurvey/commit/5500ed612c2319b030f1d127ffbd9b3e85a671d4

**Pull request closed without merging**
