### PR TITLE
Fixed issue # 17207: When attaching using the theme editor, full path is displayed on the screen

### PR DESCRIPTION
**Pull request by gabrieljenik**
Removing root dir from displayed path

### CODE REVIEW

**Comment by Shnoulle** [comment]
This fix windows issue too.
I close in mantis

**Review by Shnoulle — COMMENTED** [review]
Fix windows issue too :)

- [16905](https://bugs.limesurvey.org/view.php?id=16905): Windows server : good attachment throw JS error (and broke all JS action)
- [16903](https://bugs.limesurvey.org/view.php?id=16903): Windows server : unable to save attachements

**Comment by gabrieljenik** [comment]
Are you sure this ticket is the one that solved those issues? This is about theme editor while issues below are about email templates

**Comment by Shnoulle** [comment]
Ag … lol

https://github.com/LimeSurvey/LimeSurvey/commit/dba28941138fb537f3c04f481f43eceb3f08f150

**Pull request merged**
