### PR TITLE
Develop merge master

### PR DESCRIPTION
**Pull request by Shnoulle**
Still have issue with gulp : can you gulpify please ?

Or merge master in develop

### CODE REVIEW

**Comment by Shnoulle** [comment]
@olleharstedt , @lacrioque no body to merge master in develop or fixing the gulp part ? I can merge , but with an outdated adminscript/build (leave current one, don't update with last fix).

**Comment by Shnoulle** [comment]
It's more because you ask me to merge master in develop yesterday …

**Comment by olleharstedt** [comment]
Yes, but I didn't know you had a problem with gulp or whatever.

**Comment by Shnoulle** [comment]
@olleharstedt or @lacrioque or @c-schmitz 

My result of gulp : 

```
[shnoulle@poledra adminbasics]$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #5: Expected object but got string
npm ERR! typeerror     at inflatableChild (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:93:3)
npm ERR! typeerror     at BB.each (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
npm ERR! typeerror     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR! typeerror     at Object.gotValue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
npm ERR! typeerror     at Object.gotAccum (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
npm ERR! typeerror     at Object.tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR! typeerror     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm ERR! typeerror     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm ERR! typeerror     at Promise._settlePromiseCtx (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
npm ERR! typeerror     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm ERR! typeerror     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm ERR! typeerror     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm ERR! typeerror     at runCallback (timers.js:705:18)
npm ERR! typeerror     at tryOnImmediate (timers.js:676:5)
npm ERR! typeerror     at processImmediate (timers.js:658:5)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shnoulle/.npm/_logs/2019-02-05T10_48_49_462Z-debug.log
[shnoulle@poledra adminbasics]$ rm -f package-lock.json && npm install
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint-plugin-import@>=2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint-plugin-node@>=4.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN adminbasics No description
npm WARN adminbasics No repository field.
npm WARN adminbasics No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 311 packages from 216 contributors and audited 11210 packages in 14.741s
found 5 vulnerabilities (1 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
[shnoulle@poledra adminbasics]$ gulp default
[11:50:43] Using gulpfile /mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/gulpfile.js
[11:50:43] Starting 'default'...
[11:50:43] Starting 'compile:production'...
[11:50:43] Starting 'sass:production'...
[11:50:43] Starting 'webpack:production'...
000-lime-admin-common-rtl.css: 60349
000-lime-admin-common-rtl.css: 58766
main.css: 1826
main.css: 1479
main.css: 1826
main.css: 1479
000-lime-admin-common.css: 76793
000-lime-admin-common.css: 60515
001-jcarousel.responsive-rtl.css: 1758
001-jcarousel.responsive-rtl.css: 1740
001-jcarousel.responsive.css: 2326
001-jcarousel.responsive.css: 1739
002-attributeMap-rtl.css: 27
002-attributeMap-rtl.css: 26
002-attributeMap.css: 36
002-attributeMap.css: 26
003-attributeMapToken-rtl.css: 1393
003-attributeMapToken-rtl.css: 1342
003-attributeMapToken.css: 1681
003-attributeMapToken.css: 1340
004-displayParticipants-rtl.css: 704
004-displayParticipants-rtl.css: 680
004-displayParticipants.css: 807
004-displayParticipants.css: 687
100-adminstyle-rtl.css: 101149
100-adminstyle-rtl.css: 77189
100-bootstrap-switch.min-rtl.css: 5312
100-bootstrap-switch.min-rtl.css: 5238
100-jquery-ui-rtl.css: 28791
100-jquery-ui-rtl.css: 28304
[11:50:45] Finished 'sass:production' after 1.56 s
[11:50:45] Version: webpack 3.12.0
             Asset     Size  Chunks                    Chunk Names
    adminbasics.js   885 kB       0  [emitted]  [big]  main
adminbasics.js.map  1.14 MB       0  [emitted]         main
[11:50:45] Finished 'webpack:production' after 2.27 s
[11:50:45] Starting 'compress'...
[BABEL] Note: The code generator has deoptimised the styling of "/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/build/adminbasics.js" as it exceeds the max of "500KB".
[11:50:53] Finished 'compress' after 7.2 s
[11:50:53] Starting 'compresslibs'...
[11:50:53] Finished 'compresslibs' after 3.31 ms
[11:50:53] Finished 'compile:production' after 9.48 s
[11:50:53] Starting 'sass'...
[11:50:53] Starting 'webpack'...
[11:50:53] Starting 'babelify'...
[11:50:53] Finished 'sass' after 280 ms
[11:50:53] Version: webpack 3.12.0
             Asset     Size  Chunks                    Chunk Names
    adminbasics.js   885 kB       0  [emitted]  [big]  main
adminbasics.js.map  1.14 MB       0  [emitted]         main
[11:50:54] 'babelify' errored after 1.19 s
[11:50:54] SyntaxError in plugin "gulp-babel"
Message:
    /mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/build/adminbasics.js: Unexpected token (26536:30)
[11:50:54] 'default' errored after 11 s
[11:50:54] SyntaxError in plugin "run-sequence(babelify)"
Message:
    /mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/build/adminbasics.js: Unexpected token (26536:30)
Details:
    pos: 819195
    loc: [object Object]
    _babel: true
    codeFrame:   26534 |         // If enqueue has been called before, then we want to wait until
  26535 |         // all previous Promises have been resolved before calling invoke,
> 26536 |         // so that results are
        |                               ^
    fileName: /mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/build/adminbasics.js

Stack:
SyntaxError: /mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/build/adminbasics.js: Unexpected token (26536:30)
  26534 |         // If enqueue has been called before, then we want to wait until
  26535 |         // all previous Promises have been resolved before calling invoke,
> 26536 |         // so that results are
        |                               ^
    at Parser.pp$5.raise (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseMaybeAssign (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:3367:23)
    at Parser.pp$3.parseExpression (/mnt/data/shnoulle/nginx/www/develop/assets/packages/adminbasics/node_modules/babylon/lib/index.js:3306:19)
[11:50:54] Finished 'webpack' after 1.22 s

```

Here, it's the build from master not updated. But if you can review the gulp part … all other are merged (maybe with error but controlled)

**Comment by Shnoulle** [comment]
```
$ npm list babel-core
/mnt/data/shnoulle/nginx/www/master/assets/packages/adminbasics
├─┬ babel-core@6.26.3 
│ └─┬ babel-register@6.26.0
│   └── babel-core@6.26.3  deduped
└─┬ gulp-babel@6.1.3
  └── babel-core@6.26.3  deduped

```

**Pull request merged**
