### PR TITLE
New feature: Remote API, new User, UserGroup and Permissions handling…

### PR DESCRIPTION
**Pull request by gabrieljenik**
… routines

Added routines for managing Users, Permissions and UserGroups.
Source code was ported from the core controllers.

### CODE REVIEW

**Comment by c-schmitz** [comment]
The patch is duplicating code from core. Instead the original code should be properly refactored so it can be used both by core and API without the necessity to be duplicated.

**Comment by gabrieljenik** [comment]
I agree with you.
Core functions should call API methods.
Or there should be a central lib.

But aren't all other API methods duplicating code already?

**Comment by c-schmitz** [comment]
The never ones shouldn't - the old ones porbably do.

**Comment by gabrieljenik** [comment]
hmm don't agree that much with that approach... I mean, it is avoiding having new features while following the same pattern of all other API methods...

But is fine, I will see what I can do...

Thanks!

**Comment by Shnoulle** [comment]
Core LimeSurvey controllers + API must call model function , no ?

**Comment by gabrieljenik** [comment]
HI Shnoulle,

I agree, bouth should call the model... but what about validations (I would call them business validations)... they should be inside the model, inside a central lib or duplicated in both the API and the Controller?

If I recall correctly, I am using models, but some validations are outside the model.

As per the pluginevent, I saw it... pretty nice.. Are you suggesting to put this in there?

**Comment by c-schmitz** [comment]
Yes, model function please.

**Comment by Shnoulle** [comment]
@gabrieljenik : no, not here ... i make a pull request, but you seems to use a lot RemoteCOntrol and fix a lot of issue. Then you can be our Lead Dev on the RemoteControl system ? ANd help me to move it to a core plugin too maybe.

**Comment by gabrieljenik** [comment]
@Shnoulle: Thanks! It will be great to get that "title". But the issue is that I am not sure I will have the time, at least on the first half of 2016, to take care of that position. I will try to move your development to core...

**Comment by maziminke** [comment]
@c-schmitz , I need these feature for an upcoming project soon. Is there any chance we can merge it into 2.5x? These are only new functions so there should be no side effects or the like.

**Comment by c-schmitz** [comment]
I don't see this patch being accepted anytime soon if the mentioned problems are not fixed first.

**Pull request closed without merging**
