### PR TITLE
Fixed issue #12387: Unecessary rendering of .answer-container element…

### PR DESCRIPTION
**Pull request by TonisOrmisson**
https://bugs.limesurvey.org/view.php?id=12387

… in text-display questions

### CODE REVIEW

**Comment by tpartner** [comment]
Please see my note in the bug report - https://bugs.limesurvey.org/view.php?id=12387

**Comment by Shnoulle** [comment]
Please : wait for https://bugs.limesurvey.org/view.php?id=12360 to be fixed before testing HTML part.

And here : maybe better in CSS ? `.boilerplate .answer-container {display:none}` ?

**Comment by tpartner** [comment]
As I said in my comment in the bug - is there no way to prevent rendering server-side?

**Comment by TonisOrmisson** [comment]
I was also looking for a place to avoid rendering at first bu looking at the twig:
https://github.com/LimeSurvey/LimeSurvey/blob/develop/templates/default/views/subviews/survey/question.twig#L79
It seemed more logical to just hide it. 
I do not think there will be a twig layout per question type (or?)

About JS vs CSS. 
I put it there because it kind of was a logic place where also some other hiding occurs triggered from 
https://github.com/LimeSurvey/LimeSurvey/blob/develop/templates/default/views/layout_main.twig#L145

Why would you rather have CSS? My argument for JS is that we already have a JS function for  this type of purpose - and I like to have things in logical places (rather than maybe the best in terms of performance).

**Comment by tpartner** [comment]
As Denis knows, I am a JS fan but my argument for CSS is: 

Any time it can be done with pure CSS, it is preferable because the JS isn't fired until full page load so there may be a brief flash of the visible element before the class is applied. Also, arguably, the JS adds an unnecessary load.

**Comment by Shnoulle** [comment]
Currently : there are 2 part
- `{{ aQuestion.answer | raw }}` : is not empty : I didn't know if remove the hidden input can be done without broking EM. Can make a test BUT : i think too all this hidden input must be added by EM and not by view
- Hiding unneeded answers part : it's hiding in all condition, even with no-js : use css

But the major question (my Point Of View) : it's a template issue or a core issue ?

**Comment by TonisOrmisson** [comment]
@Shnoulle Im not sure I understood you fully :)

Anyway I changed it to use CSS instead of JS as you suggested. Thanks!

**Comment by Shnoulle** [comment]
@TonisOrmisson normal, i don't understand me too (always) ;). Let me try to explain (about 2 only).

The question is more : did we must hide this part 

1. [for all template](https://github.com/LimeSurvey/LimeSurvey/tree/develop/assets/packages/limesurvey)
2. [for all default based template](https://github.com/LimeSurvey/LimeSurvey/tree/develop/assets/packages/template-default) 
3. Only for default template, and easily updatable by user (like you do it)

Currently : we can not do 1 (`answer-container` come from template) . But maybe it best in 2.

:)

**Comment by TonisOrmisson** [comment]
Thanks - it has got much clearer now!
I agree about 2. I'll change that.

**Comment by Shnoulle** [comment]
Hey, it's for discussion, not decision : @tpartner : all default based or only template ? Did you see a reason where a user can show it (some js workaround ;) )

**Comment by tpartner** [comment]
@Shnoulle, no, I don't see a need for it in any JS workarounds I can think of. I suppose, if that were the case, you could insert the required element(s) with the workaround.

**Pull request merged**
