### PR TITLE
Fixed issue #17512: Survey Logic File Syntax Error Summary Displays Incorrect Error Count

### PR DESCRIPTION
**Pull request by gabrieljenik**
Basically what LimeExpressionManager :: ShowSurveyLogicFile () does is process each string and check for errors. That is, for each "field" to validate, execute $ LEM-> ProcessString (...), and then check $ LEM-> em-> HasErrors ().

The problem is that each expression contained in the chain is processed by RDP_Evaluate (), and one of the first things it does is reset the errors.

So if a string has more than one expression, and the last expression has no errors, $ LEM-> em-> HasErrors () returns false.

So HasErrors () reports only about the last execution of RDP_Evaluate (), it does not report about the entire process of ProcessString ().

On this fix we added the possibility (optional) of not reseting the errors.
That is, allow HasErrors() to report about the whole ProcessString() process.

An alternative is to create a separate flag for checking errors in the whole string.
Still, I believe that would more intrusive, involve more changes and also would be more error prone.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Need to reset warning too ?

See dedicated function : https://github.com/LimeSurvey/LimeSurvey/commit/b43c81d737f2f341bb68cb612b305b70c08e5a23#

**Comment by gabrieljenik** [comment]
> Need to reset warning too ?
> 
> See dedicated function : [b43c81d](https://github.com/LimeSurvey/LimeSurvey/commit/b43c81d737f2f341bb68cb612b305b70c08e5a23)

Do you mean here reset warning here as well?
https://github.com/LimeSurvey/LimeSurvey/pull/2030/files#diff-a974f1aca3b64170e04f9ac415aadb10d9108696f0ae4ce07caee89d8a1447d3R538

**Comment by Shnoulle** [comment]
Yes : in same condition :  if question have  

{Q0 = "A1"} for question  text and {if(Q1 == "A3", "a sentence")} : question must show 'this question have a warning" and top must show "A question have a warning"

**Comment by Shnoulle** [comment]
> Yes : in same condition : if question have
> 
> {Q0 = "A1"} for question text and {if(Q1 == "A3", "a sentence")} : question must show 'this question have a warning" and top must show "A question have a warning"

Must be checked , but it take time to check and report.

**Comment by gabrieljenik** [comment]
What about now?

**Review by thedirtypanda — APPROVED** [review]

**Pull request merged**
