### PR TITLE
Fixed issue #17527: Validate before using updateAll

### PR DESCRIPTION
**Pull request by gabrieljenik**
Reviewed updateAll() invocations. Added xss filtering.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Why not extend directly https://github.com/LimeSurvey/LimeSurvey/blob/2fd0581a95445cc2f5334a07be8be52f5f964a31/framework/db/ar/CActiveRecord.php#L1768 ?
for some specific model ?

**Comment by gabrieljenik** [comment]
> Why not extend directly
> 
> https://github.com/LimeSurvey/LimeSurvey/blob/2fd0581a95445cc2f5334a07be8be52f5f964a31/framework/db/ar/CActiveRecord.php#L1768
> 
> ?
> for some specific model ?

What if we override updateAll for all model.
If the model has a static attribute xssFilterAttributes, then it is used for knowing which attributes should be filtered.

**Comment by Shnoulle** [comment]
> > Why not extend directly
> > https://github.com/LimeSurvey/LimeSurvey/blob/2fd0581a95445cc2f5334a07be8be52f5f964a31/framework/db/ar/CActiveRecord.php#L1768
> > 
> > ?
> > for some specific model ?
> 
> What if we override updateAll for all models.
> If the model has a static attribute xssFilterAttributes, then it is used for knowing which attributes should be filtered.

With one model : less chance to break different things,, but yes it's a good idea.

Start by one or two model, when it work good : update https://github.com/LimeSurvey/LimeSurvey/blob/master/application/models/LSActiveRecord.php

**Comment by gabrieljenik** [comment]
OK, following last conversation, I have applied a more general approach.
- Overloaded updateAll()
- Added xssFilterAttributes atribut on LSActiveRecord
- That attirbute is used by updateAll() to know which values should be xssFiltered.

What do you think?

**Comment by Shnoulle** [comment]
Personally : i like it.

I totally understand we can not read rules currently.

**Comment by Shnoulle** [comment]
@glimz this one is merged no ?

See https://bugs.limesurvey.org/view.php?id=17699 issue

**Review by Shnoulle — COMMENTED** [review]
https://bugs.limesurvey.org/view.php?id=17699

**Comment by olleharstedt** [comment]
Revert needed? Either that or a fix on Monday.

**Comment by Shnoulle** [comment]
See for reverting, but in my opinion : yes

See master not merged : https://github.com/LimeSurvey/LimeSurvey/pull/2086

**Pull request merged**
