### PR TITLE
Fixed issue #19112: Store XSS at Label sets list

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: escape value … always escape value in text input …

### CODE REVIEW

**Review by gabrieljenik — APPROVED** [review]
Looks Ok. I guess HTML is not needed on `title` field.

**Comment by Shnoulle** [comment]
> Looks Ok. I guess HTML is not needed on `title` field.

? What do you mean ? It's an input

**Comment by gabrieljenik** [comment]
> > Looks Ok. I guess HTML is not needed on `title` field.
> 
> ? What do you mean ? It's an input

I mean this input is not supposed to allow html, right?

**Comment by Shnoulle** [comment]
> > > Looks Ok. I guess HTML is not needed on `title` field.
> > 
> > 
> > ? What do you mean ? It's an input
> 
> I mean this input is not supposed to allow html, right?

Why ? See answers for example, or subquestions.

And here : label value can be used for answers or subquestions : then need to allow HTML …

**Comment by gabrieljenik** [comment]
> > > > Looks Ok. I guess HTML is not needed on `title` field.
> > > 
> > > 
> > > ? What do you mean ? It's an input
> > 
> > 
> > I mean this input is not supposed to allow html, right?
> 
> Why ? it's answers for example, or subquestions.

If this are supposed to allow HTML, then:
1. Enter: `Me & You`
2. Will be saved as `Me &amp; You`
3. After refresh the input will have the value `Me &amp;amp; You`

Am I Right?

**Comment by Shnoulle** [comment]
> Am I Right?

No …  it's principle of escaping … we always encode value … **always** … 

Peek 02-10-2023 16-14

**Review by gabrieljenik — APPROVED** [review]

**Pull request merged**
