### PR TITLE
Fixed issue #16460: Unable to update format or questionindex by plugin

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #16460 : Unable to update format or questionindex by plugin
Dev : all attributes allowed

### CODE REVIEW

**Comment by maziminke** [comment]
@olleharstedt This is a very useful adjustment, can we merge?

@Shnoulle Is there some sample code available on how one could change the survey format by a plugin?

**Comment by olleharstedt** [comment]
QA should happen before test, buuut not easy here. Manual update? LS4 PR?

**Comment by Shnoulle** [comment]
@maziminke : i just test quickly to set all index to full on one of my existing plugin …

Idea : create a plugin to set index to full when user is admin ?

**Comment by Shnoulle** [comment]
`$this->getEvent()->set('format','A');`

**Comment by maziminke** [comment]
@cdorin93 @olleharstedt We have tested this adjustment by coding a plugin which allows changing the survey format by URL.
Everything worked as expected.
Can we please merge this ASAP?

**Comment by Shnoulle** [comment]
We NEED a better solution for merge process … some needed part wait for month …

**Pull request merged**
