### PR TITLE
[WIP] Dev: quick test of CI with debug and assets

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: Just quick test currently

### CODE REVIEW

**Comment by olleharstedt** [comment]
I saw that the emcache is always disabled when debug is on. Might break.

**Comment by olleharstedt** [comment]
Yeah, if you check the raw Travis log, you can see "emcache is not set".

**Comment by Shnoulle** [comment]
No time to check it currently, just want to see what happen quickly ;)

**Comment by olleharstedt** [comment]
So we can close, or...?

**Comment by Shnoulle** [comment]
[WIP] + draft is OK ?

Else : close it ;)

**Comment by olleharstedt** [comment]
Yep, draft is OK.

**Comment by Shnoulle** [comment]
Maybe try with 

1. `define('YII_DEBUG', true);`
2. `error_reporting(E_ALL);`
3. `App()->setConfig('debug', false);`

Do you think it can be interesting ?

**Comment by olleharstedt** [comment]
I'd go for nr 2 first.

**Pull request closed without merging**
