### PR TITLE
beforeQuestionRender Class + attributes

### PR DESCRIPTION
**Pull request by Shnoulle**
- this one seems really needed … adding a class by plugin is needed
- but can not remove included function in old twig file

### CODE REVIEW

**Comment by olleharstedt** [comment]
ping @LouisGac

**Comment by olleharstedt** [comment]
Div id works even when no plugin is running the event?

**Comment by Shnoulle** [comment]
Yes, event happen then this line : https://github.com/LimeSurvey/LimeSurvey/pull/1022/files#diff-b69c0b8c301d9dce52f005d2664f3dfbR1690
Force `id=>'questionQid'`

Same behaviour then 2.74

**Comment by Shnoulle** [comment]
It's all done for me.

**Comment by Shnoulle** [comment]
thanks :)

**Pull request merged**
