### PR TITLE
Fixed issue #12440: Propertie TemplateConfiguration.name undefined

### PR DESCRIPTION
**Pull request by TonisOrmisson**
https://bugs.limesurvey.org/view.php?id=12434

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
I'm validating through models...
There is some more of this there

**Comment by Shnoulle** [comment]
About the redirect : i think Throw a 404 is better : HTTP error code are done for this.

**Comment by TonisOrmisson** [comment]
@Shnoulle You're probably right

**Comment by Shnoulle** [comment]
Are you sure you fix home page ? No error => survey listing only

**Pull request merged**
