### PR TITLE
[WIP][DONTMERGE] Dev: 400 update step by step

### PR DESCRIPTION
**Pull request by Shnoulle**
For discussion.

Alternate way : 390 + 391 + 392  ?

Current **major** issue : if it broke during 400 upgrade and show a solution (and user have DB access) : there are no way to launch again the upgrade process

### CODE REVIEW

**Comment by Shnoulle** [comment]
@maziminke maybe you have broken DB ? Then we can test if fix the error returned directly inside DB and relauch upgrade process can work.

**Comment by olleharstedt** [comment]
IMO, first step is to move all `dropTable` to the end of the update.

**Comment by Shnoulle** [comment]
> IMO, first step is to move all dropTable to the end of the update.

More work for user :  right ?

**Comment by olleharstedt** [comment]
> More work for user : right ?

If it fails? Yes, the restore procedure would be manual.

**Comment by olleharstedt** [comment]
But less testing for us (me).

**Comment by Shnoulle** [comment]
1st step : have some broken DB (with mariadb or pg)

**Comment by olleharstedt** [comment]
> 1st step : have some broken DB (with mariadb or pg)

Easy, just manipulate the collation before upgrading to LS4.

**Comment by Shnoulle** [comment]
Maybe but must have too different errors. I see some pk in Label (really don't understand how this can happen ....)

**Comment by explorerdk** [comment]
I have the same issue, I had to rollback to backup copy of Site / DB, if helpful i will supply a copy of Database for debugging....   the same error posted on Mantis Bug report is what it does to me also.  Tried changing collation, but that did not help with the 1st error.  

My Survey DB is not to big either.,.  

/Explorerdk

**Comment by olleharstedt** [comment]
@explorerdk You should write something on Mantis so that we know more people are affected. Thank you.

**Comment by maziminke** [comment]
Currently I can't share a broken DB due to privacy issues, sorry.

**Comment by explorerdk** [comment]
> Currently I can't share a broken DB due to privacy issues, sorry.

@maziminke  I have mine Anonymized, so I was proposing to share my small Survey db  :)

**Comment by Shnoulle** [comment]
@olleharstedt 

> IMO, first step is to move all dropTable to the end of the update.

What i can do is : 

1. remove the step by step
2. move the drip table at end
3. Keep the checking of XX_400 existence before working on XX and use the _400 one by rename ? (for example question_400 exist ; delete question + questioni10n, rename question_400 to question and try again)

**Pull request closed without merging**
