### PR TITLE
Fixed issue #18026: Session expire message when submit button is clicked twice

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by c-schmitz** [comment]
Why are there translation files in this PR? That does not look right.

**Comment by gabrieljenik** [comment]
My bad. The PR was for master. I based it on dev. Will review it on Monday.

**Comment by Shnoulle** [comment]
> // We only care about the final submit, not normal forward/backward navigation.

Why ?

**Comment by gabrieljenik** [comment]
> [c-schmitz](https://github.com/c-schmitz) changed the base branch from develop to master

@c-schmitz Although this reported as a bug, should we push it to dev because of the kind of update? Seems like could be better on the dev branch, where more people will use it before going live.

**Comment by gabrieljenik** [comment]
> > // We only care about the final submit, not normal forward/backward navigation.
> 
> Why ?

The bug only appears on the final submit button. Ddin't want to be more intruisve.

**Comment by Shnoulle** [comment]
> > > // We only care about the final submit, not normal forward/backward navigation.
> > 
> > 
> > Why ?
> 
> The bug only appears on the final submit button. Ddin't want to be more intruisve.

Yes : but send X times same request is bad for SQL too ?
No ?

**Comment by c-schmitz** [comment]
I was wondering if we should show some kind of waiting indicator on the button after it was clicked.

**Comment by Shnoulle** [comment]
> I was wondering if we should show some kind of waiting indicator on the button after it was clicked.

https://demo.sondages.pro/282267

https://gitlab.com/SondagesPro/SurveyThemes/skelvanilla/-/blob/master/scripts/skelvanilla.js#L131

**Comment by glimz** [comment]
Waiting indicator seems like a better improvement. I will test after it is implemented @gabrieljenik

**Comment by gabrieljenik** [comment]
> I was wondering if we should show some kind of waiting indicator on the button after it was clicked.

You mean a loader full screen overlay (like Dennis suggested) or just some waiting indicator on the button characters?
I think loader overlay would be better.

Thoughts?

**Comment by gabrieljenik** [comment]
Ticket #18074 was appended on this PR

**Comment by Shnoulle** [comment]
> Waiting indicator seems like a better improvement. I will test after it is implemented @gabrieljenik

In my opinion : it must be related to survey theme only (inside vanilla/script) , and seems unrelated to the issue. 

Please : don't add theme related part in global js/css

**Comment by gabrieljenik** [comment]
> In my opinion : it must be related to survey theme only (inside vanilla/script) , and seems unrelated to the issue.
> 
> Please : don't add theme related part in global js/css

After reviewing, I agree. Maybe we should follow up on a new ticket?
What's wrong on merging as it is now? It will not hurt.

Please conider LTS is already merged

**Comment by Shnoulle** [comment]
> > In my opinion : it must be related to survey theme only (inside vanilla/script) , and seems unrelated to the issue.
> > Please : don't add theme related part in global js/css

can be added in vanillla ? Must follow to child ?

> 
> After reviewing, I agree. Maybe we should follow up on a new ticket? What's wrong on merging as it is now? It will not hurt.

It hurt : https://github.com/LimeSurvey/LimeSurvey/commit/8082779b1dad128da066248be21bc7e2221a6e79 it broke all other menu actions.

> 
> Please conider LTS is already merged

Seems test is not done totally on 3.X

**Comment by gabrieljenik** [comment]
> > In my opinion : it must be related to survey theme only (inside vanilla/script) , and seems unrelated to the issue.
> > Please : don't add theme related part in global js/css
> 
> can be added in vanillla ? Must follow to child ?

We can try.
> 
> > After reviewing, I agree. Maybe we should follow up on a new ticket? What's wrong on merging as it is now? It will not hurt.
> 
> It hurt : [8082779](https://github.com/LimeSurvey/LimeSurvey/commit/8082779b1dad128da066248be21bc7e2221a6e79) it broke all other menu actions.

That's already solved on another ticket for LTS. 
That solution is also merged here.
By "hurt" I mean I don't see much benefits on waiting to have the indicator to merge this.
After testing, this can be merged, independently from the indicator.

> > Please conider LTS is already merged
> 
> Seems test is not done totally on 3.X

Not sure I follow.

**Comment by Shnoulle** [comment]
> > > Please conider LTS is already merged
> > 
> > 
> > Seems test is not done totally on 3.X
> 
> Not sure I follow.

It was merged without testing top links in LTS :) ,all top links are broken.

**Comment by gabrieljenik** [comment]
> > > > Please conider LTS is already merged
> > > 
> > > 
> > > Seems test is not done totally on 3.X
> > 
> > 
> > Not sure I follow.
> 
> It was merged without testing top links in LTS :) ,all top links are broken.

And how that relates to building the waiting indicator on a new story?

**Comment by gabrieljenik** [comment]
Created new ticket for the waiting indicator
https://bugs.limesurvey.org/view.php?id=18166

**Pull request merged**
