### PR TITLE
Correct off-by-one in slicing.

### PR DESCRIPTION
**Pull request by jmantysalo**
Fixed issue #16292: One language missing in question editing

### CODE REVIEW

**Comment by olleharstedt** [comment]
This also needs to be built, right?

**Comment by jmantysalo** [comment]
> This also needs to be built, right?

Yes... But the only warning the system gives is scrutinizer missing some package on automatic test machine.

**Comment by olleharstedt** [comment]
> > This also needs to be built, right?
> 
> Yes... But the only warning the system gives is scrutinizer missing some package on automatic test machine.

If the package hasn't been built, the change is not applied yet. Maybe you should join our weekly team meeting if you want to contribute more regularly? We can give you more feedback then. It's every Tuesday, 14:30 CET. Go to #limesurvey on Freenode and we'll give you access.

**Comment by jmantysalo** [comment]
> If the package hasn't been built, the change is not applied yet. Maybe you should join our weekly team meeting if you want to contribute more regularly? We can give you more feedback then. It's every Tuesday, 14:30 CET. Go to #limesurvey on Freenode and we'll give you access.

Maybe later. The timeslot itself should be OK, I'm at UTC+2 and have no regular meeting on 15:30 local time. I'll see if I will do more for Lime in the near future -- not sure about that.

**Comment by Shnoulle** [comment]
> Yes... But the only warning the system gives is scrutinizer missing some package on automatic test machine.

I already report build issue on mantis , select development for this :)

**Comment by olleharstedt** [comment]
Fixed?

**Comment by jmantysalo** [comment]
Nope. I had to revert my repo to get a working pull request.

**Comment by olleharstedt** [comment]
OK.

**Pull request closed without merging**
