### PR TITLE
 Fixed issue #18639: Token browse can be unusable with lot of data

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #18639: Token browse can be unusable with lot of data in attribute
Dev: wrap value inside in cell (and encode)
Dev: ellipsed bigger value
Dec: set a min-width and a max-width with a container for all value

### CODE REVIEW

**Comment by Shnoulle** [comment]
@gabrieljenik there are some more fix related to usability set only with css : min-width+max-width for long text question

**Review by gabrieljenik — APPROVED** [review]

**Comment by gabrieljenik** [comment]
> @gabrieljenik there are some more fix related to usability set only with css : min-width+max-width for long text question

Not sure what you mean. Sorry

**Comment by Shnoulle** [comment]
> > @gabrieljenik there are some more fix related to usability set only with css : min-width+max-width for long text question
> 
> Not sure what you mean. Sorry

Difference with the previous version you review :)

**Comment by Shnoulle** [comment]
Too complex to fix conflict redo the PR …

**Pull request closed without merging**
