### PR TITLE
Fixed issue #18585: Click again on link by email submit again the survey

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #18585: Click again on link by email submit again the survey
Dev: reset session in all condition, reload page or click on link : start again.

### CODE REVIEW

**Comment by Shnoulle** [comment]
@gabrieljenik same than https://github.com/LimeSurvey/LimeSurvey/pull/2851 but for 3.X

**Review by gabrieljenik — APPROVED** [review]
Code looks OK. Haven't tested it. Seems there are quite some tests related, right?

**Comment by Shnoulle** [comment]
> Code looks OK. Haven't tested it. Seems there are quite some tests related, right?

Oh no, got it :)

In my opinion : 

1. the fix didn't update anything if `survey->alloweditaftercompletion != 'Y'` and `survey->tokenanswerspersistence  != 'Y'`
2. the fix happen only after survey is submitted

Then must check only survey submitted in same browser with

- anonymous survey without print available (This must not change anything)
- anonymous survey with print available : this is the issue
- token survey  without print available (This must not change anything)
- token survey  with print available : this is the issue

Remind : use email, if i just reload on same windows : sometime it work sometime not …

**Comment by gabrieljenik** [comment]
> 1. the fix didn't update anything if `survey->alloweditaftercompletion != 'Y'` and `survey->tokenanswerspersistence  != 'Y'`

https://github.com/LimeSurvey/LimeSurvey/pull/2850/files#diff-0a325a27a46ff4dd16f4f9ba11cdbe12960e8572061a2574c49cfe4118cd6908L205

If the two settings were active at the same time, right, it will not enter the IF.
Still, if only one of those was activated, it was entering.

That's why I see many testing scenarios.
If you lis the scenarios on the issue, I can help testing.

**Comment by Shnoulle** [comment]
No :)

`($thissurvey['alloweditaftercompletion'] != 'Y' || $thissurvey['tokenanswerspersistence'] != 'Y')` == `!($thissurvey['alloweditaftercompletion'] == 'Y' && $thissurvey['tokenanswerspersistence'] == 'Y')`

The only change was for survey with both to Y

**Comment by gabrieljenik** [comment]
You are right!

**Comment by Shnoulle** [comment]
Yep …
https://github.com/LimeSurvey/LimeSurvey/pull/2850/commits/3a4e1301fe478bae71b6741ac8517d12c5ea0ded

**Pull request closed without merging**
