### PR TITLE
Dev: README about PHP version

### PR DESCRIPTION
**Pull request by Shnoulle**

### CODE REVIEW

**Comment by Shnoulle** [comment]
Dev: See https://manual.limesurvey.org/Installation_-_LimeSurvey_CE#Make_sure_you_can_use_LimeSurvey_on_your_website

Still unsure for all other part  :/ In README : mysql version is greater than manual … for example.

**Comment by olleharstedt** [comment]
Thanks!

**Comment by Shnoulle** [comment]
It's not 7.2 now ?

**Comment by Shnoulle** [comment]
7.1 : https://travis-ci.org/github/LimeSurvey/LimeSurvey/builds/769678447

**Comment by olleharstedt** [comment]
> It's not 7.2 now ?

It will be in next dev release. 7.2 - 8+

**Pull request merged**
