### PR TITLE
New Feature #17301: Allow whitelisting IPs to not be locked out

### PR DESCRIPTION
**Pull request by gabrieljenik**
- Added whitelist ip as a global security settings
- Throw InvalidArgumentException if invalid attempt type is specified on isWhitelisted()

### CODE REVIEW

**Review by c-schmitz — CHANGES_REQUESTED** [review]
I don't think it is a good idea to use wildcard notation for IP addresses.
As you can see you need to introduce your own validation function.

Also your approach does not seem to handle IPv6.

It would be better to allow/use CIDR notation (https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) on top of normal IP addresses, see https://gist.github.com/pavinjosdev/cb1d636ea9dc2bd201d54107d10650c5 for a working function that also handles IPv6 (you might need to adjust that function a bit to also allow for single IP addresses)

In global settings when I enter an invalid IP address there is no error. It just vanishes on saving. It should show a proper error after saving.

**Comment by gabrieljenik** [comment]
> I enter an invalid IP a

As per discussed with @c-schmitz:
- On this story we will allow single IPv4 addresses, no wildcards, no CIDR
- On a new story to be created we will allow CIDR and wildcards.

Will review the other changes requested and implement them

Thanks!

**Review by c-schmitz — CHANGES_REQUESTED** [review]
validateIpAddresses is still not capable checking IPv6.
Also you should not roll your own solution but use filter_var instead.

**Comment by gabrieljenik** [comment]
> validateIpAddresses is still not capable checking IPv6.
> Also you should not roll your own solution but use filter_var instead.

OK, will ammend. Thanks!

**Review by c-schmitz — APPROVED** [review]

**Comment by c-schmitz** [comment]
Please do not forget to update the manual, too.

**Comment by gabrieljenik** [comment]
> Please do not forget to update the manual, too.

Done: https://manual.limesurvey.org/Global_settings#Security

**Pull request merged**
