### PR TITLE
Feature/custom box widget content

### PR DESCRIPTION
**Pull request by KRav007**
The offers the possibility to add a custom class to the box feature to fire a custom widget/View.

Where do I have to put the table migration?

### CODE REVIEW

**Comment by LouisGac** [comment]
I love it!
could you please redo a PR but after you pulled and solved the conflicts?

**Comment by KRav007** [comment]
conflict solved

**Comment by KRav007** [comment]
don't merge it I will test it first with a custom class

**Comment by Shnoulle** [comment]
Just to know, currently : where is used PanelBoxWidget ? It's the 6 box on home page ?

**Comment by KRav007** [comment]
Yes, it is.

**Comment by c-schmitz** [comment]
@KRav007 What's the status? If you still want us to merge it can you please resolve the conflicts? Thank you.

**Comment by c-schmitz** [comment]
Patch is abandoned. Closing issue.

**Pull request closed without merging**
