### PR TITLE
Default config for question setting "mandatory"

### PR DESCRIPTION
**Pull request by kw-pr**
@c-schmitz I guess this is also a hack?

I give it a try anyway. Maybe this is not covered by by the survey groups. I used `Yii:app()->getConfig()` here, hope that is a little bit better.

### CODE REVIEW

**Comment by LouisGac** [comment]
please, submit it to dev branch for now.

**Comment by kw-pr** [comment]
@LouisGac ok, thanks. Target branch is changed and one conflict resolved.
I got one error from Travis. Not sure if that is my fault?

**Comment by TonisOrmisson** [comment]
Travis tests are broken currently (after merging master into)

**Comment by c-schmitz** [comment]
This will also be covered with the survey groups feature.

**Pull request closed without merging**
