### PR TITLE
Dev: [WIP] Special characters shown as HTML

### PR DESCRIPTION
**Pull request by Shnoulle**

### CODE REVIEW

**Comment by Shnoulle** [comment]
https://bugs.limesurvey.org/view.php?id=16437

**Comment by Shnoulle** [comment]
@thedirtypanda maybe if you can find some time to help me :) Thank you.

**Comment by thedirtypanda** [comment]
I dont get this PR right now. There is no issue with adminsidepanel package. U can build it in the latest lts branch.
Also if this is not possible, the first step is to delete all node_modules folders and build every package again.

**Comment by Shnoulle** [comment]
>  U can build it in the latest lts branch.

No i can not built …

>  delete all node_modules folders and build every package again

Where is node_modules folders 

This morning : i delete ~/.yarn and `curl -o- -L https://yarnpkg.com/install.sh | bash`

**Comment by thedirtypanda** [comment]
Node_modules folder in assets/packages/adminsidepanel

**Pull request closed without merging**
