### PR TITLE
New plugin event "createStatistics" for pdf statistics

### PR DESCRIPTION
**Pull request by KRav007**
- insert event for statistics pdf creation.This event could also used in future for xls & html
- todo's insert for xls / html if make sense, insert layout features
- rename variable $surveyid to new naming rule

### CODE REVIEW

**Comment by Shnoulle** [comment]
It's more for filename, meta and header, right ?
Actauuly we can use it to do own stat, but need a App->end() ;)

**Comment by KRav007** [comment]
>It's more for filename, meta and header, right ?

Yes that's right. In first step it used it for the header and filename. In future projects you could spread the features to layout of the pdf.

>...but need a App->end()

Sorry, but what you by that? Is something in code missing or wrong?

**Comment by Shnoulle** [comment]
For the App->end : you can do "What you want" in your plugin rendering is not started (and header)

For example : you can replace the PDF stats by the doc stats (or anything you want)

It's right for any plugin event :)

**Comment by LouisGac** [comment]
By the way, in 2.5, statistic is now using views. So it's much more easy to read and modify the rendering.

**Comment by KRav007** [comment]
good to hear - but for my current projects not relevant cause of to much migration time. Next Project ... :-)

**Pull request closed without merging**
