### PR TITLE
Update question.pstpl

### PR DESCRIPTION
**Pull request by BertHankes**
Add a class  question-valid-message to the Question valid message.
This is for styling this specific element.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Template issue only.

Else : please for https://github.com/LimeSurvey/LimeSurvey/tree/answers_html

**Comment by Shnoulle** [comment]
Sorry : but not when working on complet new template + HTML views

**Comment by BertHankes** [comment]
Sorry, Keep up the good work!

**Comment by Shnoulle** [comment]
You xan work on the new default template : in fact i don't want really work on it : i make it "new html" compatible only.

But if you think something can/must be in HTML produced by LimeSurvey (and not in template) : it's the time :).

We break totally the 2.50 template compatibility.

**Pull request closed without merging**
