### PR TITLE
New feature #16779: Keep graph on same statistics PDF page if possible

### PR DESCRIPTION
**Pull request by beat**
This is a New feature proposal to save paper when printing PDF Statistics.

If there is enough room left on the page, put the graph at the bottom of the page.

Otherwise add a new page as before.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Seems to be a good idea :+1:

**Comment by maziminke** [comment]
Great idea!

**Comment by maziminke** [comment]
Great idea!

**Comment by maziminke** [comment]
Great idea!

**Comment by dominikvitt** [comment]
This is a great feature.
Can you close this one and create a new pull request in develop branch?
All new features go there.
As soon as you are finished, I'll review and merge it.

**Comment by cdorin93** [comment]
Updated in #1661

**Pull request closed without merging**
