### PR TITLE
dev: deleted border statement in .ls-answers

### PR DESCRIPTION
**Pull request by tammoterhark**
This will show borders in all tables in the default template.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Could you remove the update of config-sample please :)

**Comment by tammoterhark** [comment]
I wish I could find out how....

**Comment by tammoterhark** [comment]
How could it happen? I did not change that file, it happended during an installation process.

**Comment by Shnoulle** [comment]
Strange ? I don't remind updating it ?

**Comment by Shnoulle** [comment]
@tammoterhark : i send fix for default template in some minute (about save.pstpl + load.pstpl) : please wit some minute :)

**Comment by tammoterhark** [comment]
config-sample was updated with some data of mine during a local installation. I tried to delete this. Has that been successfull?

**Comment by Shnoulle** [comment]
No : no files updated, i do it in next commit

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/commit/cc3775f1d815c2e959077afc67c7d880ab8463af

**Pull request closed without merging**
