### PR TITLE
Dev: Model descriptions. Class & method DOCs.

### PR DESCRIPTION
**Pull request by TonisOrmisson**
If its OK, I'll continue through all models

### CODE REVIEW

**Comment by LouisGac** [comment]
seems good to me

**Comment by TonisOrmisson** [comment]
Note there are some broken things I found. See the //FIXE tags ...

**Comment by TonisOrmisson** [comment]
I'll go through the models a bit more... 
will tell when I finish pushing here

**Comment by TonisOrmisson** [comment]
OK I'm done on this! Please review. 

Probably I'll continue with trying to replace some methods with Yii's generic options to simplify things. And implement usage of relations more. (but this will be another story)

**Comment by c-schmitz** [comment]
Hah! Great work. Thank you!

**Pull request merged**
