### PR TITLE
Fixed issue #18243: ARIA Attribute role on Array question not correct

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #18243: ARIA Attribute role on Array question not correct
Dev: set role to presentation and remove thead and th (needed)
Dev: Css part : update SurveyTheme 
Dev: Fix updateRepeatHeading

### CODE REVIEW

**Comment by Shnoulle** [comment]
Still the EM JavaScript to update

**Comment by olleharstedt** [comment]
We have a LS6 in the making, using Bootstrap 5, so this PR could maybe go there?

**Comment by Shnoulle** [comment]
Maybe … some week ago it was urgent …

**Comment by Shnoulle** [comment]
> We have an LS6 in the making, using Bootstrap 5, so this PR could maybe go there?

Branch to be used ?

**Comment by olleharstedt** [comment]
> Branch to be used ?

We have an "epic" branch we use internally.

**Comment by Shnoulle** [comment]
Capture d’écran du 2022-08-29 10-36-29

I create on Epic/BS ?

**Comment by olleharstedt** [comment]
I think you can wait a little, we have to discuss too, and get feedback from tpartner regarding the changes.

**Comment by Shnoulle** [comment]
Need to check again and remove the colgroup

Else have other idea … but i want to know the best solution.

**Comment by Shnoulle** [comment]
Any decision on this ? Need to work on alternative solution with less HTML update or not ?

**Comment by olleharstedt** [comment]
@ptelu would be the man to ask.

**Comment by Shnoulle** [comment]
> Shouldnt be a problem as long as it works with the current dev branch. Will write a note to check the changes. Did you check if it potentially breaks any frontend queries for javascript?

Yes it's potentially broke any jquery workaround ,near all using array question type in fact. 

The alternate solution : less update : move rile=group on a wrapper https://www.shnoulle.net/test/arrayWCAG/tableau_role-table-2.html

It's ok on the WCAG and OK usage for accessibility, but it seems less easy for real accessibility.

**Comment by Shnoulle** [comment]
@ptelu alternative solution : https://github.com/LimeSurvey/LimeSurvey/pull/2888

1. Move role=group to a div wrapper of the array with aria-labelledby question->question
2. Put the role="columnheader" on the each header (answer text)
3. Give an id to each header ( answer-{SGQA}-{code})
4. Each line stay role="radiogroup" with aria-labelledby subquestion->question (canbe reol group for other array)
5. Put aria-hidden to label used for labelling and shown on phone
6. Set aria-labelledby to each header for each input (aria-labelledby="answer-{SGQA}-{code}")


Lot of work to do it on all other array.
I add some data like oAnswer to twig views, not needed but can be interesting

**Comment by Shnoulle** [comment]
Here there are still the col to remove. I don't want to fix it if it was never merged …

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/2888 is (a lot) more compatible with JS workaround.

**Pull request closed without merging**
