### PR TITLE
Fixed issue #16769: Unable to embed in iframe (using config.php) for Chrome

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: apply patch from Yii1 before Yii 1.1.23
Dev: see https://github.com/yiisoft/yii/pull/4313/files

### CODE REVIEW

**Comment by olleharstedt** [comment]
Can you link to the commit in Yii too, please? So we can compare.

**Comment by Shnoulle** [comment]
There are 2 commits, i put the link to the last pull request in commit comment and in https://github.com/LimeSurvey/LimeSurvey/pull/1629/files#diff-652721134484aa3b5f3d6fe36ddc8db5b02f315e1ea047974e40dec1cc0675fbR246

**Comment by olleharstedt** [comment]
Can I cherry-pick this safely to master?

**Comment by Shnoulle** [comment]
I do it (and check) but yes : sure :)

**Comment by olleharstedt** [comment]
Great, thank you, Denis!

**Comment by Shnoulle** [comment]
Arg : iframe embedded broken in 4.X …
Can not really test if it work …

**Comment by olleharstedt** [comment]
Sad. :(

**Comment by Shnoulle** [comment]
Oh no … i don't applmy fix at good place :) can set samesite to None : fix is OK https://bugs.limesurvey.org/view.php?id=16775

**Pull request merged**
