### PR TITLE
Fix: #13677 Sorting of groups and questions are wrong

### PR DESCRIPTION
**Pull request by mwehr**
Fixed issue #13677 Sorting of groups and questions are wrong

### CODE REVIEW

**Comment by olleharstedt** [comment]
Can you please remove all indentation fixes from this PR?

**Comment by olleharstedt** [comment]
Wait, nevermind. The link says it's already fixed, so I'll close this issue. Thank you!

**Comment by mwehr** [comment]
Hi,

Just want to note that this issue is not fixed as mantis states.

regards
Mario

**Comment by olleharstedt** [comment]
OK, could you please comment on Mantis on how to reproduce? Thank you.

**Comment by mwehr** [comment]
I described the problem in Matis.
The Problem is that in "parseInt(a.group_order || 999999);" a value of "0" is converted to false which returns "999999".
I wonder if I'm the only one which is getting this behaviour.
My survey und survey groups are all starting with "0" index which puts them as the last items in the survey structure menu.

**Comment by olleharstedt** [comment]
OK, so now Mantis says it's fixed again. Can you test and confirm, please?

**Comment by mwehr** [comment]
Hi,

Just tested with latest 3.x-LTS branch.
The Group/Question sorting Bug still exists.
See Screenshot.

order test

**Comment by olleharstedt** [comment]
Cannot reproduce. Please see comments on Mantis.

**Comment by mwehr** [comment]
Hi,

Hmm ok so the question is why your "a.group_order" seems to start with "1" and mine is starting with "0" ?

**Comment by olleharstedt** [comment]
First of all, are you using the /latest/ version of LS3?

**Comment by mwehr** [comment]
Yes I'm using the latest from 3.x-LTS branch
PostgreSQL 12
PHP 7.3.14

**Comment by olleharstedt** [comment]
Ah, I tested on the wrong database. I'll try again.

**Comment by olleharstedt** [comment]
I don't think this fix is sufficient. it doesn't touch the side-panel JS.

**Comment by olleharstedt** [comment]
Made a fix which included your changes. Please pull latest, clear cache and test again. Thank you.

**Comment by mwehr** [comment]
Perfetto, sorting is working now 👍

**Comment by olleharstedt** [comment]
Great, will close this issue then. Thank you for contributing!

**Pull request closed without merging**
