### PR TITLE
Fixed issue #18247: php version 8 and remote control, error in bigdata.php

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]

**Comment by Shnoulle** [comment]
Code seems OK, but need test

**Comment by gabrieljenik** [comment]
@olleharstedt Do you think we should push this to develop to mature and get more testing time?

**Comment by olleharstedt** [comment]
Hmmm, is BigData an external dependency? Carsten has been moving things to composer.json, so that we can finally keep our dependencies up-to-date.

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/blob/49edd10700501807bc08bd7b434f309076992158/application/libraries/BigData.php#L5

If need to set as dependency : need to create a repo ?

**Comment by olleharstedt** [comment]
Ah, by Sam. Yeah, then it's probably not on Packagist. :) (Checked, couldn't find it.)

**Comment by gabrieljenik** [comment]
> Ah, by Sam. Yeah, then it's probably not on Packagist. :) (Checked, couldn't find it.)

So...? not sure where that leaves us

**Comment by olleharstedt** [comment]
If you feel uncertain about the fix, pushing it to dev and wait is not gonna help much, I think. Rather, we need to discuss the different risks, what could break, and how to test it.

**Comment by gabrieljenik** [comment]
> If you feel uncertain about the fix, pushing it to dev and wait is not gonna help much, I think. Rather, we need to discuss the different risks, what could break, and how to test it.

Not uncertain, but as it is hard to test ...

**Comment by olleharstedt** [comment]
Can you write down how it should be tested?

**Comment by Shnoulle** [comment]
When it's used ? :rofl:

**Comment by gabrieljenik** [comment]
Actually, I think that if automated tests on PHP8 went good, I guess everything is OK,
Look at the reproduction steps. Just trying to get session key was triggering the error.

Question is, why haven't that error pop up before as CI runs PHP 8.

Thoughts?

**Comment by olleharstedt** [comment]
> Look at the reproduction steps. Just trying to get session key was triggering the error.

Ah ok!

PHP 8.0 or 8.1?

**Comment by c-schmitz** [comment]
The fix is fine - there is no need to pass by reference here as the value if $result is never manipulated direclty or indirectly in that function.

**Pull request merged**
