### PR TITLE
Fixed issue #18243: ARIA Attribute role on Array question not correct.

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: move to role="presentation" to keep radiogroup on line
Dev: role-radiogroup replace fieldset
Dev: add aria-labelledby for NVDA
Dev: replace some th/thead by class system

### CODE REVIEW

**Comment by Shnoulle** [comment]
https://master.sondages.pro/932473?newtest=Y&lang=en

[Uploading limesurvey_survey_AllTables.lss.txt…]()

**Comment by Shnoulle** [comment]
Out of the office until 21

**Review by gabrieljenik — APPROVED** [review]
Code structure looks OK. Haven't tested

**Comment by Shnoulle** [comment]
@c-schmitz you can «test» ?

**Comment by Shnoulle** [comment]
There still the array by columns where it's complex … near unusable with keyboard and/or screen reader

**Pull request merged**
