### PR TITLE
Fixed issue #16454: Sometimes, question_order is assigned from survey_id

### PR DESCRIPTION
**Pull request by gabrieljenik**
When deleting a question, the order of questions in the group were reassigned by calling updateQuestionOrder, but the survey ID was passed as starting position.

updateQuestionOrder definition was modified to use 1 as default value. Now reordering will follow the same schema as when questions are added, both starting from 1.

we found "database::actionUpdateQuestion()" to be deprecated. 
https://github.com/gabrieljenik/LimeSurvey/blob/1b975c60d3c4128fc72a542b07d3d981bb2eae9c/application/controllers/admin/database.php#L579
Should it be removed?

### CODE REVIEW

**Comment by gabrieljenik** [comment]
I think this instance is missing to review.
https://github.com/gabrieljenik/LimeSurvey/blob/1b975c60d3c4128fc72a542b07d3d981bb2eae9c/application/controllers/admin/database.php#L1518

I will pickup on Monday

**Comment by gabrieljenik** [comment]
> I think this instance is missing to review.
> https://github.com/gabrieljenik/LimeSurvey/blob/1b975c60d3c4128fc72a542b07d3d981bb2eae9c/application/controllers/admin/database.php#L1518
> 
> I will pickup on Monday

Could this be deprecated too?

**Comment by cdorin93** [comment]
@olleharstedt , do you have time to review quickly this one please?

**Comment by olleharstedt** [comment]
Code looks good. Did someone test it?

**Pull request merged**
