### PR TITLE
Fixed issue #17648: Email received by participant is empty

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #18034: Date from token with invalid language show error and date not saved
Dev: LimeMailer already fix language for automatic raw content
Dev: forced raw content (from POST) are not fixed

### CODE REVIEW

**Comment by Shnoulle** [comment]
@olleharstedt same than already checked https://github.com/LimeSurvey/LimeSurvey/pull/2352

**Comment by gabrieljenik** [comment]
Should #2352 be closed?

**Comment by Shnoulle** [comment]
> Should #2352 be closed?

Yes, sorry … 
Doing on LimeSurvey repo for  SonarCloud analysis

**Comment by olleharstedt** [comment]
Looks like sonarcube still fails tho. Hm.

**Comment by Shnoulle** [comment]
> Looks like sonarcube still fails tho. Hm. Well, the important thing is to find someone to test it anyway.

Quality Gate failed

Bug A [0 Bugs](https://sonarcloud.io/project/issues?id=LimeSurvey_LimeSurvey&pullRequest=2691&resolved=false&types=BUG)
Vulnerability A [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=LimeSurvey_LimeSurvey&pullRequest=2691&resolved=false&types=VULNERABILITY)
Security Hotspot A [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=LimeSurvey_LimeSurvey&pullRequest=2691&resolved=false&types=SECURITY_HOTSPOT)
Code Smell A [0 Code Smells](https://sonarcloud.io/project/issues?id=LimeSurvey_LimeSurvey&pullRequest=2691&resolved=false&types=CODE_SMELL)

0.0% [0.0% Coverage](https://sonarcloud.io/component_measures?id=LimeSurvey_LimeSurvey&pullRequest=2691&metric=new_coverage&view=list)
0.0% [0.0% Duplication](https://sonarcloud.io/component_measures?id=LimeSurvey_LimeSurvey&pullRequest=2691&metric=new_duplicated_lines_density&view=list)

but failed ?

**Comment by gabrieljenik** [comment]
@Shnoulle This is tested by you already, right?
I also gave it a test but thinking about  reproduction stpes of 18436 and 18034.

If OK, maybe you can set the label to "tested"

**Comment by Shnoulle** [comment]
18436 ? don't remind

I test 18034 : yes , i use a invalid language for update the code when send message.

**Comment by Shnoulle** [comment]
https://bugs.limesurvey.org/view.php?id=18436 : right

**Pull request merged**
