### PR TITLE
Fixed issue #18193: Question theme error: Missing metadata (Type: X)

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: questionThemeNameValidator in afterFind Yii event

### CODE REVIEW

**Comment by Shnoulle** [comment]
Some old lss/lsa didn't have valid `question_theme_name` then fix it when load if needed.

Did you try with https://forums.limesurvey.org/forum/german-forum/127651-fragebogen-bricht-ab (see related mantis issue)

**Comment by c-schmitz** [comment]
I have the same doubts regarding performance. Could this be done more performance-friendly?

**Comment by Shnoulle** [comment]
> I have the same doubts regarding performance. Could this be done more performance-friendly?

On save ? Save happen lesser.

And fix on update for older value ?

**Comment by olleharstedt** [comment]
Is the event inside a loop?

**Comment by Shnoulle** [comment]
> Is the event inside a loop?

? All question are find at a time.

**Comment by Shnoulle** [comment]
> > I have the same doubts regarding performance. Could this be done more performance-friendly?
> 
> On save ? Save happen lesser.
> 
> And fix on update for older value ?

This ?

**Comment by tiborpacalat** [comment]
Fixing it on save sounds fine, please update the patch.

**Comment by Shnoulle** [comment]
5 and master , right ?

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/3252

**Pull request closed without merging**
