### PR TITLE
Fixed issue #18330: SurveySetting type date doesnt show datepicker

### PR DESCRIPTION
**Pull request by gabrieljenik**
The solution is a bit wide, so must be tested in many scenarios/screens.
There was a JS issue related to a complex ID (with brackets) which caused JS errors.

### CODE REVIEW

**Comment by Shnoulle** [comment]
>  There was a JS issue related to a complex ID (with brackets) which caused JS errors.

Unable to fix it ? I k now anything is alwed in HTML5 but Yii have a clean solution

**Comment by gabrieljenik** [comment]
> Unable to fix it ? I k now anything is alwed in HTML5 but Yii have a clean solution

Yes, this is the fix: A proper treatment of the ID

**Comment by Shnoulle** [comment]
> > Unable to fix it ? I k now anything is alwed in HTML5 but Yii have a clean solution
> 
> Yes, this is the fix: A proper treatment of the ID

I don't understand or I don't make myself understood :+1: 
I mean no way to remove the bracket in the id ? Using CHtml::getIdByName for example ?

**Comment by gabrieljenik** [comment]
> I mean no way to remove the bracket in the id ? Using CHtml::getIdByName for example ?

I didn;t want to mess into that. Seemed more complicated.

**Comment by Shnoulle** [comment]
I make a quick test

**Comment by Shnoulle** [comment]
See : https://github.com/LimeSurvey/LimeSurvey/pull/2632

A one line fix seems better than a JS hack.
And more : select or text have alreay good id for example see the `plugin_TerminPlaner_isActive` in this plugin example.

**Comment by Shnoulle** [comment]
And more : the dfefault lable alreay use CHtml::getIdByName

**Pull request closed without merging**
