### PR TITLE
RPC Routine to delete responses of particular token in a survey.

### PR DESCRIPTION
**Pull request by ravindrakhokharia**
Added delete_responses API routine, will delete responses of the participant, its files, response timings if available

This function will delete Responses for the token passed, 
It will delete all the response related files from the server,
Delete all responses from the table for the Token if available,
Delete Response timings, if available in the table.

### CODE REVIEW

**Comment by bsdis** [comment]
Why did this excellent PR never get merged? :(

**Comment by maziminke** [comment]
I also consider this a very useful API function.

@olleharstedt @gabrieljenik Is there much work involved getting this adjusted as needed and added to LS3 LTS and LS 4?

**Comment by olleharstedt** [comment]
> I also consider this a very useful API function.
> 
> @olleharstedt @gabrieljenik Is there much work involved getting this adjusted as needed and added to LS3 LTS and LS 4?

No, seems straight-forward.

**Comment by olleharstedt** [comment]
Well, I guess the code should use the existing model logic to delete responses.

**Comment by gabrieljenik** [comment]
`Firstly you informed to move the delete files function to the Survey_Dynamic Model`
Not sure if agree with file handling inside a model. Theorically, agree. From practice, models usually handle DB representation. How is that doen now?

Maybe put that specifically on a helper method. Something like: removeFilesForResponse?

**Comment by olleharstedt** [comment]
> Theorically, agree. From practice, models usually handle DB representation. How is that doen now?

IMO, everything should be purged from the ActiveRecord classes except database access. Everything else should be moved to service classes (also called components in Yii). Very long journey to get there, tho.

**Comment by gabrieljenik** [comment]
So, helper method would be middle ground in that journey?

**Comment by olleharstedt** [comment]
No, helper classes with sensible names and limitations. Instead of `activateSurvey` there should be `SurveyActivator` etc. I think Tonis already did that?

**Comment by arnaudbore** [comment]
I know this PR has been closed and seems "dead" since June 2020 but I would like to add my thumb up :+1:  and push forward this feature. I'm also wondering why deleting a response depending on the token and not depending on the ID of the response.

**Comment by arnaudbore** [comment]
Hi @olleharstedt ,
Thank you for reopening this PR. What would be the next step ? I'm afraid @ravindrakhokharia may have move to others projects and maybe not interested anymore in this PR. Just speculation here. Last question: what about deleting response depending on the id instead of a token? In my opinion, ID makes it more flexible.

**Comment by olleharstedt** [comment]
Next step would be for someone to resolve the conflict. Should be easy, maybe just move the function to the bottom.

> Last question: what about deleting response depending on the id instead of a token? In my opinion, ID makes it more flexible.

Sure. Just have to find someone willing to code it. :)

**Comment by arnaudbore** [comment]
Ok I'll give it a try. But definitively will need some help. :+1:

**Comment by olleharstedt** [comment]
Feel free to join our Discord channel for questions.

**Comment by c-schmitz** [comment]
Is this PR still needed? If yes, it needs an update.

**Comment by arnaudbore** [comment]
This can be closed.

**Pull request closed without merging**
