### PR TITLE
Fixed issue #18488: Conditions are not properly highlighted if they have additional spaces

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: trim when view
Dev: trim when save
Dev: uneeded trim in expression

### CODE REVIEW

**Comment by c-schmitz** [comment]
I think it solves only part of the problem, as it only trims surrounding spaces of the equation.
It still does not take core of double spaces inside the condition parts, correct?

**Comment by Shnoulle** [comment]
>  It still does not take core of double spaces inside the condition parts, correct?

There are no issue with double or triple space inside relevance equation or line feed etc …
https://github.com/LimeSurvey/LimeSurvey/blob/b10a1b17c3d25d08867fe19cea6915b1b644ffc4/application/helpers/expressions/em_core_helper.php#L2485 don't care of multiple space (don't care of any space)
```Q00.NAOK 
           
== 


"Y"```

===
`Q00.NAOK=="Y"`

There are just the space and line feed after the first `{ ` (and before the last) to allow javascript inside question.

Added it during Expression Manager construction some years ago

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/blob/b10a1b17c3d25d08867fe19cea6915b1b644ffc4/application/helpers/expressions/em_core_helper.php#L2507

**Review by c-schmitz — CHANGES_REQUESTED** [review]
Looks good so far, please check my new information in the bug report.

**Comment by Shnoulle** [comment]
Screen-cast : only one «seems to be a space» character
Peek 17-11-2022 10-36

**Review by c-schmitz — APPROVED** [review]

**Pull request merged**
