### PR TITLE
Fixed issue #18102: Export Duplicate entries in the Excel Form

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: replace rewriteLimitOffsetSql for SQL SERVER up to 11
Dev: inspiration by Yii2

### CODE REVIEW

**Review by gabrieljenik — COMMENTED** [review]
Code structure seems OK.
Haven't tested it

**Comment by Shnoulle** [comment]
> Code structure seems OK. Haven't tested it

Super hard to test … and code structure for microsoft SQL server ;)

**Comment by Shnoulle** [comment]
Tested by reporter

Alternative more easy to test : https://bugs.limesurvey.org/view.php?id=18420 see what happen with this file.

**Comment by olleharstedt** [comment]
Hmm, shouldn't this also be a patch for Yii 1.1?

**Comment by Shnoulle** [comment]
Yes, too … but must find a good way to reproduce, i have to report : it take time … 
And waiting for merge in Yii1 can be longer. Il like

**Comment by olleharstedt** [comment]
Maybe you can create a thread on their forum, @Shnoulle ?

**Pull request merged**
