### PR TITLE
[WIP] Dev: fix travis for ranking

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: issue https://bugs.limesurvey.org/view.php?id=15385
Dev: is worst in develop than in master
Dev: manual checking, unsure it‘s OK ;)

### CODE REVIEW

**Comment by Shnoulle** [comment]
Let's see if travis is happy

**Comment by olleharstedt** [comment]
You can also hack `.travis.yml` to use `--filter Ranking` to only run the ranking test. Slightly faster feedback.

**Comment by Shnoulle** [comment]
Yes, but don't want to setup extra part on my allday system …
Then i do it in a VM

**Comment by olleharstedt** [comment]
I mean hacking the main .travis.yml.

**Comment by Shnoulle** [comment]
@olleharstedt : there are 2 different fix … maybe revert and check only with https://github.com/LimeSurvey/LimeSurvey/pull/1327/commits/2313cfc645be3644894a5dcda7d32b234e513aa3 ?

**Comment by Shnoulle** [comment]
Else : we don't have the same test in master and develop …

**Comment by olleharstedt** [comment]
Yes, I don't want to merge this, since it changes to test.

**Pull request closed without merging**
