### PR TITLE
removed survey language switching prevention in the API (only additional languages)

### PR DESCRIPTION
**Pull request by gekkedev**
It is not necessary to block language switching as a survey owner could do this by the webinterface, too.

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
Main language can not be changed after the survey has been created

**Comment by gekkedev** [comment]
True, thought that was the same as additional_languages, those are changeable though, but I adjusted the pull request now. To conclude, the survey attribute ```language``` should not be changeable, ```additional_languages``` should be.
Not sure if the API should support it, but we could split the languages, since all of them are written into one string, separated by spaces.

**Comment by c-schmitz** [comment]
When you add/or delete a language from a survey the integrity of the survey must be checked and fixed (question groups/questions/answers etc.) need to be created/deleted for all language if they are missing/obsolete-
This is all missing currently. Please complete the patch accordingly.

**Comment by gekkedev** [comment]
Sounds like we could as well write separate methods for language deletion and creation.

**Comment by gekkedev** [comment]
Too busy, sorry. Feel free to continue or close it.

**Pull request closed without merging**
