### PR TITLE
DEV: Fix config.xml

### PR DESCRIPTION
**Pull request by gabrieljenik**
- Add missing 'type' on Bootstrap Dropdown config.xml

### CODE REVIEW

**Comment by Shnoulle** [comment]
test failed ? I need to do same to check theme page :)

**Comment by gabrieljenik** [comment]
@glimz Can you please remove the test failed tag? This needs to be pushed. Has no story. This is because when using debug a dump happens when entering question editor.

**Comment by gabrieljenik** [comment]
@olleharstedt Can I ask for your reviewal?

**Comment by Shnoulle** [comment]
> test failed ? I need to do same to check theme page :)

:)

**Comment by Shnoulle** [comment]
We need it in master … No way to get theme list with debug> 0 …

**Pull request merged**
