### PR TITLE
Allow kcfinder uploadDir to be a symlink

### PR DESCRIPTION
**Pull request by Jelle-S**
Allow the ckfinder upload dir to be a symlink.

LimeSurvey issue: https://bugs.limesurvey.org/view.php?id=10820

Also created an upstream pull request:
https://github.com/sunhater/kcfinder/pull/136

### CODE REVIEW

**Comment by Jelle-S** [comment]
Seems like all checks passed. Any chance this could get merged?

**Comment by c-schmitz** [comment]
Did you check and test it completely? Last time it utterly failed and forced us to re-release so there better not be another issue this time.

**Comment by Jelle-S** [comment]
I'll double check to make sure

**Comment by Jelle-S** [comment]
Ok, so here's what I tested:

Default installation with the upload dir in the limesurvey root:
- Create survey & save (otherwise you get the warning: "To be able to upload images or other content you have to save your survey once first."
- Use ckeditor to insert an image in the description, save again
- Add one group & question
- Preview the survey: Image is there

Then I threw the whole installation away to start clean:

**Moved** the upload dir to my desktop, created a symlink (named 'upload') in limesurvey's root directory linking to that upload dir on my desktop, reinstalled limesurvey:
- Create survey & save (otherwise you get the warning: "To be able to upload images or other content you have to save your survey once first."
- Use ckeditor to insert an image in the description, save again
- Add one group & question
- Preview the survey: Image is there

Then I threw the whole installation away again to start clean:

**Deleted** the upload dir from limesurvey's root:
- limesurvey wouldn't let me install because of the missing directory

**Created** an **empty** upload dir:
- limesurvey let's me install but kcfinder crashes because of missing upload/surveys directory. But I'm guessing this is by design since limesurvey expects that folder to just be there?

Did I test everything OK? Or are there more use cases to test?

**Comment by c-schmitz** [comment]
Sounds good. Thank you.

**Comment by c-schmitz** [comment]
There was a merge commit in your patch. 
I had to revert it again.
Please create a new clean pull request.

**Comment by Jelle-S** [comment]
I'm so sorry, I'm clearly no too experienced with these pull requests. New PR: https://github.com/LimeSurvey/LimeSurvey/pull/502

Again, my apologies

**Pull request merged**
