### PR TITLE
[ENH] transfer delete response to 3.x-LTS

### PR DESCRIPTION
**Pull request by arnaudbore**
Add RPC function to delete a response depending on the ID of the response.
This PR followed this original one #78 and #1928

### CODE REVIEW

**Comment by arnaudbore** [comment]
@olleharstedt, @Shnoulle next step ?

**Comment by Shnoulle** [comment]
For me : it's great

**Comment by olleharstedt** [comment]
Risk is low, and any bug would be localized to the new functionality, so for me it's OK.

**Comment by olleharstedt** [comment]
Uh, please port the test too. The current implementation contains a bug. And copy-paste my fixed version, not the original buggy version. Thank you.

**Comment by arnaudbore** [comment]
Should be fine now...If I found the bug you were taking about. @olleharstedt  
Thank you for your help.

**Comment by olleharstedt** [comment]
You need to copy the test survey, too.

Now it breaks at phpunit start, for some reason. Hm.

**Comment by arnaudbore** [comment]
@olleharstedt what do you mean by "copy the test survey" ? I think I've done exactly the same thing as the previous PR.

**Comment by arnaudbore** [comment]
Maybe it's a Travis issue you could restart it. @olleharstedt  @Shnoulle

**Comment by olleharstedt** [comment]
> @olleharstedt what do you mean by "copy the test survey" ? I think I've done exactly the same thing as the previous PR.

I had to update the test survey file you used to get it to work. I had a duplicated survey id, which caused a failure.

**Comment by olleharstedt** [comment]
Oh wait, maybe you did a copy already. Sorry, didn't see in the overview.

**Comment by olleharstedt** [comment]
Hm, did you base this commit on master or 3.x-LTS branch? The composer.json file seems incorrect, for some reason. Weird.

**Comment by olleharstedt** [comment]
Or maybe it's based on an old version of 3.x-LTS branch?

**Comment by olleharstedt** [comment]
The latest commit when I check out this PR is from Fri Mar 26.

**Comment by olleharstedt** [comment]
Maybe it's easier if I just merge it and fix any issue after. :thinking:

**Comment by arnaudbore** [comment]
It was 3.X-LTS but maybe an "old" (but not so old) one. I'm not modifying the composer.json file in this PR.

**Comment by olleharstedt** [comment]
Yeah, let me merge tomorrow. If it's too much trouble I can revert.

**Comment by arnaudbore** [comment]
Perfect I will be available if you need anything.

**Comment by olleharstedt** [comment]
You still had a bug here: it should be delete_response, not delete_responses. Will fix.

**Pull request merged**
