### PR TITLE
DEV implement yii2-like model::findOne() instead of model::model()->findByPk()

### PR DESCRIPTION
**Pull request by TonisOrmisson**
Also replaced all 
`Survey::model()->findByPk($iSurveyId)` to Yii2-like `Survey::findOne($iSurveyId)` in the Models folder

The overall idea is that Yii1 end of maintenance was Dec 31, 2016. So going to yii2 eventually probably is inevitable

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findOne()-detail

**Comment by Shnoulle** [comment]
It's to move to Yii2 after more easily ?

**Comment by TonisOrmisson** [comment]
yes

**Comment by olleharstedt** [comment]
> After that we will only respond to and fix security issues if any will be found until at least the end of 2018.

http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/

**Comment by olleharstedt** [comment]
> Yii 1.1.19 is compatible with PHP 7.1 that, at the time of this writing, has an announced security support until December 1, 2019.

http://www.yiiframework.com/news/137/yii-1-1-19-is-released/

**Comment by Shnoulle** [comment]
Because you call parent::findByPk : you losse the static call of findByPkCache ? No ?

We use a lot Survey::model()->findByPk and do one SQL request each time if we don't have a static.

**Comment by c-schmitz** [comment]
Yii 1.1 is currently under maintenance mode. Continued support and bug fixes for this version has ended on December 31, 2016. Security fixes will be provided until December 31, 2019.

**Comment by TonisOrmisson** [comment]
@Shnoulle 
I'm not sure it changes much of that since it's just a shortcut to the current usage. 
And regarding caching - I tend not to think too much on that and hope on the DB engine caching.

**Comment by Shnoulle** [comment]
>  I'm not sure it changes much of that since it's just a shortcut to the current usage.

No because you use parent and not self :)

>  And regarding caching - I tend not to think too much on that and hope on the DB engine caching.

It's not caching, it static here : with previous version we put Survey::model()->fincByPk in memory 

Maybe you're right about DB caching

**Comment by c-schmitz** [comment]
I don't think it makes much sense. Even when we update the code for Yii2 it is a simple seach & replace.

**Pull request closed without merging**
