### PR TITLE
Dev: Convert ternary operators to null-coalesce where applicable, using Rector

### PR DESCRIPTION
**Pull request by machitgarha**
Dev: Convert ternary operators to null-coalesce where applicable, using Rector.

I found it hard on my eyes to see `isset()`s every so often with ternary, so I decided to replace them with modern null-coalescing operator `??`, with the help of [Rector](https://getrector.org/). It includes `=== null` and `!== null` changes as well.

Doing all these kind of upgrades (e.g. `array()` to `[]` conversion) in one big PR might become a pain for reviewers, so I decided to only do this small hop.

Note that, I don't know why, but Rector changed some indentations not relating to the change itself, so I'm going to fix them as well (so this PR is WIP).

And, in the big picture, LS can start using Rector... It sounds to be a powerful tool!

### CODE REVIEW

**Review by machitgarha — COMMENTED** [review]
So I reviewed and reverted extra stuff. Now it should be ready (although I reverted few of the good changes).

**Comment by c-schmitz** [comment]
Thank you  - can you amend your PR to not touch files in /third_party directories?

**Comment by machitgarha** [comment]
Oops. I did something wrong. I cannot reopen it. @c-schmitz, are you able to do so?

**Comment by machitgarha** [comment]
@c-schmitz, this PR seems to be corrupted, so I created a new one with the changes you requested.

**Pull request closed without merging**
