### PR TITLE
Fixed issue #18428: Image select QuestionTheme settings are shown on Core theme settings

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]
It's because it's added to core ?

How … F …

**Comment by Shnoulle** [comment]
PS : maybe review the commit when merging

> Fixed issue #18428: Image select QuestionTheme settings are shown on Core theme settings

**Comment by gabrieljenik** [comment]
> PS : maybe review the commit when merging
> 
> > Fixed issue #18428: Image select QuestionTheme settings are shown on Core theme settings

@olleharstedt What'the best way to ammend the message so it show better on the change log?

**Comment by olleharstedt** [comment]
> > PS : maybe review the commit when merging
> > > Fixed issue #18428: Image select QuestionTheme settings are shown on Core theme settings
> 
> @olleharstedt What'the best way to ammend the message so it show better on the change log?

Hm do you have an edit-button next to PR title? I do, dunno if it's permission related. Else I can do it when merging. What's the new title?

**Comment by gabrieljenik** [comment]
> Hm do you have an edit-button next to PR title? I do, dunno if it's permission related. Else I can do it when merging. What's the new title?

Done. Thought the changelog was built from commit messages only.
Somehow the title f the bug changed during time. Haven't gone too much into it :)

**Comment by olleharstedt** [comment]
Ehm was it done? I merged it now.

**Pull request merged**
