### PR TITLE
DEV: SQL -> AR; add UserGroup->hasUser()

### PR DESCRIPTION
**Pull request by TonisOrmisson**
Some fixes regarding moving to AR instead of plain SQL queries. 
Ended up adding the UserGroup->hasUser() method also

### CODE REVIEW

**Comment by Shnoulle** [comment]
👍 just one thing : i see `array_map('htmlspecialchars', $grpresult);` better because i think model must not filtering, but just validate if we filter the group name in views. I see it after merge is done :) except if you take a look ;)

**Comment by TonisOrmisson** [comment]
I think the encoding should be done in views via CHtml::encode(), not in controller. By doing it in controller like that we loose the object oriented way.

**Comment by TonisOrmisson** [comment]
In this case I do not see the places where the encoding would be needed. Or am I missing something ?

**Comment by Shnoulle** [comment]
> I think the encoding should be done in views via CHtml::encode(), not in controller.

+1 encoding it's a view task :). 

Else : 20 caracter only … in `admin/usergroups/sa/view/ugid/1` and `/admin/usergroups/sa/view` (but here : we have an XSS in description with an old 3.0.0 beta. I check on master).

**Pull request merged**
