### PR TITLE
Dev: avoid bad helper load

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: sometimes need to be sure a class is loaded, Yii does the job, let hime do the job

### CODE REVIEW

**Comment by olleharstedt** [comment]
Better: Throw exception if slash is found?

**Comment by olleharstedt** [comment]
Actually, could be an assert (turned off on production). And then fix all cases in the code which is wrong.

**Comment by olleharstedt** [comment]
Wait, this is LS3?? Nah, come on.

**Comment by Shnoulle** [comment]
> Better: Throw exception if slash is found?

Then : need to fix whole current error ? 
Why not .

DEBUG + forcedsuperadmin : throw exception

**Comment by Shnoulle** [comment]
> Wait, this is LS3?? Nah, come on.

😎 🕺

**Comment by Shnoulle** [comment]
> Wait, this is LS3?? Nah, come on.

Reason : since you remove it, maybe it's needed in some specific view :D

**Comment by olleharstedt** [comment]
It might be. If you want to fix it you can revert my fix and then replace the '/' with '.'. And also test quick translation after.

**Comment by olleharstedt** [comment]
> DEBUG + forcedsuperadmin : throw exception

`assert()` is even better, because it's not even executed in production mode (in PHP 7+).

**Comment by olleharstedt** [comment]
But we would have to configure assert_options etc, might be too much. https://www.php.net/manual/en/function.assert.php

**Comment by Shnoulle** [comment]
Maybe some user with external hoster want to help …

But : why not : to be in manual ?

**Comment by olleharstedt** [comment]
> Maybe some user with external hoster want to help …

debug = 2 should enable all assertions in the system.

**Comment by olleharstedt** [comment]
> But : why not : to be in manual ?

Which part? :thinking:

**Comment by Shnoulle** [comment]
> > Maybe some user with external hoster want to help …
> 
> debug = 2 should enable all assertions in the system.

It's the case currently ?


> > But : why not : to be in manual ?
> 
> Which part? thinking

Use assert :)

**Comment by olleharstedt** [comment]
> It's the case currently ?

No, it's not. No logic added for assert() yet. It's in the new code quality guideline as a way to check internal invariants. Have to check the Yii 3 approach too, if they did something.

**Comment by olleharstedt** [comment]
https://manual.limesurvey.org/Code_quality_guide#Assertions

**Comment by olleharstedt** [comment]
But this will be added to LS4, not LS3. :joy:

**Comment by Shnoulle** [comment]
:)

**Pull request closed without merging**
