### PR TITLE
Dev: Allow beforeEmail events to update core replacement

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: sample : EXPIRY on user language, MESSAGE from user in place of SURVEYDESCRIPTION
Dev: …

### CODE REVIEW

**Comment by Shnoulle** [comment]
No impact : no core impact, only external Plugin more easy to write.

**Review by gabrieljenik — APPROVED** [review]
Check. Haven't tested.
Seems a good idea

**Comment by olleharstedt** [comment]
Should be in dev tho? Since it's not a bug fix?

**Comment by Shnoulle** [comment]
Then : new plugin can not use it … and need to find a workaround.
This make just more complex for plugin dev., and they have to manage multiple version.

It's one of the reason why i didn't try to improve LimeSurveyAPI : time to be merged : i already publish the plugin

Here : it's really a light update, then i think its good on master.

**Comment by olleharstedt** [comment]
Fine.

**Pull request merged**
