### PR TITLE
Fixed issue #18029: Removed html tags in emails

### PR DESCRIPTION
**Pull request by fsay2604**
Fixed issue #18029: Removed html tags in emails
Dev: Add js script to change configuration of loaded instances of CKEDITOR in the email templates view to prevent losing html tags when switching from wysiwyg to source mode. The fullpage config: "With these settings in place, CKEditor 4 will output the entire HTML page, including the elements outside the <body> section."

### CODE REVIEW

**Comment by Shnoulle** [comment]
In https://github.com/LimeSurvey/LimeSurvey/blob/9e9d3b4658352cda3b37d202e0f0aded0be6ab35/application/views/admin/survey/prepareEditorScript_view.php#L30 seems better in my opinion.

And document ready didn't work with popup editor

**Comment by fsay2604** [comment]
You are right, I move the code to this file but it doesn't affect the popup editor configuration neither.

**Comment by fsay2604** [comment]
I pushed a new commit that changes the configuration of the popup editor if the action is related to edit email templates. Let me know if I need to change something.

**Comment by c-schmitz** [comment]
Is this only a problem in v3, or also in v5?

**Comment by c-schmitz** [comment]
@fsay2604 Does this issue only affect v3 ? Or is it also present in v5 ?

**Comment by fsay2604** [comment]
I have to install a v5 version on my machine before I can confirm that. I'll get back to you asap.

**Comment by fsay2604** [comment]
@c-schmitz I confirm that this issue is also in v5. But the fix in the v3 wouldn't work in v5 since the name of the ckeditor div has changed from "email_..." to "cke_email_...". I can make another PR for the V5 to fix the issue if this PR is accepted (this is my first contribution, I will get familiar with the procedure and standards over time! ). 

Let me know if I can do something else to help.

**Comment by c-schmitz** [comment]
@fsay2604 Thank you for your contribution! Yes, please create another PR for v5.

**Pull request merged**
