### PR TITLE
Added .row to gender q-view buttons

### PR DESCRIPTION
**Pull request by tammoterhark**
Now a PR to answers_html after several other attempts...

### CODE REVIEW

**Comment by Shnoulle** [comment]
OK for this time, but next one : remind [Git commit messages](https://manual.limesurvey.org/Standard_for_Git_commit_messages)

Here : Dev: Added .row ...

Seem OK

**Comment by Shnoulle** [comment]
And : PS : i remove the cold-sm-6 from HTML actually : leave it for template. There are no reason to add one if we can not control it via attributes.

**Comment by tammoterhark** [comment]
Great! Also great about col-sm-6. That is indeed better in media statement in css. Is design decision, not developers decision.

**Comment by tammoterhark** [comment]
I learn day by day the tricks of developers. I might even become one... Thanks!

**Pull request merged**
