### PR TITLE
Fixed issue #18407: On-page conditions not working when pre-filling q…

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #18407: On-page conditions not working when pre-filling question with equation on the same page
Dev: ASSIGN didn't work really with javascript,
Dev: Minimal fix to don't throw JS error

### CODE REVIEW

**Comment by maziminke** [comment]
@gabrieljenik what your opinion regarding the fix? Does it look good to you?

**Comment by Shnoulle** [comment]
I don't remind if i test and fix in 5.X ?

5X have another update part about Expression manager javascript … must test

**Review by gabrieljenik — APPROVED** [review]
Code looks structurally OK.
Still, I am sorry, I haven't gone through the caveats of the diagnosis and solution.
This updates EM, so this is sensitive.

**Comment by Shnoulle** [comment]
The original issue is `document.getElementById('".$jsName."').value` without valid jsName … need to be avoided.

**Comment by gabrieljenik** [comment]
> The original issue is `document.getElementById('".$jsName."').value` without valid jsName … need to be avoided.

That is related to this `Dev: Minimal fix to don't throw JS error`, right?

> Dev: ASSIGN didn't work really with javascript,

That is related to this, right?
https://github.com/LimeSurvey/LimeSurvey/pull/2676/files#diff-a974f1aca3b64170e04f9ac415aadb10d9108696f0ae4ce07caee89d8a1447d3R1285

**Comment by Shnoulle** [comment]
> That is related to this, right?

Yes , but more : $stringParts is joined to do tghe final JS … then need more work than just move to jquery … to mpove to jquery : yoiu need to add `idToSet` variable …

**Comment by gabrieljenik** [comment]
Wouldn't it be easier to test and push if the 2 different issues were on 2 different PRs?

I feel someone else should be reviewing this as well

**Comment by gabrieljenik** [comment]
> What do you mean ? There are no related PR

It seems there are 2 different things tackled on the same PR.
If each issue had its own ticket and PR, I think would be eaiser to handle

**Comment by Shnoulle** [comment]
> > What do you mean ? There are no related PR
> 
> It seems there are 2 different things tackled on the same PR. If each issue had its own ticket and PR, I think would be eaiser to handle

No : only one fix for this issue … i don't find another way to fix this issue.

**Comment by gabrieljenik** [comment]
> No : only one fix for this issue … i don't find another way to fix this issue.

I didn't mean there was another way to fix the issue.

From the comments in the PR description you are solving the ticket and also fixing something else. Then seemed like you were fixing 2 issues on the same PR. That was what I meant.

Anyway, I will test the use case reported on the bug and be back.

**Comment by Shnoulle** [comment]
> From the comments in the PR description you are solving the ticket and also fixing something else. Then seemed like you were fixing 2 issues on the same PR. That was what I meant.


You mean  _Dev: ASSIGN didn't work really with javascript,_ ? No, it's a comment, i didn't fix it …

**Comment by gabrieljenik** [comment]
> You mean _Dev: ASSIGN didn't work really with javascript,_ ? No, it's a comment, i didn't fix it …

OK, confussion solved then :)

**Comment by Shnoulle** [comment]
@olleharstedt : can we have this tested and merged  in some week ?

I just want to know if i can apply on a fork before it was added.

It broke a lot of survey where you use equation …

**Comment by gabrieljenik** [comment]
> @olleharstedt : can we have this tested and merged in some week ?

Sorry @Shnoulle I have it on my list. A bit delayed. Sorry. Hope do it today or tomorrow. Thanks

**Comment by Shnoulle** [comment]
> Sorry @Shnoulle I have it on my list. A bit delayed. Sorry. Hope do it today or tomorrow. Thanks

You mean the test ? I really don't know how all of this is managed … 

When it's ready to merge : i check on 5 too …

**Comment by olleharstedt** [comment]
> > @olleharstedt : can we have this tested and merged in some week ?
> 
> Sorry @Shnoulle I have it on my list. A bit delayed. Sorry. Hope do it today or tomorrow. Thanks

Just ping me on Cliq when tested.

**Comment by gabrieljenik** [comment]
Tested successfully the situation described under the "reproduction steps".

**Pull request merged**
