### PR TITLE
Dev: debug 2 as default, max_execution_time at 240

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: A way to debug installer

### CODE REVIEW

**Comment by olleharstedt** [comment]
Hm, I don't think I support this. Better to just set debug = 2 on your local machine while debugging.

**Comment by olleharstedt** [comment]
OR: Let PHP check for CLI arguments if you install from command-line.

**Comment by Shnoulle** [comment]
It's only for pre-alpha and alpah : reset to 0 by default when beta :)

**Comment by olleharstedt** [comment]
https://www.php.net/manual/en/function.getenv.php

**Comment by Shnoulle** [comment]
It's not really for us, more for tester :).

**Comment by olleharstedt** [comment]
Yes, but test must happen on debug = 0. Some bugs are ONLY visible when debug = 0, and those are the ones we care about most.

**Comment by Shnoulle** [comment]
OK, good point :)

**Pull request closed without merging**
