### PR TITLE
Fixed issue #19763: Unable to answer multiple choice question with other

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: my error here : https://github.com/LimeSurvey/LimeSurvey/commit/89a3800356a2e94cfb459f0a595cb382f4adb3e8

### CODE REVIEW

**Comment by Oliver3012** [comment]
Hey @Shnoulle, thanks for taking care of the bug! What do you think: how fast will the fix be live for our surveys? 

We have to make a decision now: stopping the survey, deactivating the "Other"-option and start the survey again (which includes losing all cached answers) OR waiting for your fix.

**Comment by itsmevictor** [comment]
Thank you @Shnoulle for the quick fix! Obviously, the sooner the fix is pushed the better, but thank you already for reacting so rapidly. 

@Oliver3012 Depending on your survey, one option is to temporarily hide the multiple choice question by selecting "Yes" to "Always hide the question" in the question's settings. It's not optimal but at least you don't have to deactivate the survey at the risk of losing cached answers etc.

**Comment by itsmevictor** [comment]
Unless I am mistaken, the problem seems to be resolved, although I don't really understand how that can be since no commits were pushed since this morning.

**Comment by Oliver3012** [comment]
Our account has apparently been rolled back to 6.6.3:
image

**Comment by itsmevictor** [comment]
I have no idea where to find the version we're running on but that was probably it!

**Comment by ptelu** [comment]
The affected commit will be reverted until further testing has been done, and a new version will be released shortly.

**Pull request closed without merging**
