### PR TITLE
Fixed issue #15939: Update to 4x seems to have changed the Display/Export

### PR DESCRIPTION
**Pull request by gabrieljenik**
Adding group order criteria.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Oh shit …
https://github.com/LimeSurvey/LimeSurvey/pull/1398

**Comment by Shnoulle** [comment]
Strange : model seems fixed in 4.X : https://github.com/LimeSurvey/LimeSurvey/blob/1daf9d4347b9a102a26aa8ba67e70a20fd98438a/application/models/Question.php#L121-L123

We don't use relation in 4.X ?

**Comment by gabrieljenik** [comment]
Not sure I follow. The fix is about group order which didnd't include a sorting criteria.

**Comment by Shnoulle** [comment]
Yes, see this printanswer != printable :)

Always made the error

**Comment by sushmanadendlals** [comment]
Working as Expected,please refer Mantis for more details.

**Pull request merged**
