### PR TITLE
Fixed issue #18596: Reintroduce lost unit tests from merge

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by gabrieljenik** [comment]
Tests seem were failing. Strange is they are failing on places not updated by this PR.
The parent commit was green. Not sure what is happening.

**Comment by olleharstedt** [comment]
Hmmm rerunning jobs to check.

**Comment by olleharstedt** [comment]
Still failing.

**Comment by olleharstedt** [comment]
$_SESSION problem maybe? Or database fixture not cleared?

**Comment by gabrieljenik** [comment]
Will review.

**Comment by olleharstedt** [comment]
For one test I had to do $_SESSION = [] to clear session from previous test.

**Comment by gabrieljenik** [comment]
seems `surveyDynamic()::model($surveyId)-->getMaxId()` had some prior info and it was not getting refreshed.
We added a manual refresh.

Maybe we should:
- create clearMaxId() function (or an extra param)
- overload activeRecord->refreshMetadata() as to also refresh those
?

Also, didn't like the fact `static $maxId` is declared locally.
We can't reset it without recalculating.

**Comment by olleharstedt** [comment]
Well that was a new one :) Yeah, it's a problem for tests to cleanup everything when done, if the model classes are stateful like that. :stuck_out_tongue:

**Comment by gabrieljenik** [comment]
> seems `surveyDynamic()::model($surveyId)-->getMaxId()` had some prior info and it was not getting refreshed. We added a manual refresh.
> 
> Maybe we should:
> 
> * create clearMaxId() function (or an extra param)
> * overload activeRecord->refreshMetadata() as to also refresh those
>   ?
> 
> Also, didn't like the fact `static $maxId` is declared locally. We can't reset it without recalculating.

Does it worth putting this into a story?
Can this kind of situation happen in real life?

GetMaxId() should probably be refreshed on other AR operations, like Save(), Add(), Delete(), ...

**Pull request merged**
