### PR TITLE
Fixed issue #15819: Missing localization for group_name in add_group, set_group_properties, import_group

### PR DESCRIPTION
**Pull request by gabrieljenik**
'import_group' was working fine.
'add_group' was updated as to save to the QuestionGroupL10n model.

'set_group_properties' was updated as to be able to receive an array on 'questiongroupl10ns' param.
The method is backward compatible. If an 'questiongroupl10ns' is not given, then it is composed from the old name, description and language parameters.

Adding test for 'add_group' y 'set_group_properties'.

### CODE REVIEW

**Comment by olleharstedt** [comment]
You need to pull the Travis changes here to get green.

**Comment by gabrieljenik** [comment]
> You need to pull the Travis changes here to get green. Sorry.

Done

**Comment by olleharstedt** [comment]
OK, looks good now, the failure is inside the Travis build system itself.

**Comment by olleharstedt** [comment]
But now I can't see what this change is about? :thinking:

**Comment by Shnoulle** [comment]
Travis only for 4.2 and 74 with different DB : temporary issue : right ?

**Comment by gabrieljenik** [comment]
> But now I can't see what this change is about?

Should I create a new PR?

**Comment by gabrieljenik** [comment]
New PR replaceing this: https://github.com/LimeSurvey/LimeSurvey/pull/1793

**Pull request closed without merging**
