### PR TITLE
DEV: implement survey->timingsTableName from Survey object

### PR DESCRIPTION
**Pull request by TonisOrmisson**

### CODE REVIEW

**Comment by LouisGac** [comment]
I like the "table name" fix.

**Comment by TonisOrmisson** [comment]
Yup, I'll get the other tables similarly

**Comment by LouisGac** [comment]
just in case: http://www.yiiframework.com/doc/api/1.1/CActiveRecord#tableName-detail

**Comment by olleharstedt** [comment]
This commit and maybe others break a lot of things.

**Comment by olleharstedt** [comment]
Don't know if it's due to Ajax template.

**Comment by olleharstedt** [comment]
Please pull, test and fix.

**Comment by olleharstedt** [comment]
> CException
> Property "Survey.hasTimingsTable" is not defined. 

At survey delete, also.

**Pull request merged**
