### PR TITLE
New feature: Let user set default settings for statistics export in c…

### PR DESCRIPTION
**Pull request by kw-pr**
…onfig.php

I think this would be useful. If wanted I can also add the other options to make the pull request more complete.

### CODE REVIEW

**Comment by LouisGac** [comment]
Yes, very good idea! Thank you. 
But please, submit it to dev branch. 
(it will be merge with master)

**Comment by kw-pr** [comment]
@LouisGac Thanks for the answer!
I changed the commit base to develop.

**Comment by c-schmitz** [comment]
Where can these new settings be set? I am missing some kind of configuration & documentation here.

**Comment by kw-pr** [comment]
The settings as called statistics_noncompleted, statistics_showtextinline, statistics_usegraph. They can have the value 0 or 1. They can be set in application/config/config.php in the 'config' section.

I could add documentation in config-defaults.php or where would be a good place for that?

**Comment by maziminke** [comment]
Please also update/extend the manual if this gets added to the core!

**Pull request closed without merging**
