### PR TITLE
DEV: tests folder restructure - recommit

### PR DESCRIPTION
**Pull request by TonisOrmisson**
The re-commit. 
hands off autoloaders :)

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/927

**Comment by olleharstedt** [comment]
Cool. So, does it contain anything else the folder restructure? Any special commit I should check?

**Comment by TonisOrmisson** [comment]
Im just looking at the conflict, on the InstallationControllerTest. Dont understand that. I maually copied from master

**Comment by TonisOrmisson** [comment]
Should not contain anything apart from tests folder. some changes regarding the paths & namespaces. Otherwise relocation. but I would appreciate a re-check :)

**Comment by olleharstedt** [comment]
OK, well, I can't merge before the conflict is resolved, whatever it's about.

**Comment by TonisOrmisson** [comment]
I just re-added the original file to resolve conflict. need to delete this again

**Comment by olleharstedt** [comment]
None of these commits begin with "Dev:"?

**Comment by olleharstedt** [comment]
Btw, Travis is broken right now, so ignore that.

**Comment by TonisOrmisson** [comment]
Yup, I saw

**Comment by olleharstedt** [comment]
Can you fix the merge conflict, please? Should be trivial.

**Comment by olleharstedt** [comment]
Never mind, I fixed it. Thank you for your contribution. ^^

**Comment by olleharstedt** [comment]
Seems like there still both a data/ folder and resources/ folder. Can you remove the data folder please, and make sure everything is moved to resources?

**Comment by olleharstedt** [comment]
Tonis, come on. You removed all empty lines from the tests?

**Comment by olleharstedt** [comment]
A comment about the factorizations you made in CreateSurvey test - maybe we should subclass the Facebook webdriver and add our own LimeSurvey specific methods, like clickNext() to go to next page? What do you think?

**Comment by olleharstedt** [comment]
OK, I created a subclass called `LimeSurveyWebDriver`. Maybe we should also split it in frontend and backend to avoid potential method name conflict.

**Comment by TonisOrmisson** [comment]
Sry for silence. I was away on vacay for a week. 
Regarding the empty lines removal. Did not mean to do that. I copy-pasted some files contents manually from master source and the PhpStorm did some automatic formatting on that I did not realize. I have nothing against empty lines :)
Why did you revert that? The empty lines or any more problems?

**Comment by LouisGac** [comment]
Hey Tonis,

Olle is in holidays too. For what I understood, he's using the empty lines for navigation with Vim (Olle codes with Vim). Also, it's always useful to be able to compare the changes between two commits. 

Thank you again for your great work ;-)

**Comment by olleharstedt** [comment]
@TonisOrmisson You should use `git mv` to move files, so git understands what happens.

**Pull request merged**
