### PR TITLE
Fixed issue #16695 : we don't use jsonRPCClient Class

### PR DESCRIPTION
**Pull request by Shnoulle**

### CODE REVIEW

**Comment by Shnoulle** [comment]
LimeSurvey is a API server , not a client.

**Comment by c-schmitz** [comment]
The jsonRPCClient is used by the test() function of the remotecontrol controller.
It is an easy way to check/test the RC api. So please don't remove it.

**Comment by Shnoulle** [comment]
> The jsonRPCClient is used by the test() function of the remotecontrol controller.

No, there are a die() at start. I have another place to make my test (with more complex RC function) my self. 

If we need a test : best is to really create a test : https://github.com/LimeSurvey/LimeSurvey/tree/master/tests

**Comment by c-schmitz** [comment]
So, if you want to remove it, then please create the tests first. Otherwise just leave it.

**Comment by Shnoulle** [comment]
See https://github.com/LimeSurvey/LimeSurvey/pull/1603 

I don't understand how we can fix something we don't really use …

**Comment by maziminke** [comment]
> > The jsonRPCClient is used by the test() function of the remotecontrol controller.
> 
> No, there are a die() at start. I have another place to make my test (with more complex RC function) my self.
> 
> If we need a test : best is to really create a test : https://github.com/LimeSurvey/LimeSurvey/tree/master/tests

Well, **you** may have another way to test. But other may use the existing code for testing :-)

**Comment by Shnoulle** [comment]
> Well, you may have another way to test. But other may use the existing code for testing :-)

External dev search od `die()` function before looking at manual ?
Even if search show the manual at 1st : https://duckduckgo.com/?q=limesurvey+api+php  ?
stackoverflow too (usage of ->function) https://stackoverflow.com/search?q=limesurvey+API+php 
etc …

Usage of https://github.com/weberhofer/jsonrpcphp 

This one : https://github.com/nuxwin/JsonRPC seem to use `execute`

**Comment by c-schmitz** [comment]
As mentioned this will not be merged. It is neither necessary nor important and why remove something useful that does not bother anyone.

**Pull request closed without merging**
