### PR TITLE
Alternate PDF font for Croatian language

### PR DESCRIPTION
**Pull request by nmisic**
Added dejavusans as Croatian PDF font.

### CODE REVIEW

**Comment by c-schmitz** [comment]
Can you explain the reason behind the change? Is the default font not working?

**Comment by c-schmitz** [comment]
@nmisic Feedback please?

**Comment by nmisic** [comment]
Hi,

sorry for late feedback. Yes, the default font is not working. Chars like čćžšđČĆŽŠĐ are displaying as ? char. With this change everything is working properly on PDF download. 

Is there any other kind of testing or configuration information required?

**Comment by c-schmitz** [comment]
No, thank you. It is fine.

**Pull request merged**
