### PR TITLE
Dev: Convert ternary operators to null-coalesce where applicable, using Rector

### PR DESCRIPTION
**Pull request by machitgarha**
See #2578 for more information.

Created this because somehow the previous PR was corrupted and couldn't be merged.

### CODE REVIEW

**Comment by olleharstedt** [comment]
Rector is a refactoring tool, I take it?

**Comment by machitgarha** [comment]
@olleharstedt, actually it's more than just refactoring, but mainly yes.

**Comment by Shnoulle** [comment]
https://github.com/RectorPHP/Rector ?

**Comment by machitgarha** [comment]
@Shnoulle, yes.

**Comment by olleharstedt** [comment]
OK, CI is green, and `??` works from PHP 7.2, right? I approve.

**Review by olleharstedt — APPROVED** [review]

**Comment by machitgarha** [comment]
@olleharstedt, actually null-coalescing operator is an addition to PHP 7.0.

And thanks for the review.

**Comment by machitgarha** [comment]
Anyone willing to merge this?

**Comment by olleharstedt** [comment]
Done. Thank you. :)

**Pull request merged**
