### PR TITLE
14260 mark hidden questions for LS4

### PR DESCRIPTION
**Pull request by mbischof**
Fixed issue # : 
New feature # :
Changed feature # :
Dev: 
Dev:

### CODE REVIEW

**Comment by maziminke** [comment]
@lacrioque Can you please check if this looks fine and then merge?
Thanks!

**Comment by Shnoulle** [comment]
Can you explain the exact feature here ?

Is this related to such feature : https://github.com/LimeSurvey/LimeSurvey/pull/1258 ?

PS : i don't update this feature when i can test Hidden attribute by Expression + hide with css or HTML …

**Comment by Shnoulle** [comment]
OK, checked : i‘m totally against this commit : only using color/opacity is reall a bad solutiuon.

See my proposal
Capture d’écran du 2019-05-22 12-20-42

**Comment by Shnoulle** [comment]
And nned screenshot.

Ps : if you show it elsewhere : i think we must show EM error before hidden or not …

**Comment by maziminke** [comment]
This is the related bugtracker ticket: https://bugs.limesurvey.org/view.php?id=14260

As outlined before, we simply add a CSS class which allows users to mark hidden questions at their admin theme. Nothing more, nothing less.
We do NOT add any colors or the like so I don't agree to your objections.

**Comment by Shnoulle** [comment]
Then : i don't really understand the point …

Usage of text or data- or informatin on titke is best.

And since css3 is great `[data-attribite-hidden]{color: red}` do the trick for admin template

**Comment by Shnoulle** [comment]
If it's for adding CSS/data- in left part : need

1. Question type class/data (i need it …)
2. Hidden attribute
3. Random group attribute (i need it …)
4. Have or not condition/expression
5. …

**Comment by lacrioque** [comment]
I will close this and reapply it without so many unecessary whitespace changes.
Also data-attributes are applied to the question blocks.

**Comment by Shnoulle** [comment]
Yep data-attributes is great :)

I must find a way for random-group for a client now …

**Comment by Shnoulle** [comment]
@lacrioque : one think more needed maybe : EM error inside question ? 
More PHP time consuming maybe … but things it's more needed than other one.

**Pull request closed without merging**
