### PR TITLE
Fixed issue #13437: simple statistics looks odd

### PR DESCRIPTION
**Pull request by gabrieljenik**
Made the view responsive and have 1, 2 columns or 3 depending on the screen width.
Made the legends to be below the chart, and not on its right side.

### CODE REVIEW

**Comment by cdorin93** [comment]
Hello @gabrieljenik , could you please check why travis is red? Will test it after

**Comment by gabrieljenik** [comment]
> Hello @gabrieljenik , could you please check why travis is red? Will test it after

Not sure why. The error is in the "create test survey" script and this has nothing to do with that.
@olleharstedt has more experience with Travis. Sometimes it fails I think..

@olleharstedt What do you think?

**Comment by olleharstedt** [comment]
You need to merge develop into this PR to include the geckodriver fix.

**Comment by gabrieljenik** [comment]
> You need to merge 3.x-LTS into this PR to include the geckodriver fix.

Worked good!

**Review by eddylackmann — APPROVED** [review]

**Review by eddylackmann — APPROVED** [review]

**Pull request merged**
