### PR TITLE
Fixed issue #18343: Problem with interpreting double slash in URL (IIS)

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: use PHP to construct the url
Dev: check if non empty before adding it

### CODE REVIEW

**Review by gabrieljenik — APPROVED** [review]
Code looks OK. Not tested

**Comment by Shnoulle** [comment]
Same than 3LTS except the contdir (unsure it's used)

**Comment by Shnoulle** [comment]
Reporter test the commit on 3LTS : fixed the popup editor but have another issue with Placeholder for example.
https://bugs.limesurvey.org/view.php?id=18343#c72044

OK to set it as tested ?

**Comment by Shnoulle** [comment]
Need to check and fix https://bugs.limesurvey.org/view.php?id=18811

**Comment by Shnoulle** [comment]
I redo a simple fix … 
See https://bugs.limesurvey.org/view.php?id=18811

**Pull request closed without merging**
