### PR TITLE
Fixed issue #18884: Stored XSS in Survey Groups Function

### PR DESCRIPTION
**Pull request by gabrieljenik**
Avoid the issue for users other than superadmin. 
It doesn't treat existing groups.

### CODE REVIEW

**Comment by Shnoulle** [comment]
No,
we need to encode it when shown.

1. XSS protection is here for survey, for participant only. Not for admin part
2. No admin part must allow any XSS, by superadmin or not
3. This description didn't have an HTML editor (and there are no real reason to hide HTML)
4. This is the lits of group : no reason to have HTML

The 5.X have the good solution. No need to filter or restrict, just is not HTML, then always encode when show (we show it only on list)

**Comment by Shnoulle** [comment]
title must be encoded too …

**Comment by Shnoulle** [comment]
> This patch applies the same principles that are applied on other parts of the system, so not sure about that statement.

No,

**It's false** … you can add script in group title : the group title are filtered when view in group list.

Same for question text i organizer or question list.

Please : check the 5.X version where we don't have this issue…

**Comment by Shnoulle** [comment]
> show them as saved (LSYii_Validator).

We **NEVER**  show something as saved in admin part ! ONLY on public survey page.

**Comment by gabrieljenik** [comment]
Ready for re-reviewal @Shnoulle

**Comment by gabrieljenik** [comment]
Closed in favor of #3241

**Pull request closed without merging**
