### PR TITLE
Fixed issue #16882: Unable to set Html editor in Personnal settings

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by cdorin93** [comment]
Hey @gabrieljenik , can you please update the branch? I think this one has issues with the pop up mode (if I choose pop up mode in personal settings, the pop up won't happen in questions / groups)

**Comment by gabrieljenik** [comment]
I think looks better now, right?

**Comment by cdorin93** [comment]
hey @gabrieljenik , have time to rebase it (for master?) and solve the conflicts?

**Comment by gabrieljenik** [comment]
New PR: https://github.com/LimeSurvey/LimeSurvey/pull/1731

**Pull request closed without merging**
