### PR TITLE
Fixed issue #14227: Some token with existing reponse can send PHP War…

### PR DESCRIPTION
**Pull request by Shnoulle**
…ning about seed
Dev: set a seed if empty

### CODE REVIEW

**Comment by Shnoulle** [comment]
We can fix invalid seed too (badly VV import for example) or throw an error (or just log it …)

**Comment by olleharstedt** [comment]
Looks good?

**Comment by Shnoulle** [comment]
It work, the only potential issue : here https://github.com/LimeSurvey/LimeSurvey/blob/ad436aa43e8e5833825bde8ad39980738e0de249/application/libraries/MersenneTwister.php#L17 (current ls too) : if column don't exist.

I'm unsure we need https://github.com/LimeSurvey/LimeSurvey/blob/ad436aa43e8e5833825bde8ad39980738e0de249/application/libraries/MersenneTwister.php#L31

**Comment by Shnoulle** [comment]
PS : why ? : i assign to you, because you have already some bug on seed :). And you know best than me .

The question : what to do if seed is not set, and what to do if seed is invalid ( ' 1234 ` (see space : unsure it work) or `abcd`) ?

**Pull request merged**
