### PR TITLE
Fixed issue : 400, 404 show template unrelated to current template

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: Manage all know error page by Yii
Dev: copy message from Yii error page
Dev: move some 401/403/404 error to real error with header
Dev: I really think it's a bad idea to show admin email in default error page …

### CODE REVIEW

**Comment by LouisGac** [comment]
great!

**Comment by Shnoulle** [comment]
There are some question about debug > 1 / 2 superadmin/ not super admin etc …

See comment : https://github.com/LimeSurvey/LimeSurvey/pull/1089/files#diff-f5392477bcb7ace25c65e8bd7abd39e9R345 

(and currently travis have some issue …)

**Comment by Shnoulle** [comment]
Then , OK to merge this one ?

**Comment by Shnoulle** [comment]
Thank you,
If you have better idea for «When to show complete error» …

See the comments

**Pull request merged**
