### PR TITLE
Fixed issue #16166: Survey taking/editing uploaded pictures not showing up

### PR DESCRIPTION
**Pull request by tgurr**
Allow .htaccess to also work with apache 2.4 syntax.

### CODE REVIEW

**Comment by olleharstedt** [comment]
@Shnoulle Can you review, please?

**Comment by Shnoulle** [comment]
I don't have apache multiple version …

**Comment by Shnoulle** [comment]
(and currently use nginx …) check to have a apache 2.2 and a 2.4 …

**Comment by Shnoulle** [comment]
This one seems a hack : https://stackoverflow.com/a/15081790/2239406
Maybe add https://stackoverflow.com/a/20135157/2239406 before 

😕

**Comment by Shnoulle** [comment]
Let apache 2.2 compatibibility broke :) OK for this @olleharstedt 

See https://github.com/LimeSurvey/LimeSurvey/#minimal

**Comment by Shnoulle** [comment]
PS 

````
<FilesMatch "^fu_[a-z0-9]*$">
    Require all denied
</FilesMatch>
````

**Comment by Shnoulle** [comment]
For 3LTS too (?)

**Comment by tgurr** [comment]
I've updated the commit to include your suggestions about also including mod_version.

**Comment by olleharstedt** [comment]
ping @c-schmitz

**Comment by olleharstedt** [comment]
Thank you for contributing!

**Pull request merged**
