### PR TITLE
Fixed issue #18261: Simple statistics, 'Array (5 point choice)' dont show subquestions

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by olleharstedt** [comment]
Tested and reviewed by me.

**Comment by Jerome-Herbinet** [comment]
@gabrieljenik @olleharstedt is this PR supposed to solve this ? : https://bugs.limesurvey.org/view.php?id=13955

**Comment by gabrieljenik** [comment]
> @gabrieljenik @olleharstedt is this PR supposed to solve this ? : https://bugs.limesurvey.org/view.php?id=13955

Would have to get into the issue and test it to assure it fixes it completely, but yes, feels it could help (probably a lot)

Why? What do you think?
Want to keep discussion on 13955 ticket?

**Comment by Jerome-Herbinet** [comment]
I've not found how to create an account on the mantis tool ...

**Comment by gabrieljenik** [comment]
I think from here?
https://account.limesurvey.org/sign-up

**Comment by Jerome-Herbinet** [comment]
I already tried ; this is only an account to get access to SASS LimeSurvey :-(

**Comment by gabrieljenik** [comment]
By looking at this should be good for mantis as well.
https://community.limesurvey.org/bug-tracker/

**Pull request merged**
