### PR TITLE
Fixed issue #9591: Sometimes date_max / date_min validations for date/t...

### PR DESCRIPTION
**Pull request by gabrieljenik**
...ime questions doesn't allow to use the maximum date expected.

- Reformat expression held into date_max / date_min into "Y-m-d H:i" format, so comparison can be done among equals format.

### CODE REVIEW

**Comment by mfaber** [comment]
Will cause problems if someone enters a date > 2038 in min/max date. But at the end of unix time, the world wil probably seize to exist anyway. ;) Thanks for the fix!

**Comment by mfaber** [comment]
@gabrieljenik Could you please also add to 2.06 branch? Thanks!

**Comment by gabrieljenik** [comment]
One upside that I noticed is that now US users will be able to enter min_date / max_date in natural language.

**Comment by mfaber** [comment]
Yes, all the date formats correctly parsed by strtotime will work (YYYY-MM-DD, YYYY/MM/DD, DD.MM.YYYY, MM/DD/YYYY, DD-MM-YYYY).. :)

**Comment by gabrieljenik** [comment]
PR for v2.06: https://github.com/LimeSurvey/LimeSurvey/pull/299

**Pull request merged**
