### PR TITLE
Fixed issue #18602: When surveys are copied without copying attachments, attachment info is copied but not updated

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by kevin-foster-uk** [comment]
Its difficult to test this branch because email attachment import functionality is saving the data as serialised PHP but then the .lss export functionality is saving the data as JSON.

Do you need to merge the latest 5.x into this branch to get the recent changes from other PRs?

**Comment by gabrieljenik** [comment]
> Do you need to merge the latest 5.x into this branch to get the recent changes from other PRs?

Strange.
Isn't it already?

**Comment by gabrieljenik** [comment]
> Its difficult to test this branch because email attachment import functionality is saving the data as serialised PHP but then the .lss export functionality is saving the data as JSON.

Import saves inside LS as serialized, as it has always been. We changed how info is being stored, just the import and export format from serialized to json.

**Comment by kevin-foster-uk** [comment]
OK thanks for clarifying. 

One thing I did notice is that if you attempt to import a .lss file which contains JSON attachments to a LimeSurvey version which expects serialised data, you get a PHP error.

**Pull request merged**
