### PR TITLE
Fixed issue #15615: Mandatory multiple choice questions are not assigned a red background if not being answered

### PR DESCRIPTION
**Pull request by gabrieljenik**
Added new code on tip event handler for updating question-container, evaluating status of its tips and then add/remove the error class

### CODE REVIEW

**Comment by Shnoulle** [comment]
Like the move to function, no new event here , no ?

**Comment by gabrieljenik** [comment]
> Like the move to function, no new event here , no ?

Thought about new event. This seems easier. Do you see any upside on using events for that?

**Comment by Shnoulle** [comment]
You said «Added new event handler for question-container,» , i don't see a new event here. It was just a question. 

Since it's template-core : i already remove this in theme … My opinion : we must not have the same color for 'submitted' and not submitted errors :)

**Comment by gabrieljenik** [comment]
> You said «Added new event handler for question-container,» , i don't see a new event here. It was just a question.

Fixed description

> Since it's template-core : i already remove this in theme … My opinion : we must not have the same color for 'submitted' and not submitted errors :)

I don't understand sorry. You already have something on your theme which differentiates submitted and not submitted (dirty fields and non dirty fileds)?

**Comment by Shnoulle** [comment]
> I don't understand sorry. You already have something on your theme which differentiates submitted and not submitted (dirty fields and non dirty fileds)?

I just don't update wrapper with JS solution. Project is to add it, but must find times.

**Comment by cdorin93** [comment]
@gabrieljenik , could you please test why Travis is red? thanks!

**Comment by gabrieljenik** [comment]
I will

**Comment by gabrieljenik** [comment]
AutoCalcTest::testBasic() is erroring here:
`$this->assertEquals('Body Mass Index (BMI) is 25.308.', $bmi, $bmi);`

It shouldn't fail. Still, the comaprison is wrong! Is comparing the result with itself, not a calculated value.

About the other error RankingFilterHideShowTest::testRankingFilterShown, not sure why. 
We will go deeper into it.

**Comment by gabrieljenik** [comment]
We found the issue I think. We will push the fix.

**Review by eddylackmann — APPROVED** [review]

**Pull request merged**
