### PR TITLE
Update to PHPmailer 5.2.19

### PR DESCRIPTION
**Pull request by Jan-E**
@c-schmitz @tammoterhark See https://bugs.limesurvey.org/view.php?id=12020
AFAIK this is the necessary upgrade.

### CODE REVIEW

**Comment by Jan-E** [comment]
@Shnoulle could you check if this update is consistent with the previous PHPmailer update? See https://github.com/LimeSurvey/LimeSurvey/pull/452

**Comment by Jan-E** [comment]
BTW: I took the release tarball for 5.2.19 from https://github.com/PHPMailer/PHPMailer/releases, deleted the /examples, but updated the MD files from git head at https://github.com/PHPMailer/PHPMailer

git head is on par with 5.2.19, so feel free to use that in stead of the release tarball.

**Comment by lacrioque** [comment]
Thank you very much for your work.
Can you please use our correct commit message formatiing?
In this case the correct commit message would be "Fixed issue #12020: Critical Vulnerability in PHPMailer" 

We need othis formatting so sort the commit to the correct error report and to have our internal search and filter methods working. Thank you!

**Comment by Jan-E** [comment]
New PR: https://github.com/LimeSurvey/LimeSurvey/pull/615

**Pull request closed without merging**
