### PR TITLE
Features/spss export fix token attributes

### PR DESCRIPTION
**Pull request by clemens-tolboom**
The export SPSS syntax file contains quite some errors.

This PR tries to fix these by getting rid of local variable and adds a map for token field definition.

It still needs some work but I'd love to get some feedback on how to make this PR land.

### CODE REVIEW

**Comment by Aestu** [comment]
Probably you should create a pull request with just one commit and follow the commit message standards:

https://manual.limesurvey.org/Standard_for_Git_commit_messages

**Comment by Aestu** [comment]
You could create a bug in http://bugs.limesurvey.org to show the errors in SPSS syntax and make testing of your code easier. Afterwards, if you need some help, I could help you to put your changes in one commit.

**Comment by c-schmitz** [comment]
Hello Clemens,

can you describe what errors you did fix exactly? We would love to accept your patch but since you refactored some code (which is fine in general) it is hard to check what changed regarding that.
Let us know!

**Comment by c-schmitz** [comment]
@clemens-tolboom Feedback please?

**Comment by clemens-tolboom** [comment]
@c-schmitz + @Aestu sorry for the delay. I will add a new PR containing 1 commit + report on what is fixed next week.

**Comment by clemens-tolboom** [comment]
I close this in favor of https://github.com/LimeSurvey/LimeSurvey/pull/296

**Pull request closed without merging**
