### PR TITLE
Dev: disable account type buttons if global configuration is used

### PR DESCRIPTION
**Pull request by ViliusS**
Dev: It is still possible to click on the buttons, even though the labels are disabled, but at least this shows a clear indication to the user.

### CODE REVIEW

**Comment by Shnoulle** [comment]
disbaled is **not** supported by label
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

css issue, not js. Don't broke HTML please :)

**Comment by ViliusS** [comment]
How about now?

**Comment by Shnoulle** [comment]
Leave the attr disabled to the input maybe ;)

It work with class ? Maybe add class to all other lable (PS : **i didn't check** !)

**Comment by ViliusS** [comment]
The reason I've submitted the patch is that disabling the input didn't work. These buttons are constructed via <label> and CSS classes.

Now it works and is on par with "bounceaccountencryption" type below.

**Comment by Shnoulle** [comment]
> The reason I've submitted the patch is that disabling the input didn't work.

? Strange issue here … someone broke HTML before you ;)

**Comment by Shnoulle** [comment]
OK, got it : seems in 3 : label have class, but no update on radio :)

What i have in current 4.3.23  seems clear enough in global settings
Peek 03-11-2020 16-21

Here : it's for survey settings ?

**Comment by Shnoulle** [comment]
Near same aspect in Survey settings : in my opinion : it's clear enough

@cdorin93 ?

**Comment by Shnoulle** [comment]
In survey settings : seems button have already the disabled class … (but the text input didn't have good class)
Peek 03-11-2020 18-45

**Comment by ViliusS** [comment]
You are checking the wrong field. The patch is against bounceaddresstype, not the bounceaddressencryption.

**Comment by Shnoulle** [comment]
> The fix is for survey settings, not the global settings.

I don't know we can disable it … where can i get the page please ?

**Comment by Shnoulle** [comment]
OK !!!

 Server type  … finally i got it …

**Comment by Shnoulle** [comment]
Thank you and sorry for my misunderstanding ...

**Pull request merged**
