### PR TITLE
Fixed issue #11923: Obsolete files in 161118 

### PR DESCRIPTION
**Pull request by BertHankes**

### CODE REVIEW

**Comment by c-schmitz** [comment]
Please use proper commit messages - read up on https://manual.limesurvey.org/Standard_for_Git_commit_messages

**Comment by c-schmitz** [comment]
Unfortunately changing the title of the pull requestion does not change the commit itself. Please resubmit.

**Comment by BertHankes** [comment]
I closed and reopened . Hopefully this is the way to resubmit.

**Comment by BertHankes** [comment]
BTW: Denis said I should make a pull.. I merely signaled a sort of 'bug'.. So this fiddeling is costing me time too... So don't be to cross!

**Pull request closed without merging**
