### PR TITLE
Feature/user stats view

### PR DESCRIPTION
**Pull request by KRav007**
I saw this ugly template. I added the bootstrap classes and using the bem class naming.
If you confirm the naming, I could write a path for the templates and delete the old classes and ids

### CODE REVIEW

**Comment by Shnoulle** [comment]
Hi,

Think this one must be in [develop](https://github.com/LimeSurvey/LimeSurvey/tree/develop) + in the good directory : https://github.com/LimeSurvey/LimeSurvey/tree/develop/application/views/survey/frontpage + use more views ($statisticsoutput must use view too).

Something different : i really didn't understand why using row > col-sm-12. Using row > col-sm-X if you need : diferenet width for one row OR if you nhave multiple rows.

boostrpa don't NEED always row/col-sm-X

**Comment by Shnoulle** [comment]
See http://testing.sondages.pro/answershtml/index.php/statistics_user/282267?language=fr , started reworking on 'table' class. Don't remind when ... (and must use some views here ...)

**Comment by LouisGac** [comment]
I agree with Shnoulle, but this PR still improves the actual rendering of master.

**Comment by Shnoulle** [comment]
@LouisGac : you make the twig files ;) , need merging master in develop and develop in twig :/

**Comment by LouisGac** [comment]
I know... I will assume :'(

**Pull request merged**
