### PR TITLE
New Feature: User group grid view

### PR DESCRIPTION
**Pull request by zerwalter**
@LouisGac Please advise of any corrections

### CODE REVIEW

**Comment by LouisGac** [comment]
Again : it seems good to me. You're doing it right.

**Comment by LouisGac** [comment]
I confirm. Very good job.
Just : a confirmation for the delete action would be needed. 
a Bootstrap Modal would be perfect. 
Llet me know if you want to do it and need indication about how to.

**Comment by zerwalter** [comment]
Ok, I looked and the label set gridview needs a confirmation also. I will add for both and submit a new PR.

**Comment by LouisGac** [comment]
https://github.com/LimeSurvey/LimeSurvey/commit/8f44c92ce1e4a241177200e95741c70092451caa

**Comment by mfavetti** [comment]
Thanks for for taking care of the bug and leaving this comment. I reviewed the problem and the fix so I can learn for next time.

**Comment by LouisGac** [comment]
I was sure it will interest you.

**Pull request merged**
