### PR TITLE
Fixed issue #19232: Missing cssframework default values for survey th…

### PR DESCRIPTION
**Pull request by olleharstedt**

### CODE REVIEW

**Comment by Shnoulle** [comment]
In 3.X : the default was boostrap.css, empty mean boostrap.css, then variation “replace” boostrap.css

**Comment by olleharstedt** [comment]
> In 3.X : the default was boostrap.css, empty mean boostrap.css, then variation “replace” boostrap.css

Problem is, default is not "empty" now. If you reset the fruity theme, you get a JSON object saved instead of a simple string, and survey export breaks... :no_mouth:

**Comment by Shnoulle** [comment]
Related to (array) json_decode ?

**Comment by olleharstedt** [comment]
Not completely sure :stuck_out_tongue_closed_eyes:

**Comment by Shnoulle** [comment]
Else: in 5 : saved in cssframework_css `{"replace":[["css/bootstrap.css","css/variations/slate.min.css"]]}` but set as flatly.min.css whene reset (don't know how …)

**Review by Shnoulle — APPROVED** [review]

**Pull request merged**
