### PR TITLE
Remove MySQL specific quotes from a survey criteria

### PR DESCRIPTION
**Pull request by gwn**
Breaks Postgres if we don't.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Maybe must replace by Yii [quoteColumnName](http://www.yiiframework.com/doc/api/1.1/CDbSchema#quoteColumnName-detail) ?

**Comment by TonisOrmisson** [comment]
@Shnoulle No. Yii will do it anyway after. The way @gwn did is how it should be.

**Comment by TonisOrmisson** [comment]
@Shnoulle No. Yii will do it anyway after. The way @gwn did is how it should be.

**Comment by Shnoulle** [comment]
@TonisOrmisson : Thanks, one question why Yii did it here but not on other part ? In Quota count management for example :).

**Comment by TonisOrmisson** [comment]
@Shnoulle anything going through the `CACtiveRecord->query()` will get the quoting done by yii. 
Im not sure about the Quota count. Maybe there is raw SQL composed there?

**Comment by Shnoulle** [comment]
No raw SQL : https://github.com/LimeSurvey/LimeSurvey/blob/master/application/models/Quota.php#L174 

Currently in model, before in common or frontend helper. Started the patch without the quoteColumnName : bug report : broke on mssql, fix the patch

**Comment by TonisOrmisson** [comment]
Seems to be unnceccessary. Yii will do it anyway after

**Comment by TonisOrmisson** [comment]
ok I was rechecking that to be sure and seems that bit everything gets quoted afterall. in this case also yii will not quote it

**Pull request merged**
