### PR TITLE
Dev 17262: Create new getQuestionAttributes() endpoint for Limesurvey API which is used by plugins

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by Shnoulle** [comment]
New feature ? And need an API version update => for dev.

New API feature => need to be know with a simple float API checker.

**Comment by Shnoulle** [comment]
Else : great ! 

:+1:  :heart:

**Comment by gabrieljenik** [comment]
> New feature ? And need an API version update => for dev.
> 
> New API feature => need to be know with a simple float API checker.

Sorry, can you explain both a little bit further?

**Comment by Shnoulle** [comment]
I mean : it's an API.

If a plugin want to check this API function : need to to test API when activate.

Then : App()->getconfig('versionnumber') > X.Y See https://semver.org/ .

I know i currently use verison_compare in my plugin because some «PATCH» broke API or add feature to API. 
But maybe in 5.Y or 6.Y or … we can use floatval … 

Or better : have a LimeSurvey::API constant to check …

**Comment by gabrieljenik** [comment]
oh ok. I get it.
We can add something on the versions.php file.
Then the API can read it and show it out on method

**Comment by Shnoulle** [comment]
@olleharstedt : nee version minor(feature) update here. In my opinion.

Alternative solution : create multiple API version :+1: 

- SurveyTheme API verison
- QuestionTheme API version
- Plugin API version

but : i think it's best if we use only a single API nulber

**Comment by olleharstedt** [comment]
phpunit just aborts after green bar test. Weird.

**Comment by olleharstedt** [comment]
Maybe try to run only the newly added test with debug = 2?

**Comment by olleharstedt** [comment]
> @olleharstedt : nee version minor(feature) update here. In my opinion.

Sure.

**Comment by Shnoulle** [comment]
* need

**Pull request merged**
