### PR TITLE
Fixed issue #17270: Print statistics take a lot of page

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #17270: Print statistics take a lot of page
Dev: remove a lot of body.onStatistics
Dev: remove usage of :not(.printable) : hide more than needed
Dev: Still have issue, but really cleaner

### CODE REVIEW

**Comment by Shnoulle** [comment]
[LimeSurvey.pdf](https://github.com/LimeSurvey/LimeSurvey/files/6478509/LimeSurvey.pdf)

Still have an issue with graph not done.

I hide the legend : because background color are not printed …

**Comment by olleharstedt** [comment]
Looks very nice :)

**Comment by olleharstedt** [comment]
I'd prefer seeing it in master, tho...

**Comment by Shnoulle** [comment]
master didn't have the same issue .

And : it's needed for LTS too.

**Comment by Shnoulle** [comment]
Fixed complete.

**Pull request merged**
