### PR TITLE
Fixed issue #16669: getQuestionAttributes function don't get the plugins attribute

### PR DESCRIPTION
**Pull request by gabrieljenik**
Picking up plugin attributes and merging them with theme and std ones.

### CODE REVIEW

**Comment by olleharstedt** [comment]
This has the same issue as before - the plugin is run from two different places. Maybe it's the only way. Still I wonder if it's possible to use ONLY the method "getQuestionThemeAttributeValues" to fetch question theme attributes.

**Comment by gabrieljenik** [comment]
> Or, is it possible to have ONE function to get question theme attributes (together with their values, if any)? And fire the event there?

Why do you wan't fir it from there? I was actually thinking about removing it from there.
Let's review on a call?

**Comment by olleharstedt** [comment]
Sure, ping me tomorrow.

**Comment by gabrieljenik** [comment]
After call, this ticket was created: https://bugs.limesurvey.org/view.php?id=17242

**Comment by olleharstedt** [comment]
Merged after deciding to continue with more clean-up PRs.

Ticket for unit-test: https://bugs.limesurvey.org/view.php?id=17241

Duplicate ticket for clean-up: https://bugs.limesurvey.org/view.php?id=17240

**Comment by Shnoulle** [comment]
@olleharstedt About issue with https://manual.limesurvey.org/NewQuestionAttributes 

For example : 
````
        'inputtype' => 'switch',
        'options'   => array(
          0 => gT('No'),
          1 => gT('Yes'),
        ),
````
Nothing is shown

````
        'inputtype'=>'singleselect',
        'options'=>array(
          'afteranswer'=>$this->_translate("The script is inserted just after answer part."),
          CClientScript::POS_HEAD=>$this->_translate("The script is inserted in the head section right before the title element (POS_HEAD)."),
          CClientScript::POS_BEGIN=>$this->_translate("The script is inserted at the beginning of the body section (POS_BEGIN)."),
          CClientScript::POS_END=>$this->_translate("The script is inserted at the end of the body section (POS_END)."),
          CClientScript::POS_LOAD=>$this->_translate("The script is inserted in the window.onload() function (POS_LOAD)."),
          CClientScript::POS_READY=>$this->_translate("The script is inserted in the jQuery's ready function (POS_READY)."),
        ),
````
Show a dropdown with 'array' (and break with debug)

Report as issue or API upgrade need updating manual ?

**Comment by Shnoulle** [comment]
Oh no … ok : before 4.5.0 : need 
````
          'option'=> array(
            array('value'=>0, 'text'=> gT("No")),
            array('value'=>1, 'text'=> gT("Yes")),
          ),
````

for 4.5 : come back with compatibility of 3.X …

Still some issue with help and with switch

**Comment by olleharstedt** [comment]
Report everything, assign to Gabriel. :) :partying_face:

**Comment by olleharstedt** [comment]
Or tell me which function that needs unit-test to stay correct.

**Pull request merged**
