### PR TITLE
Fixed issue #17762: vulnerable verson of jQuery used in devbridge-autocomplete

### PR DESCRIPTION
**Pull request by DenisChenu**
Dev: move to minimal version, update to 1.4.11

### CODE REVIEW

**Comment by Shnoulle** [comment]
Seem only used in map currently (grep on application)

**Comment by Shnoulle** [comment]
How this can break on endurl ?

**Comment by Shnoulle** [comment]
But more : this test can not work : auto redirect work only on activated survey

**Comment by Shnoulle** [comment]
@gabrieljenik : you find any relation between _End Url Redirect (ls\tests\EndUrlRedirect)_ and _autocomplete_ ?

**Review by gabrieljenik — APPROVED** [review]
Seems good to me. This is a lib update

**Comment by Shnoulle** [comment]
I really don't understand why there are an issue in this commit about EndUrlRedirect … still upset

**Comment by olleharstedt** [comment]
> I really don't understand why there are an issue in this commit about EndUrlRedirect … still upset

Did you try to run the test manually with your changes? Maybe JS error in console?

**Comment by Shnoulle** [comment]
> 
> Did you try to run the test manually with your changes? Maybe JS error in console?

Yes, don't found any issue :/

**Comment by Shnoulle** [comment]
> > Did you try to run the test manually with your changes? Maybe JS error in console?
> 
> Yes, don't found any issue :/

In master, without any update : if survey is not activated : there are no redirection … survey must be activated to have the redirection.

**Comment by olleharstedt** [comment]
OK, someone else have to test too, then.

**Comment by gabrieljenik** [comment]
Will review...

**Comment by gabrieljenik** [comment]
Have you tried adding a body_dump() or similar to see the screen before failing the test?

**Comment by Shnoulle** [comment]
Sh***!

```
shnoulle@debian:~/public_html$ php -v
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies
shnoulle@debian:~/public_html$ git branch
* Shnoulle-develop_devbridge-autocomplete
  develop
  master
shnoulle@debian:~/public_html$ DOMAIN=localhost ./third_party/bin/phpunit ./tests/functional/frontend/EndUrlRedirectTest.php 
PHPUnit 8.5.21 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 9.73 seconds, Memory: 26.00 MB

OK (2 tests, 2 assertions)
shnoulle@debian:~/public_html$ grep version third_party/devbridge-autocomplete/package.json 
  "version": "1.4.11",
```

**Comment by Shnoulle** [comment]
Re-run all jobs : issue fixed.

Google broken when it's done ? 2 times ?

**Comment by gabrieljenik** [comment]
> Re-run all jobs : issue fixed.

So what happened? What was wrong? version issue?

**Comment by Shnoulle** [comment]
> > Re-run all jobs : issue fixed.
> 
> So what happened? What was wrong? version issue?

Google broken ?

**Pull request merged**
