### PR TITLE
Feature: Add file attachement function for RPC method

### PR DESCRIPTION
**Pull request by sieutruc**
Hello,

I have created a mail template with a file attachment.
When i send an invitation email via the web interface to an user, that user receives a mail with the attached file.

But when i use the JSON-RPC method, the attached file is missing in the client 's side.

This patch adds the feature that is missing when using the JSON-RPC method.

Truc

### CODE REVIEW

**Comment by SamMousa** [comment]
@sieutruc I am not sure relevance checking will work properly in this case.

The relevance equations apply to mails send on completion (at that point there is a certain state in EM, ie the response is loaded). Via RPC this is not the case and relevance equations will not be evaluated properly.

Have you tested this?

**Comment by sieutruc** [comment]
Actually, i don't know exactly how the line "LimeExpressionManager::singleton()>ProcessRelevance($aAttachment['relevance']))" works

But i have tested and it works without any problem.

**Comment by SamMousa** [comment]
With relevance equations or without?

**Comment by sieutruc** [comment]
With relevance equations, i have tested and it works in 2 cases, by sending an invitation mail or a reminder mail (one attachment or several attachments). If you think there'd be a special case that could produce a problem, i will test it for you.

**Comment by SamMousa** [comment]
Hmm, well the code in the original location loads the token information, you don't. So any relevance based on a token property will not work.

For example try adding 2 attachments, 1 called English.pdf; and 1 called Dutch.pdf.

Now configure a relevance equation for each so that tokens with their language set to dutch will get Dutch.pdf and all other people get English.pdf

That will not work in your code.

Check: https://github.com/LimeSurvey/LimeSurvey/blob/master/application/controllers/admin/tokens.php#L1467

**Comment by sieutruc** [comment]
I have updated my patch and i tested it. Do you have any remark on this patch ?

**Comment by SamMousa** [comment]
No, looks good to me. @c-schmitz please decide if you want this in master or 2.06 or where you want it to go!

**Comment by sieutruc** [comment]
Can you tell me when the patch will be applied to the current version ? (master or 2.06 )

Truc

**Comment by sieutruc** [comment]
is this patch integrated to the later version ?

**Comment by SamMousa** [comment]
Hi sieutruc, 
This is a new feature, and I'm afraid LS2.06 is currently feature locked.

Please reopen this pull request for the develop branch. Note that develop is currently not ready for general use, but we can keep this PR open as a reminder, even if it will not work for LS3 without some changes.

**Pull request closed without merging**
