### PR TITLE
Fixed issue #17972: events are dispatched if the plugin is deactivated

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: Add param to load init
Dev: set it to false in PluginManagerController in all case
Dev: active plugin are loaded via PluginManager->loadPlugins
Dev: use plugin model active status in PluginManager

### CODE REVIEW

**Comment by Shnoulle** [comment]
Same than merged in 5.X ;)

**Review by gabrieljenik — APPROVED** [review]
Code looks good. Haven't tested it

**Comment by gabrieljenik** [comment]
Master PR has already been pushed. I think this could be as well, right?

**Comment by olleharstedt** [comment]
> Master PR has already been pushed. I think this could be as well, right? @olleharstedt @c-schmitz ?

If it's the same patch? Sure.

**Pull request merged**
