### PR TITLE
Revert Question Group Editor

### PR DESCRIPTION
**Pull request by gabrieljenik**
Reverted Vue-JS from View, Add, Edit

### CODE REVIEW

**Comment by thedirtypanda** [comment]
I found some issues:

1. if you press at 'create group' then the view will be rendered. But there is a heading called 'Description'. It's not possible to add any description (at this point) to the group (there is no ckeditor). Please hide the description at this stage. After saving enable the visibility for the description again.

2. What happens to the topbar? Dorin told me that you need help.

**Comment by gabrieljenik** [comment]
> 1. if you press at 'create group' then the view will be rendered. But there is a heading called 'Description'. It's not possible to add any description (at this point) to the group (there is no ckeditor). Please hide the description at this stage. After saving enable the visibility for the description again.

Will review.

> 2. What happens to the topbar? Dorin told me that you need help.

We just didn't spend too much time on it as we are not sure if it will be vue-js based or PHP based or how it will be the basic structure for setting up in the future. So looks weird now. Any updates on how topbar will be setup? Reverted or kept in php?

**Comment by gabrieljenik** [comment]
Added a test and a review for languages

**Comment by thedirtypanda** [comment]
I prefer to stick to vue JS for now. In the future it might be changing. The problem is, that we want to release fast and if we change the top bar now, it will take a while, cause the top bar will affect every page in the admin views.

If you want we can discuss this at discord, together with the other developers.

**Comment by gabrieljenik** [comment]
> I prefer to stick to vue JS for now. In the future it might be changing. The problem is, that we want to release fast and if we change the top bar now, it will take a while, cause the top bar will affect every page in the admin views.
> 
> If you want we can discuss this at discord, together with the other developers.

No worries. If we will be keeping the vueJs toolbars then we will follow it.

**Comment by gabrieljenik** [comment]
@thedirtypanda Please see latest commits.

**Comment by cdorin93** [comment]
hey @thedirtypanda , have time to take a look today at this one?

**Pull request merged**
