### PR TITLE
New feature #17835: Add custom token attributes to Response details screen

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by Shnoulle** [comment]
I have some survey with more than 60 token attributes … need a system to disable this «feature»

**Comment by Shnoulle** [comment]
No issue in code, but need discussion

**Review by Shnoulle — APPROVED** [review]

**Comment by olleharstedt** [comment]
@Shnoulle Status of discussion?

**Comment by Shnoulle** [comment]
https://bugs.limesurvey.org/view.php?id=17835#c68822

By @maziminke : 

> [@gabrieljenik](https://bugs.limesurvey.org/view_user_page.php?id=25282) it should be "single response detailed view". Not sure if adding this to the "all responses" tabular overview makes sense.

I really don't know. For me it need to be hidden by default OR have a "Save status on column" to be shown.
https://bugs.limesurvey.org/view.php?id=17835#c68812

**Comment by gabrieljenik** [comment]
> I really don't know. For me it need to be hidden by default OR have a "Save status on column" to be shown.
> https://bugs.limesurvey.org/view.php?id=17835#c68812

https://bugs.limesurvey.org/view.php?id=17835#c68823
Why? This is for the detailed view which has only 2columns and a long tail (depending on the questions and token attributes)

**Comment by Shnoulle** [comment]
>  Why? This is for the detailed view which has only 2columns and a long tail (depending on the questions and token attributes)

https://bugs.limesurvey.org/view.php?id=17835#c68812

> I have survey with more than 60 token attribute, i really dislike to have it each time i browse response.

But right : this browse response is awful today, really can not be used when need something, then we can add broker and broker …
Until we don't have a really usable browse response system with clean filter + clean overflow …

**Comment by gabrieljenik** [comment]
This ticket only concerns the individual response view, not the grid with multiple responses.

**Comment by Shnoulle** [comment]
Argl … original issue …

OK for this one (needed)

**Review by Shnoulle — APPROVED** [review]

**Comment by maziminke** [comment]
@glimz / @gabrieljenik Can we merge this one and make it available at the next 3.x and 5.x release?

**Comment by gabrieljenik** [comment]
@maziminke Not up to me. Sorry

**Comment by Shnoulle** [comment]
@olleharstedt i can merge ? Who merge now ?

**Comment by olleharstedt** [comment]
> @olleharstedt i can merge ? Who merge now ?

Ehm, yes, if the PR is both tested and code reviewed, you can probably merge.

**Comment by olleharstedt** [comment]
Did it now.

Does the manual need to be updated?

**Pull request merged**
