### PR TITLE
Fixed issue #16154: Not all files imported with custom question theme

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by gabrieljenik** [comment]
Tested it OK!
image

**Comment by Shnoulle** [comment]
The question is : did we need allow upload such file ? It's sample, to be imported separately.

**Comment by Shnoulle** [comment]
> The question is : did we need allow upload such file ? It's sample, to be imported separately.

@c-schmitz you advice here ? It's not really an issue , no ?

**Comment by gabrieljenik** [comment]
Why shouldn't we?

**Comment by Shnoulle** [comment]
> Why shouldn't we?

Not needed, not used by QuestionTheme, not usuable by QuestionTheme, no reason to have it uploaded.

**Comment by gabrieljenik** [comment]
No reason to limit it either... maybe there will come a QuestionTheme that uses it?
It is part of a deliverable and usually the deliverable is what it is uploaded as it is simple for the user and hence or the growth.

**Comment by Shnoulle** [comment]
> maybe there will come a QuestionTheme that uses it?

tell me how … 

> It is part of a deliverable and usually the deliverable

More part of manual, documentation in my opinion.

**Comment by gabrieljenik** [comment]
> More part of manual, documentation in my opinion.

Isn't that part of a delivberable?
What's wrong in keeping documentation close to source? (or levaing that as an option to the developer)

**Comment by Shnoulle** [comment]
OK : answered by Tony : via Li!meStore : no way to distribute lss except like that.

**Pull request merged**
