### PR TITLE
Fixed issue #13936: Bootswatch inherit everyting to no: deactivate container

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: just add the option from vanilla in bootswatch
Dev: quick fix since it was always reproducible

### CODE REVIEW

**Comment by Shnoulle** [comment]
@LouisGac  still reproduce …
No way to disable ajax mode without disabling container in boostrap

https://framadrop.org/r/DnvvM5JBo1#a0Hd1jshANXgg71An7JSPMf6UJqaATiX+SndwS0W8AI=
https://framadrop.org/r/sD7_f_O3Rl#C64eshtk0GPGI7zaB1IE3R2BpSI8EzqWge12M8x3+v0=

**Comment by Shnoulle** [comment]
Not fixed currently …

**Comment by dominikvitt** [comment]
Is this issue still relevant for LS3?
Does this PR fix it?

**Comment by Shnoulle** [comment]
@dominikvitt : last time i check : yes (Februrary the 8). 

https://bugs.limesurvey.org/view.php?id=13936#c48749 , screencast is dead … i sedn one on issue after reproduct.

**Comment by Shnoulle** [comment]
Screencast : https://bugs.limesurvey.org/view.php?id=13936#c51725

**Pull request merged**
