### PR TITLE
Dev #T636: Not clear how to edit a question comparing LS3 with LS4

### PR DESCRIPTION
**Pull request by gabrieljenik**
As a user it's not clear how I can EDIT a question.

In LS 3 the EDIT button was on the TOP BAR navigation. 
In LS 4 we as it looks like  have 2 buttons outside TOP BAR navigation on right side. 

This makes it difficult for the end user to understand how to edit a question in comparison with LS 3.

QUESTION SUMMARY:
1  Get the EDIT button back in top bar and behave like clicking  on Question Editor selector/tab
2. Remove the Question overview/Question editor tabs. From the standard buttons:
Save/Save & close/Close  - Save & close/Close direct the user back to Overview.

Edits on Question Summary page:
1. Question overview  --> Delete
2. Question Editor = Edit - Primary
3. Group following buttons into Tools dropdown:
a. Check logic
b. Condition designer
c. Edit default awnswers

EDIT QUESTION :
1. Import question: This button does not belong here its part of the create process - Remove.

GROUP SUMMARY
1. Question Group Editor = Edit question group - Green
2. Delete current group = Delete question group
3. Export this question group = Export question group
4. Check logic for current question group = Check question group logic

### CODE REVIEW

**Comment by Shnoulle** [comment]
Screenshot ?

**Comment by gabrieljenik** [comment]
image

**Comment by Shnoulle** [comment]
Really better !

Did you keep direct editor mode ?
Capture d’écran_2021-05-18_08-41-33

I try to find time to checkout and test before this afternoon :+1:

**Comment by Shnoulle** [comment]
OK : directly Show editor mode still active. 

Some possible improvement or remark
- Block : Set select to dropdown (User preference) : Activated survey allow update of Question type  (an **no PHP control** issue must be reported separately.)
- Partial block : Close and Save and close **force** Question summary (when Show editor mode by default is ON) : this is needed for some tools like delete;, copy etc ....
- Improve : The delete button is really big, why not in tool ? It mus not be used a lot. 
- Improve : A good plugin idea : extend Tools menu (like Survey tool menu)

**Review by Shnoulle — CHANGES_REQUESTED** [review]
User preference issues

Issue that must be fixed before merge 
- Set select to dropdown (User preference) : Activated survey allow update of Question type (an no PHP control issue must be reported separately.)

Issue that must be fixed before release 
- Close and Save and close force Question summary (when Show editor mode by default is ON) : this is needed for some tools like delete;, copy etc ....

**Comment by olleharstedt** [comment]
You could do "Close" without a page reload, no? Just go to question overview again.

**Comment by Shnoulle** [comment]
> You could do "Close" without a page reload, no? Just go to question overview again.

Set User settings to _Show editor mode by default_ to ON. Close reopen Question edit.

**Comment by c-schmitz** [comment]
The edit button should not be green and should be right of the preview buttons.

**Comment by c-schmitz** [comment]
The delete button should be the very rightr button of the left button group

**Comment by Shnoulle** [comment]
> The edit button should not be green and should be right of the preview buttons.

I really think it's best with a specific color and the last one at right.

**Comment by gabrieljenik** [comment]
> You could do "Close" without a page reload, no? Just go to question overview again.

Yes, but the changes done on the editor will still be there and could lead to confusions if going back and forth.
Ex: 
1 - Change Qcode
2 - Go to Overview
3 - Got editor.
4 - Change Quesiton Test
5 - Save.
6 - Qcode is "unexpectedly" (?) changed as well.

Not sure if that could be a confusing situation.
But by reloading, we just avoid it.

Thoughts?

**Comment by c-schmitz** [comment]
> 
> 
> > The edit button should not be green and should be right of the preview buttons.
> 
> I really think it's best with a specific color and the last one at right.

The 'Delete' button would be in the same position and color as  the 'Cancel' button.
The 'Edit' button would be in the same position and color as the 'Save' button.

I can tell you that is a very bad design decision. This is confusing and might lead to data loss.

**Comment by Shnoulle** [comment]
> > You could do "Close" without a page reload, no? Just go to question overview again.
> 
> Yes, but the changes done on the editor will still be there and could lead to confusions if going back and forth.

Not with Show editor mode by default to ON 

Peek 18-05-2021 14-26

**Comment by Shnoulle** [comment]
> Dialog buttons (Save/Save&close/Close) and action buttons (Edit/Delete) need to have a clear distinction.

But why you want to remove the primary color from Edit ? I really think it's better.

I dislike the Delete just near the Edit

**Comment by c-schmitz** [comment]
> But why you want to remove the primary color from Edit ? I really think it's better.
> 
> I dislike the Delete just near the Edit

Ok, changed my message. Primary color is okay for me, just not the positioning.

**Comment by Shnoulle** [comment]
For information : i still search where is the Add question button in 3.X … even after create 20 questions …

**Comment by Shnoulle** [comment]
Why not Edit 1st button then ? 

Edit is used a lot more than Preview : it must be the primary action, the most easy to find (in my opion).

Button importance order (my opinion)

1. Edit
2. Create a new
3. Preview question
4.  set subquestion and set answers (i know this button are move at the same place than "Statistic graph type …")
5. condition, Default answers … 
6. Preview group, copy, export …
7.

**Comment by olleharstedt** [comment]
Make it's the same as in question group, too...

**Comment by gabrieljenik** [comment]
> * Set select to dropdown (User preference) : Activated survey allow update of Question type (an no PHP control issue must be reported separately.)

Can you elaborate a bit more?

**Comment by Shnoulle** [comment]
> > * Set select to dropdown (User preference) : Activated survey allow update of Question type (an no PHP control issue must be reported separately.)
> 
> Can you elaborate a bit more?

1. Activate a sample survey with a short text question
2. Set _Question type selector_ to simple is user preferences (this settings is really needed : really more quick than the other one)
3. Edit your question : set to array …
4. Save 

Peek 18-05-2021 17-09

Then 2 issues here

1. Related to this commit : dropdown must be readonly
2. Not related to this commit : never trust the user data: the control must be done on server side (by the Question model ?) : new issue to report.

**Comment by gabrieljenik** [comment]
> Related to this commit : dropdown must be readonly

I think it is a separate bug too. This commit is mostly about buttons.

**Comment by gabrieljenik** [comment]
I think all (or most) of the changes requested were implemented. Ready for re-review.
Let me know what you think.

Thanks

**Comment by Shnoulle** [comment]
> > Related to this commit : dropdown must be readonly
> 
> I think it is a separate bug too. This commit is mostly about buttons.

Confirm. Seems report need to be done

**Review by Shnoulle — APPROVED** [review]
It's OK now :).

**Pull request merged**
