### PR TITLE
Adds PostgreSQL 12 compatibility

### PR DESCRIPTION
**Pull request by mwehr**
Fixed issue # : Removed g_attrdef.adsrc in PostgreSQL 12
New feature # : PostgreSQL 12 compatibility
Changed feature # : use pg_get_expr() as a replacement
Dev:
Dev:

### CODE REVIEW

**Comment by c-schmitz** [comment]
Is this proposed change backward compatible - if yes down to which version does this work?

**Comment by mwehr** [comment]
According to the docs "pg_get_expr()" is supported since 7.4.
https://www.postgresql.org/docs/7.4/functions-misc.html

**Comment by c-schmitz** [comment]
Thank you!

**Comment by barto2932** [comment]
I have the same problem with LimeSurvey. I migrated to Postgresql 13

I have added compatibility by modifying the file and restarting Apache but the same error continues to appear.

"CDbCommand failed to execute the SQL statement: SQLSTATE[42703]: Undefined column: 7 ERROR: column d.adsrc does not exit
LINE 1: ...ER(format_type(a.atttypid, a.atttypmod)) AS type, d.adsrc, a..."

Is there anything more to do to make the change take good?

**Pull request merged**
