### PR TITLE
Fixed issue #15690: User with XSS enable can add/update scripts

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: Add 2 function : one for XSS and one for script in LSWebUser
Dev: The 1st commit is the needed action, 2nd commit : just the view

### CODE REVIEW

**Comment by Shnoulle** [comment]
I got it in rules \o/

**Comment by olleharstedt** [comment]
Well, now I can't test it, because I can't get the damn script text field to show.

1. New user
2. New survey
3. My account -> show script field: yes
4. Edit question
5. Still no script field

What am I missing?

**Comment by Shnoulle** [comment]
> What am I missing?

XSS disable for simple user ?
And maybe disable this option when XSS is enable for user ?

PS : checking with superadmin : i try to hide scripts : still shown …

**Comment by Shnoulle** [comment]
PS : in you fork : script still show to user as editable even if they don't have the right.

If you want same : 1st commit do it. 2n,d commit only disable the script edit part.

**Comment by olleharstedt** [comment]
image

image

**Comment by olleharstedt** [comment]
Oh, you hide the field now...

**Comment by Shnoulle** [comment]
I hide the edit field if user can not edit.

But let me check

**Comment by Shnoulle** [comment]
It's OK with simple user, XSS disable : script are shown and editable

**Comment by olleharstedt** [comment]
Well, I can't test the validator unless the field is visible. :) I'm hacking it to test.

**Comment by olleharstedt** [comment]
OK, works, but I'd prefer if a message was shown to the user. "Not allowed to edit script" instead of just hiding it, because it's set shown = yes in the profile.

**Comment by Shnoulle** [comment]
…  
It's must be in User settings …

And … really … asking more and more and more form external … But [LS team can do anything](https://github.com/LimeSurvey/LimeSurvey/commit/1eee6cf2833261dcd020bac974b154f34750fa27) ?

**Comment by Shnoulle** [comment]
Your fork : https://github.com/LimeSurvey/LimeSurvey/tree/bug/15690-user-with-xss-filter-enabled-can-add-script

Use see script, can think it can be updated, try to update and … nothings happen …

**Comment by Shnoulle** [comment]
You prefer i revert https://github.com/LimeSurvey/LimeSurvey/pull/1364/commits/1924ea89b950d49f64b69c42de745c43e8a7e282 ?

Then user see script but when save : script is resetted (like XSS system)

**Comment by olleharstedt** [comment]
Urgh. I'll merge this and then revert 1924ea8 manually. Let's discuss later about marking script field read-only, we can do it in the office.

**Comment by Shnoulle** [comment]
@olleharstedt : wait for "text information" my 2 other pull request

1. Global GUI : scriptAllowUpdate follow XSS : yes/no
2. PHP : xss for superadmin

**Comment by Shnoulle** [comment]
And i do a 

3. Add information about all of this in UserSettings and Question edit/preview when all it done

**Comment by olleharstedt** [comment]
Issue here: https://bugs.limesurvey.org/view.php?id=15702

**Pull request merged**
