### PR TITLE
New feature #14414: Theme need more url than image

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: adding templateRessourceUrl TWIG function
Dev: need sanitize, but maybe better sanitize in getTemplateForRessource

### CODE REVIEW

**Comment by Shnoulle** [comment]
@LouisGac i know , no new feature in 3.X, but clearly : all usage of specific font in theme is broken now (except plugin to create package).

There are no way to create a package in config.xml or twig, right ?

**Comment by Shnoulle** [comment]
Ready now, since added filename sanitizer

**Comment by tammoterhark** [comment]
If we consistently want to use English, "ressource" should be changed to "resource".

**Comment by Shnoulle** [comment]
Seems i'm not the 1st one : https://github.com/LimeSurvey/LimeSurvey/commit/d7cae995ec6ece2ea28cf51c9f66af12544146dc French Powa ;)

**Comment by Shnoulle** [comment]
1. Here this function is a pull request, not in master. It's a feature, then … officialy can not be in master.
2. There are no twig function in manual currently, no information about twig etc …
3. https://bugs.limesurvey.org/view.php?id=14502

**Comment by dominikvitt** [comment]
@Shnoulle: can you move this to develop branch?

**Comment by Shnoulle** [comment]
> @LouisGac i know , no new feature in 3.X, but clearly : all usage of specific font in theme is broken now (except plugin to create package). 

Yes OK, but … please, answer more quickly on such question … please … 😿

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/commit/150c4a18adc7a837f8c6a20909b18d740aacbcde

**Pull request closed without merging**
