### PR TITLE
Fixed issue #18906: Unable to fix or edit survey with UpperCase templ…

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #18906: Unable to fix or edit survey with UpperCase template name
Dev: set to existing directory/folder

### CODE REVIEW

**Comment by Shnoulle** [comment]
An alterantive solution are check if templatename == templete->folder

`if (is_object($oTemplate) && $oTemplate->checkTemplate() && self::checkTemplateXML($oTemplate->folder) && $oTemplate->folder == $sTemplateName) {`

But this one are in https://bugs.limesurvey.org/view.php?id=18907 …
Currently : just fix broken import.

**Comment by Shnoulle** [comment]
Here : i set uppercase to UpperCase if needed. Aletrnative solutuion uppercase reset to default template.

**Comment by Shnoulle** [comment]
@ptelu can we know why you close this PR ?

We can discuss on te way to fix , but we **NEED** a fix ....

**Comment by ptelu** [comment]
> 

Hey this wasnt intentionally closed, the branch attached to this PR cause issue when trying to update local git environments, thats why i renamed the branch from "bug./5X_18906_UppercaseTemplateImport" to "bug/5X_18906_UppercaseTemplateImport".  I restored everything now, but please update the branch as soon as you can. Both branches exist only difference is naming feel free to delete it. Try not to use "." in the names.

**Comment by Shnoulle** [comment]
Oh i add a dot after bug ?

Sorry ....

**Pull request closed without merging**
