### PR TITLE
Fixed issue #15873: setVariableExpressionEnd have lack of system to udate question part

### PR DESCRIPTION
**Pull request by Shnoulle**
- Add questionSeq2relevance in set / get
- plugin have all they can have but .... not really stable since EM must be rewritten
- **but** EM is same since years now ....

### CODE REVIEW

**Comment by Shnoulle** [comment]
Quickest working system, allow plugin a **lot** of things but we must inform is NOT API stable :) ([already updated manual](https://manual.limesurvey.org/SetVariableExpressionEnd#Some_detail_of_knowVars))

**Comment by Shnoulle** [comment]
@olleharstedt this one is 

1. Allow plugin to do anything
2. Didn't update anything in Expression manager system and file
3. Plugin dev must know EM a lot .... but they can really do what they want (when survey start, maybe after with some https://github.com/LimeSurvey/LimeSurvey/blob/f1a0bd2b8f151b5d193440105459ba946edb470c/application/helpers/expressions/em_manager_helper.php#L743 
4. But we can not give any warranty of the stability of `knowVars` and `questionSeq2relevance`. See the alert on https://manual.limesurvey.org/SetVariableExpressionEnd#Possible_output

**Comment by olleharstedt** [comment]
OK, cool. However small, since this commit adds new data to the event object, it should preferably be in develop branch. See release schedule for details.

**Comment by Shnoulle** [comment]
OK update branch

Other pull request are her e: https://github.com/LimeSurvey/LimeSurvey/pull/1393 but iu think we must rework on ExpressionScript before offering a clean API to update it , no ?

**Comment by olleharstedt** [comment]
> OK update branch

Thanks!

About the other fix, have to read more. Tomorrow. Perhaps... If I have time. :(

**Comment by Shnoulle** [comment]
It's not **other** fix. The 2 pull request are for exactly the same «issue» [15873: setVariableExpressionEnd have lack of system to udate question part](https://bugs.limesurvey.org/view.php?id=15873)

But it's more about the way to do ...

Current way + this commit : can broke specific plugin when update ExpressionScript easily

I try to find a way but .... need ExpressionScript rewrite before maybe ...

**Comment by Shnoulle** [comment]
See

- Add questionSeq2relevance to the event set and get (this pull)
    - Advantage : the most par updatable by plugin, no need other. I'm sure we can set order etc ...
    - Con : plugins can broke totally Expression Script system easily
- Add related function in API
    - Advantage : ? unknow (because knowVars array still can be updated)
    - Con : Create new function in EM just for API. API just call just created function

**Comment by olleharstedt** [comment]
Before I merge: Is there a new feature issue I can link to? No acceptance tests necessary.

**Comment by Shnoulle** [comment]
See https://gitlab.com/SondagesPro/coreAndTools/organizeSurvey/-/commit/80054f58b47abf4dced236cbdbc542b4456463a9

If you want to really update `hidden` or  `relevance` or order of questions : you need questionSeq2relevance update 

See https://www.limesurvey.org/forum/design-issues/120373-grouping-questions-within-a-question-group#194606 forum post too.

**Comment by olleharstedt** [comment]
Hm, I'd prefer "New feature #xxxxx: Bla bla bla". Mind creating an issue real fast in the feature project on Mantis? Sorry for the administration overhead...

**Comment by Shnoulle** [comment]
Not really a new feature here .... since it was a update on existing feature.

Update knowVars work only for fixed var, but not for dynamic var (question) because EM and SurveyRuntime use `questionSeq2relevance` and not `knowVars` (when i make the original pull requets, i really think EM use knowVars ... but EM ................ 🤔

**Comment by Shnoulle** [comment]
OK done : https://bugs.limesurvey.org/view.php?id=15923

About adding a plugin : if you want questionOrganizer or answerAsreadonly in core : you can ask.

**Comment by olleharstedt** [comment]
Danke schoen!

**Comment by Shnoulle** [comment]
Thanks to you .

If you find an interesting plugin to have in core, but with not more than one day work ....

I think i propose organizeSurvey in core, but only when it's really stable .... (and then we can add a test)

**Pull request merged**
