### PR TITLE
Fixed issue #19277: When export to CSV : multiple PHP error with debug and php8.1

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: fix with for NULL value

### CODE REVIEW

**Comment by Shnoulle** [comment]
Not fixed for xlsx : need composer update

**Review by gabrieljenik — APPROVED** [review]
Code looks good!

**Comment by c-schmitz** [comment]
@Shnoulle This patch breaks the export of the comment field in 'List with comments' question types - the comment field is now always empty. I also feel that now NULL values are not shown/exported anymore. (but I did not verify that).

**Comment by Shnoulle** [comment]
> @Shnoulle This patch breaks the export of the comment field in 'List with comments' question types - the comment field is now always empty. I also feel that now NULL values are not shown/exported anymore. (but I did not verify that).

You have a lss for testing ? I understand for null value, but how can it update something with  'List with comments'  ???

**Comment by Shnoulle** [comment]
For N/A : https://bugs.limesurvey.org/view.php?id=19383 (warranty ;) )

**Comment by Shnoulle** [comment]
> @Shnoulle This patch breaks the export of the comment field in 'List with comments' question types - the comment field is now always empty. 
[survey_archive_ListWithComment.zip](https://github.com/LimeSurvey/LimeSurvey/files/14096137/survey_archive_ListWithComment.zip)

I can not reproduce (rename .zip to lsa)

**Pull request merged**
