### PR TITLE
Fixed issue #17973: Error 404 for statisctics_user/action

### PR DESCRIPTION
**Pull request by gabrieljenik**
Controller changed from Statistics_userController to StatisticsUserController.
The runtime generates the url as "statistics_user/action/surveyid/123456".

That used to work before because to look for the controller class, a ucfirst() is done.

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]

**Comment by bilias** [comment]
does not work for me...
still get a 404 on /index.php/statistics_user/action/surveyid/257815

application/config/routes.php:
$route['statistics_user/<surveyid:\d+>'] = array('StatisticsUser/action', 'matchValue'=>true);
$route['statistics_user/action'] = 'StatisticsUser/action';

application/helpers/SurveyRuntimeHelper.php:
$this->aSurveyInfo['aCompleted']['aPublicStatistics']['sUrl']  = $surveyActive ? Yii::app()->getController()->createUrl("/StatisticsUser/action/", array('surveyid' => $this->iSurveyid, 'language' => App()->getLanguage())) : "#";

**Comment by bilias** [comment]
FYI I've also upgraded upgraded today to latest version 5.3.7+220328
and reapplied the patch without any change. Still 404

**Comment by gabrieljenik** [comment]
Thanks will review again

**Comment by psonHN** [comment]
I applied the code to 2 installation 5.3.4 and 5.3.5 and it works (url typed manually).

**Comment by bilias** [comment]
I've even deleted opcache files,

$ egrep 'statistics_user|StatisticsUser'  application/config/routes.php
$route['statistics_user/<surveyid:\d+>'] = array('StatisticsUser/action', 'matchValue'=>true);
$route['statistics_user/action'] = 'StatisticsUser/action';

$ egrep 'statistics_user|StatisticsUser' application/helpers/SurveyRuntimeHelper.php 
                $this->aSurveyInfo['aCompleted']['aPublicStatistics']['sUrl']  = $surveyActive ? Yii::app()->getController()->createUrl("/StatisticsUser/action/", array('surveyid' => $this->iSurveyid, 'language' => App()->getLanguage())) : "#";

404: Not Found
Unable to resolve the request "statistics_user/action/surveyid/197941".
URL is: limesurvey.example.com/index.php/statistics_user/action/surveyid/197941

maybe some other cache? I've also recreated tmp folder without any change.
What URL did you use?

**Comment by psonHN** [comment]
> I've even deleted opcache files,
> 
> $ egrep 'statistics_user|StatisticsUser' application/config/routes.php $route['statistics_user/surveyid:\d+'] = array('StatisticsUser/action', 'matchValue'=>true); $route['statistics_user/action'] = 'StatisticsUser/action';
> 
> $ egrep 'statistics_user|StatisticsUser' application/helpers/SurveyRuntimeHelper.php $this->aSurveyInfo['aCompleted']['aPublicStatistics']['sUrl'] = $surveyActive ? Yii::app()->getController()->createUrl("/StatisticsUser/action/", array('surveyid' => $this->iSurveyid, 'language' => App()->getLanguage())) : "#";
> 
> 404: Not Found Unable to resolve the request "statistics_user/action/surveyid/197941". URL is: limesurvey.example.com/index.php/statistics_user/action/surveyid/197941
> 
> maybe some other cache? I've also recreated tmp folder without any change. What URL did you use?

Instead of "statistics_user" I used "StatisticsUser".

**Comment by bilias** [comment]
that was it.
/index.php/StatisticsUser/action/surveyid/197941
works :)

However, the link that is presented to the user after survey completion is /index.php/statistics_user/197941?language=en

**Comment by psonHN** [comment]
Oh, I see.

**Pull request merged**
