### PR TITLE
Fixed issue #16500: Printable survey have no 'group_order' and 'question_order' attribute

### PR DESCRIPTION
**Pull request by ushiyasan**
Fixed issue #<Mantis issue number>:16500
New feature #<Mantis issue number>:
Dev:

### CODE REVIEW

**Comment by Shnoulle** [comment]
Seems cool !

**Review by eddylackmann — APPROVED** [review]

**Comment by eddylackmann** [comment]
@ushiyasan can you please reabase your branch and solve the merge conflict ?

**Review by eddylackmann — CHANGES_REQUESTED** [review]
Rebase and solve merge conflict

**Comment by gabrieljenik** [comment]
Ported to this PR: https://github.com/LimeSurvey/LimeSurvey/pull/1655
To be closed.

**Pull request closed without merging**
