### PR TITLE
Fixed issue #17765: The order of the answer options not correct when exporting to printable survey or queXML

### PR DESCRIPTION
**Pull request by c-schmitz**

### CODE REVIEW

**Comment by olleharstedt** [comment]
That was quick :)

**Comment by Shnoulle** [comment]
No default scope on answer ?

**Comment by c-schmitz** [comment]
I was afraid of setting a default scope. Did not want to compromise other stuff like alpha_sort

**Comment by Shnoulle** [comment]
> I was afraid of setting a default scope. Did not want to compromise other stuff like alpha_sort

Yes, i think default_scope order are only when there are no other order :). Maybe develop ?

**Pull request merged**
