### PR TITLE
Fixed issue #18427: LDAP plugin error when try to create new user on PHP8.1

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: same fix than log in
Dev: check if connection is an array

### CODE REVIEW

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/2684#issuecomment-1288606568

**Comment by gabrieljenik** [comment]
I noticed I got assigned to this PR. What I am supposed to do about it? Sorry don't understand :)

**Comment by Shnoulle** [comment]
Just a code review.

See 
- https://github.com/LimeSurvey/LimeSurvey/pull/2684#issuecomment-1288553588 : need to check it's an array (in place of isset) with debug > 1
- https://forums.limesurvey.org/forum/plugins/128491-error-when-authenticating-using-authldap-auto-create-user-fails need a fix for PHP8 for user creation 

Thank you

**Comment by gabrieljenik** [comment]
Already left a few comments :) Thanks

**Comment by Shnoulle** [comment]
Checked OK ? or not ?

**Comment by gabrieljenik** [comment]
I hope you can answer them ....

**Comment by olleharstedt** [comment]
Looks fine to me? Also, I see no comments.

**Comment by Shnoulle** [comment]
> I see a problem of letting the user test - they only test in their new environment. So when a fix is done for PHP 8.1, we should probably check so that it still works for PHP 7.2.

I can for LDAP …

You're right about User test but dev test too …

**Comment by olleharstedt** [comment]
> You're right about User test but dev test too …

Hopefully dev test, yes. ^^

**Comment by Shnoulle** [comment]
> > You're right about User test but dev test too …
> 
> Hopefully dev test, yes. ^^

I mean : any tester test what they think … but rarely : error in config for example, deleted directory, hacked HTML etc …

**Pull request merged**
