### PR TITLE
Fixed issue #13565: Remove punctuation points from php

### PR DESCRIPTION
**Pull request by KRav007**
Fixed issue #13565: Remove punctuation points from php

### CODE REVIEW

**Comment by olleharstedt** [comment]
You should probably change the translations and include the period.

**Comment by KRav007** [comment]
What means "the period". If I put the point to the translation-string, the mo-files don't find the string anymore?! Right?! How to deal with the x mo files. Is there a job that move strings around - to the mo files ?

**Comment by Shnoulle** [comment]
+1 for @olleharstedt , yes translation must be updated :).

**Comment by olleharstedt** [comment]
@KRav007 Just move the point (full stop) into the string, and the translation tools will automatically mark the translation as "needs to be updated".

**Comment by KRav007** [comment]
ok - cool - done

**Comment by LouisGac** [comment]
Is this going to work with RTL languages?

**Comment by KRav007** [comment]
From my logic - it should. RTL would not beginn with punctions on right side…

**Pull request merged**
