### PR TITLE
Fixed issue #18136: Core plugin PasswordRequirement shows duplicate setting fields

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: add info h3

### CODE REVIEW

**Comment by Shnoulle** [comment]
Capture d’écran du 2022-06-03 09-26-43

**Comment by maziminke** [comment]
@Shnoulle So "Check password when saving" refers to the "Save and return later" feature?

**Comment by maziminke** [comment]
How about:
Check password requirements at "Save and return later" feature

**Comment by Shnoulle** [comment]
«Password requirements for administration login»

«Password requirements for "Save and return later" feature»

?

**Comment by maziminke** [comment]
Both sounds good!

**Comment by Shnoulle** [comment]
@c-schmitz for grammar 😳

**Review by gabrieljenik — APPROVED** [review]

**Comment by Shnoulle** [comment]
Then : who merge it ?

**Comment by gabrieljenik** [comment]
@olleharstedt ?

**Pull request merged**
