### PR TITLE
Fixed issue #16937: Easy way to launch CDBException

### PR DESCRIPTION
**Pull request by gabrieljenik**
Porting #16481 to LS4.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Original pull request still not merged in 3.X https://github.com/LimeSurvey/LimeSurvey/pull/1480

And 

> for master : we need a better solution : move after setMoveResult ?

because [prefill value broke survey policy  currently](https://bugs.limesurvey.org/view.php?id=16482).

**Comment by gabrieljenik** [comment]
> for master : we need a better solution : move after setMoveResult ?

We have moved it:
- from `StartSurvey()`, which is run inside `initFirstStep()`
- to after `setMoveResult`

This is the list of steps it does for starting up:
```
    /**
     * Init session/params values depending of user moves
     *
     * - It init the needed variables for navigation: initFirstStep, initTotalAndMaxSteps, setMoveResult
     * - Then perform all the needed checks before moving:
     *   + did the participant used browser navigation?
     *   + did he pressed clear cancel, is he a confirmed quota?
     *   + Is the previous step set?
     *   + Is the survey finished?
     *   + Are all the answer validated? (like: participant didn't answered to a mandatory question)
     */
    private function initMove()
    {
        $this->initFirstStep(); // If it's the first time user load this survey, will init session and LEM
        $this->initTotalAndMaxSteps();
        $this->checkIfUseBrowserNav(); // Check if user used browser navigation, or relaoded page
        if ($this->sMove != 'clearcancel' && $this->sMove != 'confirmquota') {
            $this->checkPrevStep(); // Check if prev step is set, else set it
            $this->setMoveResult();
            $this->checkClearCancel();
            $this->setPrevStep();
            $this->checkIfFinished();
            $this->setStep();
            $this->saveStartingValues();
```

Why do we need to move it after `setMoveResult()`?
Shouldn't it be done before so the EM data is available for setting the move?

**Comment by cdorin93** [comment]
Everything seems ok - I cannot reproduce the issue. However, Travis is red. Could you please check once more the PR, @gabrieljenik ?

**Comment by gabrieljenik** [comment]
The testing error is very strange. Also the merge seems difficult. I will just reaply the patch on top of develop and create a new PR

**Comment by gabrieljenik** [comment]
Check https://github.com/LimeSurvey/LimeSurvey/pull/1726

**Pull request closed without merging**
