### PR TITLE
insert no-more-tables class to array-by-columns-table

### PR DESCRIPTION
**Pull request by KRav007**
in this question the class was missing

### CODE REVIEW

**Comment by olleharstedt** [comment]
No. Array-by-column is rebuilt using Javascript.

**Comment by KRav007** [comment]
hi ole - ok. is it come from core? or from theme?

**Comment by olleharstedt** [comment]
Will check.

**Comment by olleharstedt** [comment]
In template, e.g. `default/scripts/template.js`, function `replaceColumnWithDiv`.

**Comment by KRav007** [comment]
ok thanks

**Comment by olleharstedt** [comment]
Nice, you're in Hamburg. You should join on after-work sometime. :)

**Comment by KRav007** [comment]
yeah.. do you have a babysitter :-) where are you go to after work?

**Comment by olleharstedt** [comment]
We work near Kampnagel but go to different places.

**Pull request closed without merging**
