### PR TITLE
Fixed issue #17082: text display in plain italics not possible

### PR DESCRIPTION
**Pull request by gabrieljenik**
Adjusting weight queries as to make regular italic to use the Italic.ttf font

### CODE REVIEW

**Review by olleharstedt — APPROVED** [review]

**Comment by olleharstedt** [comment]
Approved if testing is ok.

**Comment by olleharstedt** [comment]
Using popup text edit, I got this code:

```
<p><em>bla bla bla</em></p>

<p><strong>bla bla bla</strong></p>

<p>bla bla bla</p>

<p><u>bla bla bla</u></p>
```

**Comment by olleharstedt** [comment]
`<em>` needs to be `<i>`

**Comment by Shnoulle** [comment]
> `<em>` needs to be `<i>`

Noooooooooo !

**Comment by olleharstedt** [comment]
> > `<em>` needs to be `<i>`
> 
> Noooooooooo !
> 
> HTML must be semantics first , not only for a11y : https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#good_semantics

Ctrl-f "italic", nothing?

**Comment by Shnoulle** [comment]
> Ctrl-f "italic", nothing?

I didn't understand, even github use em for _Add italic text_

**Comment by olleharstedt** [comment]
> > Ctrl-f "italic", nothing?
> 
> I didn't understand, even github use em for _Add italic text_

Oh yeah. OK, I'm wrong, I thought <i> meant "italic".

**Comment by Shnoulle** [comment]
> Oh yeah. OK, I'm wrong, I thought `<i>` meant "italic".

Yes , without other ean, it's like a span. It's one of the reason of usage by font-awesome ; https://fontawesome.com/v4.7.0/icon/id-card-o 

`i` : no meaning, «don't care»
`em` : something different here, not louder (like strong) but an emphasis.

Same for `b `VS `strong`

**Comment by olleharstedt** [comment]
Nevertheless, the `<em>` was still bold. I was running on debug = 2. Gabriel, maybe you need to increase the assetversionnumber as well?

**Comment by gabrieljenik** [comment]
Guys, I will stand by on this one for a while.
This kind of CSS adjustments need to be fine tuned and also applied / revieed with other fonts in the themes.

On the other side, this could have some backwards incompatibility with all other extended themes.

So, considering this is minor.
Will make it a "stand by"

**Comment by olleharstedt** [comment]
Sure, we can talk about it later, maybe during Discord meeting. Added the "Needs review" label.

**Pull request merged**
