### PR TITLE
Fixed issue # 17007: bug on invitation+reminder dates when creating a  new token using the integrated LS GUI

### PR DESCRIPTION
**Pull request by gabrieljenik**
Removed extra spaced which were previously removed by a flattenText call. That flattenText was removed, so adapting the view to the new situation.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Maybe adding a auto trim in model ?

**Comment by cdorin93** [comment]
thx for merge and PR, guys!

**Comment by Shnoulle** [comment]
My fault … sorry …

**Comment by cdorin93** [comment]
It was needed :D

**Comment by Shnoulle** [comment]
@gabrieljenik : you fix it in master or you do it ?

**Pull request merged**
