### PR TITLE
Dev #T635: Land in the Suvey Builder (Structure) when creating a survey

### PR DESCRIPTION
**Pull request by gabrieljenik**
1. When a user creates a survey he should always land on the first question of the first question group in the STRUCTURE tab. If no question group exists a default one (the demo one) is created, and he lands on that first question group.
2. By doing so we don't need the option in create survey: "Create example question group and question?". Get rid of that option.

### CODE REVIEW

**Comment by Shnoulle** [comment]
> If no question group exists a default one (the demo one) is created

But why ? 

I already ask to remove the forced demo question, not to ask again to disable it …

**Comment by ViliusS** [comment]
I support @Shnoulle here. The purpose of demo question/question group should be to introduce new LimeSurvey users how to create a question. Hence, demo question should be an option **and** _disabled by default_. I would hate to delete that question every time when I create a survey even though I have created hundreds of them in the past.

**Comment by gabrieljenik** [comment]
This was requested by Jory Nigel. I agree with him on this one.
Having the first groups and question already cerated saves some clicks and also it is easier for newcomers.
For pro-users is it really a big difference? Instead of deleting, you just edit.

**Comment by ViliusS** [comment]
Newcomers would use this functionality _once_. Pro-users would need to use workaround (edit or delete) _every time_.

**Comment by Shnoulle** [comment]
> This was requested by Jory Nigel. I agree with him on this one.

2 VS 2 ;)

> Having the first groups and question already cerated saves some clicks and also it is easier for newcomers.
> For pro-users is it really a big difference? Instead of deleting, you just edit.

New user settings ?

- autocreate question and group when create a survey
- autocreate question and group when a survey is empty.

**Comment by gabrieljenik** [comment]
> New user settings ?

Why? That would make things more complex, not simpler.
I mean, what is so bad about going in the first group and edit it instead of just creating the first group?

> PS : a lot pof user have a 1st group with variables, specific question etc… the 1st things they do : it's import this group.
They can still do that.

**Comment by ViliusS** [comment]
> > PS : a lot pof user have a 1st group with variables, specific question etc… the 1st things they do : it's import this group.
> 
> They can still do that.

I think the question is not if they can do that, but the question of convenience. Pro users could do a lot of things, but it doesn't mean that LimeSurvey needs to put them into this position and force to do unnecessary things.

Don't get me wrong, I support making LimeSurvey more friendly for novice users, but I feel that one-time wizard or better UX in general would be a better way to achieve this.

Now you are making experience better for one group of people and making it worse for other group.

**Comment by gabrieljenik** [comment]
> Don't get me wrong, I support making LimeSurvey more friendly for novice users, but I feel that one-time wizard or better UI in general would be a better way to achieve this.

We understand this. And that is the way to go.
This change was just a small adjustment.

> Now you are making experience better for one group of people and making it worse for other group.

Worse? How much worse?

**Comment by ViliusS** [comment]
> > Don't get me wrong, I support making LimeSurvey more friendly for novice users, but I feel that one-time wizard or better UI in general would be a better way to achieve this.
> 
> We understand this. And that is the way to go.
> This change was just a small adjustment.

This needs to be done on a global scale. You cannot fix UX with small changes. 

> > Now you are making experience better for one group of people and making it worse for other group.
> 
> Worse? How much worse?

I can speak only for myself here, I would _hate_ to do additional steps (delete or edit). LimeSurvey configuration is enough complicated as it is. Also I _hate_ software which thinks that it knows better than me and autocompletes/autocreates/autoreboots/auto-does something on its own.

**Comment by Shnoulle** [comment]
> > Now you are making experience better for one group of people and making it worse for other group.
> 
> Worse? How much worse?

3 click against 1 is worse when you do it 150 times a day …

And : since LimeSurvey admin are not really speed : 2 click more mean 5 second more …

**Comment by Shnoulle** [comment]
> Worse? How much worse?

And why auto create is better ? 
For new user : understand they have to create a group (or more) to put question in it.

Else : we have sometime on forum some user using only one group : they don't know really understand they can create group.

**Comment by Shnoulle** [comment]
User settings ? ;)

**Comment by olleharstedt** [comment]
Who takes the decision here?

**Comment by ViliusS** [comment]
> User settings ? ;)

I think global setting is fine. It could be even more general, and named like "Tutorial interface" > "On"/"Off". This one switch could enable automatic question creation, display of various hints in the interface, etc.

**Comment by Shnoulle** [comment]
> > User settings ? ;)
> 
> I think global setting is fine. It could be even more general, and named like "Tutorial interface" > "On"/"Off". This one switch could enable automatic question creation, display of various hints in the interface, etc.

Yes, but for company : it's a user settings needed. Only some user need an help during a time. 

It a user choice, not a global choice.

**Comment by maziminke** [comment]
Many long term users of Limesurvey will be **very** annoyed if they have to edit an auto-generated group **and** an auto-generated question every time they create a new survey. I will surely be one of them!

Please do **not** add this to the core. The benefit for new users is really minor and for experienced Limesurvey users this makes things worse. We already lost a lot of reputation, this will add to it.

**Comment by Shnoulle** [comment]
@maziminke : why not like other user settings ?

1. Global settings by default (default came from DB)
2. User settings

I know HTML editor stay Inline a lot, and maybe muts be popup by default, but this allow superadmin : 

1. Choose the way for new user
2. Some admin to allow update own settings
3. Have a default default for new installation of CE or at SAAS.

**Comment by gabrieljenik** [comment]
> @maziminke : why not like other user settings ?
> 
> 1. Global settings by default (default came from DB)
> 2. User settings
> 
> I know HTML editor stay Inline a lot, and maybe muts be popup by default, but this allow superadmin :
> 
> 1. Choose the way for new user
> 2. Some admin to allow update own settings
> 3. Have a default default for new installation of CE or at SAAS.

I like having this as user settings. Fair simple to implement.

**Comment by gabrieljenik** [comment]
Now we have a global and a user setting for controlling whether to create sample questions. :)

**Comment by olleharstedt** [comment]
Before merge - has this feature been documented?

**Comment by gabrieljenik** [comment]
Actually, I have not detected anything else to update, nor not sure if there is anything to add.
Maybe we could add the new global setting to the manual, but there is no personal setting section

**Comment by olleharstedt** [comment]
https://manual.limesurvey.org/First_login_-_your_user_preferences#My_personal_settings ?

**Comment by gabrieljenik** [comment]
Added here:
https://manual.limesurvey.org/Global_settings#General
https://manual.limesurvey.org/First_login_-_your_user_preferences#My_personal_settings

**Comment by olleharstedt** [comment]
Nice!

**Pull request merged**
