### PR TITLE
Dev: fix really seacrh Question, not with language

### PR DESCRIPTION
**Pull request by Shnoulle**

### CODE REVIEW

**Comment by Shnoulle** [comment]
I don't think need testing, since : you really test on https://bugs.limesurvey.org/view.php?id=17042

**Comment by gabrieljenik** [comment]
> I don't think need testing, since : you really test on https://bugs.limesurvey.org/view.php?id=17042

17042 only happens in 3.x, not in master.
So, no, will not be testing on master. Sorry

**Review by gabrieljenik — APPROVED** [review]
Code change looks good.
Haven't tested it

**Comment by Shnoulle** [comment]
>  So, no, will not be testing on master. Sorry

We need a way to broke database to check if it work ;)

**Pull request merged**
