### PR TITLE
Fixed issue #16442: Unable to use string with "on" in theme option label

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: User theme options must not be update totally like this
Dev: New settings already use optionlabels

### CODE REVIEW

**Comment by Shnoulle** [comment]
See https://github.com/LimeSurvey/LimeSurvey/commit/5b974d2557f5b8ecf05d789effbda81b3afdce4a

**Comment by Shnoulle** [comment]
Dominik does the original part , but seems uneeded . `core` have optionslabels and not `core` can do anything else.

Still need a clean way to get clean translatable label :), but not core can use `{{ gT("Yes") }}`

**Comment by Shnoulle** [comment]
And why you must not use 'no' or 'null' to be false

https://hitchdev.com/strictyaml/why/implicit-typing-removed/

**Comment by eddylackmann** [comment]
@Shnoulle  can you please rebase your branch and fix the merge conflict ?  Thanks

**Review by eddylackmann — CHANGES_REQUESTED** [review]
@Shnoulle can you please rebase your branch and fix the merge conflict ? Thanks

**Comment by Shnoulle** [comment]
Shit … broken …

```
git rebase origin/master
git pull Shnoulle master_16442
```

I redo , seems the force_pushed broke the rebase …

**Comment by Shnoulle** [comment]
?

Capture d’écran du 2020-10-16 12-26-12

**Comment by eddylackmann** [comment]
> ?
> 
> Capture d’écran du 2020-10-16 12-26-12

Looks good . No Merge conflict anymore. Lets wait for Travis . Thank you :)

**Comment by Shnoulle** [comment]
Yes, when compare, but here show 127 commits and 135 files change (for me only ?)
Capture d’écran du 2020-10-16 12-31-12

**Comment by Shnoulle** [comment]
> > ?
> > Capture d’écran du 2020-10-16 12-26-12
> 
> Looks good . No Merge conflict anymore. Lets wait for Travis . Thank you :)

Yes , when compare but here : show 135 files changes and 127 commits : for me only ?
Capture d’écran du 2020-10-16 12-32-59

**Comment by eddylackmann** [comment]
Holly Sh** , 127 commits.  Let me check that again on my localhost .

**Comment by Shnoulle** [comment]
I do exatly that 

`git rebase origin/master`
Trying to push : tell that something must be done

`git pull Shnoulle master_16442`
Push : and see whole commits… 
I surely make an error somewhere …

We can close this one and use this one : https://github.com/LimeSurvey/LimeSurvey/pull/1626

**Pull request closed without merging**
