### PR TITLE
New feature: #13853 - Allow test & basic feedback of the email functionality.

### PR DESCRIPTION
**Pull request by githubLewis**
New feature: Allow test & basic feedback of the email functionality.
New feature # : 13853

Dev: This change affects the UI of two of the tabs - "bounce settings" and "email settings"
Dev: the UI changes are just to keep everything consistent.
Dev: The main change adds a "Test" button to the "email settings" tab which allows
Dev: the user to test the *saved* configuration options. Feedback is returned and displayed
Dev: in a flash message.

### CODE REVIEW

**Comment by Shnoulle** [comment]
I like the idea :+1: .

Just some update (maybe)
- Create a view for the result and didn't [redirect](https://github.com/LimeSurvey/LimeSurvey/pull/1093/files#diff-281d99ac5e11882a14aa7083c876b49cR99) 
- Force maildebug to 2 when testing (just add `App()->setConfig('maildebug',2)\ just before sending email.

**Comment by githubLewis** [comment]
Sure, I'll make the debug change as per the initial feedback and check it in the develop branch. 

Question - should it redirect to a new view, is this the LS standard? Happy to make the change but I thought it made sense to not redirect as the user can make configuration changes, save, test, get feedback and go through the loop quickly rather than navigating back from a different view.

**Comment by githubLewis** [comment]
Closing this pull request as changes have now been made on the develop branch and not this branch.

**Comment by githubLewis** [comment]
New Pull Request: https://github.com/LimeSurvey/LimeSurvey/pull/1094

**Pull request closed without merging**
