### PR TITLE
New feature: Allow user to enter to the survey after registering.

### PR DESCRIPTION
**Pull request by Shnoulle**
New survey setting : directregister : if set to Yes : user have the link to enter to the survey just after registering
And some correction to registercontroller

3 possibility:
- No: default like now
- Yes: shown : show the url after register
- Yes: direct : directly goes to url just after registering

### CODE REVIEW

**Comment by maziminke** [comment]
Denis, looks like this one was lost in space...?

Carsten, can we add this to 2.5? It is an often requested feature (start token based survey directly after registration).

**Comment by danielgimeno** [comment]
Marcel is not completely forgoten, I've started a plugin to allow token to
log to LDAP server.

I'll keep you informed.

 Daniel

2016-02-19 9:02 GMT+01:00 Marcel Minke <notifications@github.com>:

**Comment by Shnoulle** [comment]
Hi,

It's already in a plugin :
https://git.framasoft.org/SondagePro-LimeSurvey-plugin/replaceRegister/blob/develop/replaceRegister.php#L72

But yes : it can be interesting to have an option in core i think. Showing the token form too : You can register OR if you already have a token.

All 2.1 are lost.

Denis

**Comment by danielgimeno** [comment]
Great, it's good information to not start from scratch.

Thank you

2016-02-19 9:52 GMT+01:00 Denis Chenu <notifications@github.com>:

**Comment by Shnoulle** [comment]
@c-schmitz : my new idea with this : add a new little plugin : 

- Global setting : Redirect- to survey after successfull register by default : yes/no(default)
- Survey setting : Redirect- to survey after successfull register by default : yes/no/default(default)

Maybe we need too : "mandatory email" ?

**Comment by maziminke** [comment]
Denis, I like the idea but I think it would be sufficient to always let the survey admin select which method to be used.

Email should always be mandatory if no redirect is enabled.

**Comment by Shnoulle** [comment]
Yes : right

**Pull request closed without merging**
