### PR TITLE
Fixed issue #16181: some strings in italian have characters shown as entities

### PR DESCRIPTION
**Pull request by gabrieljenik**
The encoded strings were shown in the quickmenu, but not in the "normal" side menu.
_submenu.vue had a reConvertHTML method for handling such strings, but _quickmenu.vue did not.
Copied reConvertHTML to _quickmenu.vue and applied it to the tooltips

### CODE REVIEW

**Comment by sushmanadendlals** [comment]
Issue is not fixed completely, please refer mantis for more details

**Comment by sushmanadendlals** [comment]
Issue Fixed. Please refer mantis for more details

**Review by eddylackmann — CHANGES_REQUESTED** [review]
Can you please rebase you branch with the actual master and push it again? Just to be sure that we have the same state. And also Travis has to be run again. Thanks :)

**Comment by gabrieljenik** [comment]
> Can you please rebase you branch with the actual master and push it again? Just to be sure that we have the same state. And also Travis has to be run again. Thanks :)

New PR: https://github.com/LimeSurvey/LimeSurvey/pull/1580

**Pull request closed without merging**
