### PR TITLE
New feature: add afterGenerateToken event with customToken plugin

### PR DESCRIPTION
**Pull request by Jan-E**
@Shnoulle @olleharstedt 
This PR contains the same changes as in https://github.com/LimeSurvey/LimeSurvey/pull/1307, but now to the develop branch. Let us continue the conversation here. I will close https://github.com/LimeSurvey/LimeSurvey/pull/1307

### CODE REVIEW

**Comment by Jan-E** [comment]
In reply to https://github.com/LimeSurvey/LimeSurvey/pull/1307#issuecomment-513716509
> @Jan-E : about plugin : i mean plugin inside LimeSurvey core. Unsure of the place : plugins/ seems best in my opinion. see [mailSenderToFrom](https://github.com/LimeSurvey/LimeSurvey/tree/develop/plugins/mailSenderToFrom) for example : thius fix a mantis LimeSUrvey issue (and the [2 new plugins](https://github.com/LimeSurvey/LimeSurvey/pull/1256/files#diff-a084b794bc0759e7a6b77810e01874f2R75) in this pull request : [New feature setVariableExpressionEnd ](https://github.com/LimeSurvey/LimeSurvey/pull/1256))

OK, now I see what you mean. I will see what I can do.

**Comment by Jan-E** [comment]
OK, I added a customToken plugin and tested it in LS 4.0.0-RC1 and LS 3.17.0+190402.
What next?

**Comment by Jan-E** [comment]
Is anything blocking this to be merged? We need at least the first commit (the new afterGenerateToken event) for our use case in https://bugs.limesurvey.org/view.php?id=15026:
15026: Omit ambiguous characters from token

**Comment by Jan-E** [comment]
I have merged the customToken plugin part of the PR into 1 commit.
Please review and merge.

**Comment by Shnoulle** [comment]
Personnaly , i think it's a really good pull request :) Allowing to generate token by an external API can be needed too :)

**Comment by Jan-E** [comment]
> Allowing to generate token by an external API can be needed too :)

Tokens generated by `add_participants($sSessionKey, $iSurveyID, $aParticipantData, $bCreateToken = true)` in the RPC will already follow the customToken settings.

The same applies to `getTokenId($iSurveyId)` in the RegisterController class
https://github.com/LimeSurvey/LimeSurvey/blob/master/application/controllers/RegisterController.php#L413

Both do essentially:
1. Initiate the Token class: `$token = Token::create($iSurveyID)`
2. Add a generated token to that class: `$token->generateToken()`

addDummies() will follow the same procedure, once this PR is merged.

**Comment by Jan-E** [comment]
@Shnoulle What is the standard procedure for new features like this? Merge it to develop will only add it to 4.0.0-RCx, I guess. When and how will it be backported to 3.17.x?

**Comment by Shnoulle** [comment]
It was never BackPorted …

About new feature : i have same issue than you : like to have some new (little) feature in 3.X , but i didn't decide … see https://github.com/LimeSurvey/LimeSurvey/pull/1271 for example … light featire, can not broke anything but …

**Comment by Jan-E** [comment]
I asked the same to @olleharstedt : https://github.com/LimeSurvey/LimeSurvey/pull/1307#issuecomment-514147618

If we want it in 3.17.x and it will not be backported, what is the way to go? Create another PR for the master branch?

**Comment by Shnoulle** [comment]
@Jan-E : only @c-schmitz can answer.

**Comment by Jan-E** [comment]
@c-schmitz I can imagine that adding a new plugin to LS 3.x is a step too far. Will a PR with only the new afterGenerateToken event to master be approved?

**Comment by LouisGac** [comment]
If everybody agrees on it, I bet Carsten will aprove it.

**Comment by Jan-E** [comment]
It will be the first commit in this PR: https://github.com/LimeSurvey/LimeSurvey/pull/1308/commits/dbc8d47cdaeecf2608954e8abd8f5b099d04ba51

**Comment by Shnoulle** [comment]
> If everybody agrees on it, I bet Carsten will aprove it.

I ask for some really minor feature‘s in master some week ago, and the answer are «All new feature for 4.0».
Then , if this one is OK : i NEED a clear situation about new feature !

**Comment by Jan-E** [comment]
Changes in that commit summarized:
1. In tokens.php: change the call from addDummies() to generateRandomToken() into a call to generateToken()
2. Because there already is a loop in generateToken() I removed the loop in addDummies(), but increased the attempts in generateToken to 50 (which was the failure threshold in addDummies)
3. Change `function generateToken()` into `function generateToken($tokenlength = NULL)`
4. If a tokenlength argument is passed to generateToken() that one is used, otherwise `$this->survey->tokenlength`
5. Change the `public static function generateRandomToken` into a `private function _generateRandomToken`
6. Change the calls to `$this::generateRandomToken()` into `$this->_generateRandomToken()`
7. Add a call to a new plugin event `afterGenerateToken` in `_generateRandomToken()`

**Comment by Shnoulle** [comment]
[Issue reopen as feedback.](https://bugs.limesurvey.org/view.php?id=15026)

**Comment by Jan-E** [comment]
Thanks for merging,

**Pull request merged**
