### PR TITLE
FIX: Survey form:admin email

### PR DESCRIPTION
**Pull request by TonisOrmisson**

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
not fixed still :(

**Comment by TonisOrmisson** [comment]
OK that should do it.
Moved the create/update difference from view to the model where it should be

**Comment by c-schmitz** [comment]
Is this fix still needed?

**Comment by TonisOrmisson** [comment]
I would say yes. 
I you create new survey, the owner & email fields are blank right now.
Im not sure about the conflicts right now, cant see them here.

**Comment by c-schmitz** [comment]
Could it  be that you have 'tabs' activated in your source editor?
All tabbing should be done by using spaces.

**Comment by TonisOrmisson** [comment]
no, spaces. I just merged, but now its broken

**Comment by TonisOrmisson** [comment]
OK now should be good again. 
The logic & decisions are done in model rather than the view. 
If, its the new model, we use current users data

**Pull request closed without merging**
