### PR TITLE
Fixed issue #17952: Command action potentially try to open uneeded session

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: no reproduction with sendMailCron, but avoid too uneeded session

### CODE REVIEW

**Comment by c-schmitz** [comment]
I think this is alot of checks in a function that is called hundreds of times in a very short period.
I am scared that this might have  a measurable hit on performance.
Why not make sure that CCConsoleApplication has  a proper admin language set, instead?

**Review by c-schmitz — CHANGES_REQUESTED** [review]
Imho not the correct approach. see previous comment

**Comment by Shnoulle** [comment]
Checked : only used for admin user error :).

For example : check survey logic of https://github.com/LimeSurvey/LimeSurvey/blob/master/docs/demosurveys/ls3_sample_survey_multilingual_fr_de_en_it.lss : function are not caled.

Best is to check if user is connected … return the default string or an empty string if not connected.

**Comment by Shnoulle** [comment]
@c-schmitz the only way to "fix it" on your way is to create a totally new false session system

```
$consoleConfig = array(
    'modules' => array(
        'components' => array(
            'session' => array(
                'class' => 'application.core.console.ConsoleSession',
            ),
        )
    )
);
```

It's what you want ?

**Comment by Shnoulle** [comment]
I test with sendMailCron and _Invitation to participate {lolo(titi}_ in invitation subject

```
PHP Error[2]: session_name(): Cannot change session name when headers already sent
    in file /data/webdev/master/framework/web/CHttpSession.php at line 206
#0 /data/webdev/master/framework/web/CHttpSession.php(206): session_name()
#1 /data/webdev/master/framework/base/CComponent.php(152): ConsoleHttpSession->setSessionName()
#2 /data/webdev/master/framework/YiiBase.php(227): ConsoleHttpSession->__set()
#3 /data/webdev/master/framework/base/CModule.php(393): createComponent()
#4 /data/webdev/master/framework/base/CModule.php(103): ConsoleApplication->getComponent()
#5 /data/webdev/master/application/helpers/expressions/em_core_helper.php(2567): ConsoleApplication->__get()
#6 /data/webdev/master/application/helpers/expressions/em_core_helper.php(1793): gT()
#7 /data/webdev/master/application/helpers/expressions/em_core_helper.php(603): ExpressionManager->HasSyntaxErrors()
#8 /data/webdev/master/application/helpers/expressions/em_core_helper.php(1997): ExpressionManager->RDP_Evaluate()
#9 /data/webdev/master/application/helpers/expressions/em_core_helper.php(1957): ExpressionManager->sProcessStringContainingExpressionsHelper()
#10 /data/webdev/master/application/helpers/expressions/em_manager_helper.php(4159): ExpressionManager->sProcessStringContainingExpressions()
#11 /data/webdev/master/application/core/LimeMailer.php(689): ProcessString()
#12 /data/webdev/master/application/core/LimeMailer.php(565): LimeMailer->doReplacements()
#13 /data/webdev/3LTS/plugins/sendMailCron/sendMailCron.php(604): LimeMailer->sendMessage()
#14 /data/webdev/3LTS/plugins/sendMailCron/sendMailCron.php(416): sendMailCron->sendEmails()
#15 /data/webdev/3LTS/plugins/sendMailCron/sendMailCron.php(298): sendMailCron->sendTokenMessages()
#16 unknown(0): sendMailCron->sendMailByCli()
#17 /data/webdev/master/application/libraries/PluginManager/PluginManager.php(269): call_user_func()
#18 /data/webdev/master/application/commands/PluginCommand.php(55): LimeSurvey\PluginManager\PluginManager->dispatchEvent()
#19 unknown(0): PluginCommand->actionIndex()
#20 /data/webdev/master/framework/console/CConsoleCommand.php(178): ReflectionMethod->invokeArgs()
#21 /data/webdev/master/framework/console/CConsoleCommandRunner.php(71): PluginCommand->run()
#22 /data/webdev/master/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#23 /data/webdev/master/framework/base/CApplication.php(185): ConsoleApplication->processRequest()
#24 /data/webdev/master/application/commands/console.php(77): ConsoleApplication->run()
```

before fix.

After fix  : noi issue.

Hard to tests since 
```
$test = LimeExpressionManager::ProcessString("test {toto(titi}", null, array(), 3, 1, false, false, true);
```
don't throw error :(

**Pull request merged**
