### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman100**

### CODE REVIEW

**Comment by Justman100** [comment]
@Shnoulle

**Comment by Shnoulle** [comment]
What is the question ?

**Comment by Shnoulle** [comment]
> > What is the question ?
> 
> Öhm.. Merging of this PR? Maybe?

Then : need composer update too.

Else : why me ?

**Comment by Shnoulle** [comment]
https://manual.limesurvey.org/First_steps_for_new_developers (partially outdated)
https://manual.limesurvey.org/How_to_contribute_new_features#Contribution_process

**Comment by Justman100** [comment]
> Else : why me ?

You have write permissions here?

**Comment by Justman100** [comment]
> https://manual.limesurvey.org/First_steps_for_new_developers (partially outdated) https://manual.limesurvey.org/How_to_contribute_new_features#Contribution_process

What does this have to do with my PR?

**Comment by Shnoulle** [comment]
> > Else : why me ?
> 
> You have write permissions here?

Yes, and ?

**Comment by Shnoulle** [comment]
> > https://manual.limesurvey.org/First_steps_for_new_developers (partially outdated) https://manual.limesurvey.org/How_to_contribute_new_features#Contribution_process
> 
> What does this have to do with my PR?

Because we don't accept and review any PR like that. See https://manual.limesurvey.org/Standard_for_Git_commit_messages 
And personnaly : i thin we always need a mantgis issue : https://bugs.limesurvey.org/my_view_page.php

**Comment by Justman100** [comment]
> > > Else : why me ?
> > 
> > 
> > You have write permissions here?
> 
> Yes, and ?

So you can merge PRs...

**Comment by Justman100** [comment]
> Because we don't accept and review any PR like that. See https://manual.limesurvey.org/Standard_for_Git_commit_messages

Rarely seen such bullshit! Fuck what the commit syntax is! One goes into the commit and sees what it does anyway...

> And personnaly : i thin we always need a mantgis issue : https://bugs.limesurvey.org/my_view_page.php
?

**Comment by Justman100** [comment]
> Because we don't accept and review any PR like that. See https://manual.limesurvey.org/Standard_for_Git_commit_messages

Rarely seen such bullshit! Fuck what the commit syntax is! One goes into the commit and sees what it does anyway...

> And personnaly : i thin we always need a mantgis issue : https://bugs.limesurvey.org/my_view_page.php

?

**Comment by c-schmitz** [comment]
@Justman100  We expect for a PR to  have a proper subject, a description of what it is supposed to fix etc. , as indicated by @Shnoulle .
Please fix this PR accordingly and be polite.

**Comment by Justman100** [comment]
> @Justman100 We expect for a PR to have a proper subject, a description of what it is supposed to fix etc. , as indicated by @Shnoulle . Please fix this PR accordingly and be polite.

One only has to look in the damn commit! One can see it there! I must choose a one-way title just because one can't look in the commits? The title is intentional, in case more commits should come, which would then conflict with the one-way title! It is also only a single change! And while we're discussing here, one could have looked at the commits and their changes already

**Comment by c-schmitz** [comment]
@Justman100 The reason is that we don't want to guess why you are doing this. Why spend my time checking the contents of your PR without even know WHY you submitted it in the first place. So I kindly ask  you to submit that information as requested and check our documentation on PR submission and act accordingly.

**Comment by Justman100** [comment]
> @Justman100 The reason is that we don't want to guess why you are doing this. Why spend my time checking the contents of your PR without even know WHY you submitted it in the first place. So I kindly ask you to submit that information as requested and check our documentation on PR submission and act accordingly.

Dude, you only have to look in the damn commit to realise that I updated the NodeJS modules! Don't act like I have 500 commits here that change 400 lines each!

**Pull request closed without merging**
