### PR TITLE
Fixed issue #18128 : Broken javascript on welcome page

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: cleaner separation between js tailoring for qid and out of qid
Dev: review pageTailorInfo to avoid empty varused
Dev: optimization of pageTailorInfo array adaptation : do it only once, and not once by qid.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Child of https://github.com/LimeSurvey/LimeSurvey/pull/2355

**Comment by Shnoulle** [comment]
Silly boy : https://github.com/LimeSurvey/LimeSurvey/pull/2381/files#diff-fa8d35264aa59c85d37ca2d1756472996499f06fb346865594378102f5f7abc0R7521

Use a different var here !

Do you have an advice about 
```
            foreach ($pageTailorInfo[0] as $tailor) {
                $tailorParts[] = $tailor['js'];
                $vars = array_filter(explode('|', $tailor['vars']));
                if (!empty($vars)) {
                    $tailorJsVarUsed = array_merge($tailorJsVarUsed, $vars);
                }
            }
```

against : 

```
            $tailorJsVarUsed = array_map( function($tailor) {
                    return $tailor['vars'];
                },
                $pageTailorInfo[0]
            );
            $tailorParts = array_map( function($tailor) {
                    return $tailor['js'];
                },
                $pageTailorInfo[0]
            );
```

**Comment by Shnoulle** [comment]
:heart: test \o/

**Comment by Shnoulle** [comment]
@maziminke maybe you can test the fix ?

**Comment by maziminke** [comment]
@Shnoulle Sorry, I am not available for testing this week. Maybe @olleharstedt or @glimz can check?

**Review by gabrieljenik — APPROVED** [review]
Code structure looks OK.
Haven't tested it.

**Comment by olleharstedt** [comment]
Can we get testing instructions, maybe? @Shnoulle

**Comment by Shnoulle** [comment]
> Can we get testing instructions, maybe? @Shnoulle

https://bugs.limesurvey.org/view.php?id=18128

**Comment by gabrieljenik** [comment]
NO JS error found in console when following "ticket steps".
I have used the survey given in ticket, but not sure if there is anything spcific about that survey, is it?

**Comment by Shnoulle** [comment]
> NO JS error found in console when following "ticket steps". I have used the survey given in ticket, but not sure if there is anything spcific about that survey, is it?

Need to be out of any step/question : home page enable.

https://master.sondages.pro/946144?newtest=Y&lang=en

No JS error in 3.X (seems `GetRelevanceAndTailoringJavaScript` not call when not needed.)
JS error in 5.X : GetRelevanceAndTailoringJavaScript is loaded without LimeExpressionManager::StartProcessingPage too)

**Comment by gabrieljenik** [comment]
> https://master.sondages.pro/946144?newtest=Y&lang=en

This showed me an error.

My test, with patch enabled,didn't.

**Comment by gabrieljenik** [comment]
Could reproduce it on Version 5.3.17.
Couldn't reproduce it after your patch

**Comment by Shnoulle** [comment]
> Could reproduce it on Version 5.3.17.

phew ;)

**Comment by Shnoulle** [comment]
Oups … not merged …

**Pull request merged**
