### PR TITLE
DEV: Edit Question Test

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by cdorin93** [comment]
@olleharstedt , have time to take a quick look at it?

**Comment by olleharstedt** [comment]
Looks like one element can't be found?

> NoSuchElementException: Unable to locate element: #cke_question_en

**Comment by olleharstedt** [comment]
If you run the test locally, skip `MOZ_HEADLESS=1` and you'll see the browser stepping through the test.

**Comment by gabrieljenik** [comment]
This is failing as this test is being run against a revert-vue-js branch while it was done for LTS

**Comment by olleharstedt** [comment]
> A hint: This is failing as this test is being run against a revert-vue-js branch while it was done for LTS

Is it? The branch says 3.x-LTS.

**Comment by olleharstedt** [comment]
This test works perfect for me locally, in isolation.

**Comment by gabrieljenik** [comment]
> > A hint: This is failing as this test is being run against a revert-vue-js branch while it was done for LTS
> 
> Is it? The branch says 3.x-LTS.

I swear I saw something about revert-vue-js
I will try increasing the wait time before the failing line.

**Comment by Shnoulle** [comment]
When i have issue like this : the screenshot help me a lot …

**Comment by Shnoulle** [comment]
Oups , sorry @olleharstedt already tested :)

**Comment by olleharstedt** [comment]
> When i have issue like this : the screenshot help me a lot …

Yeah, but running the suite locally takes forever. T_T Can't reproduce. Grrr.

**Comment by gabrieljenik** [comment]
> > A hint: This is failing as this test is being run against a revert-vue-js branch while it was done for LTS
> 
> Is it? The branch says 3.x-LTS.

I swear I saw something about revert-vue-js

**Comment by olleharstedt** [comment]
Not sure how to continue to debug. Dump HTML at failure??

**Comment by gabrieljenik** [comment]
I want to switch to use somethign like this: frameToBeAvailableAndSwitchToIt

**Comment by olleharstedt** [comment]
> Facebook\WebDriver\Exception\NoSuchElementException: Unable to locate element: #cke_question_en

This means that the page is not loaded at all? Can you put a sleep(2) before this call? Or maybe try to find all h1 and h2 tags and dump them (will tell us which page we're on).

**Comment by Shnoulle** [comment]
maybe we set config to something other tha inline HTML editor before ? Did you try to lauch all test locally @olleharstedt ?

**Comment by olleharstedt** [comment]
> maybe we set config to something other tha inline HTML editor before ? Did you try to lauch all test locally @olleharstedt ?

I tried, but it's _really_ slow.

**Comment by olleharstedt** [comment]
I tried to run this test with different HTML editor options, it worked for all alternatives.

**Comment by gabrieljenik** [comment]
> > Facebook\WebDriver\Exception\NoSuchElementException: Unable to locate element: #cke_question_en
> 
> This means that the page is not loaded at all? Can you put a sleep(2) before this call? Or maybe try to find all h1 and h2 tags and dump them (will tell us which page we're on).

I have already tried adding a sleep(10) I think. Didn't work.
Changed the approach on how to get the div. Didn't work either.
I will try to add some echoing of html to check what is rendered.

**Comment by olleharstedt** [comment]
Does the test work if you _only_ run this test? You can edit it in .travis.yml file.

**Comment by gabrieljenik** [comment]
Ran good with a single test! Very strange!
`The command "DOMAIN=localhost ./third_party/bin/phpunit --filter EditQuestionTest" exited with 0`

**Comment by gabrieljenik** [comment]
Testing changing the order in which the tests run

**Comment by Shnoulle** [comment]
Even if update order fix the issue : we need to find what happen before ;)

**Comment by gabrieljenik** [comment]
Now failed on another. I will find out. I see some collisions.

**Comment by olleharstedt** [comment]
Also try running phpunit with `--testdox` to see the names of the tests being run.

**Comment by olleharstedt** [comment]
Another try could be to use a separate survey to import instead of current one, so that not two tests use the one survey. Not sure it matters, but maybe.

**Comment by Shnoulle** [comment]
> Now failed on another. I will find out. I see some collisions.

Yes, but this one is OK. If ChangeQuestionTemplateTest::testChangeQuestionTemplate happen after the same, it's the previous one that break …
The previous one update something but don't reset :)

**Comment by Shnoulle** [comment]
> Also try running phpunit with `--testdox` to see the names of the tests being run.

Question : you see all test ? For example

```
ls\..\testOne : OK
ls\..\testTow : OK
…
```

If yes : surely a great idea :)

**Comment by gabrieljenik** [comment]
> Another try could be to use a separate survey to import instead of current one, so that not two tests use the one survey. Not sure it matters, but maybe.

I think there is some kind of problem. The import at EditQuestionTest was some kind of failing. When moving it up in the order, worked good, but then the testChangeQuestionTemplate is failing. EditQuestionTest  has a TearDown method, so it is not supposed to be an issue. I will double check

> Also try running phpunit with `--testdox` to see the names of the tests being run.
Good!

**Comment by gabrieljenik** [comment]
Either teardownAfterClass is not being run or self::$testSurvey is not being reset. Keep on investigating

**Comment by Shnoulle** [comment]
The deletion seems partially OK … https://travis-ci.org/github/LimeSurvey/LimeSurvey/jobs/729673984 

Realy hard to fix here …

**Comment by gabrieljenik** [comment]
Last test, changing the survey file, worked good.
Not sure how that made a difference. I will double check.

Also, smell, something is wrong with the cleanup.
I think the problem is we should be using static sometimes, and we are using self.

**Comment by gabrieljenik** [comment]
https://bugs.limesurvey.org/view.php?id=16692

I will review what's wrong and fix it :)

**Comment by gabrieljenik** [comment]
We have green Travis!

**Comment by Shnoulle** [comment]
About lss file : i think it's best if they have a name in relation with the test done (or a functionality).

**Really more easy** for other dev to check and test when try to update something.

**Comment by olleharstedt** [comment]
> About lss file : i think it's best if they have a name in relation with the test done (or a functionality).

Yeah, I agree with this, Denis.

**Comment by olleharstedt** [comment]
> Also, smell, something is wrong with the cleanup.
> I think the problem is we should be using static sometimes, and we are using self.

Yeah, clean-up is hacky. One reason I want to move more to unit-tests with mocking. But integrity tests like these are needed too. Thanks for fixing!!

**Comment by Shnoulle** [comment]
next time : please, clear name for lss …

**Comment by gabrieljenik** [comment]
> next time : please, clear name for lss …

Yes, I iwas just keeping status quo. Does it worth to rename all current files and deduplicate if any is duplicate?

**Comment by Shnoulle** [comment]
> Yes, I iwas just keeping status quo.

I just speak for new files, current status quo i set a clear name for new test … , it's best to review previous one, but take time.

**Pull request merged**
