### PR TITLE
Fixed issue #13520: Unable to import theme

### PR DESCRIPTION
**Pull request by TonisOrmisson**
https://bugs.limesurvey.org/view.php?id=13520

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
Like that maybe?

**Comment by Shnoulle** [comment]
Oh , maybe let me check again ;)

**Comment by Shnoulle** [comment]
@TonisOrmisson not only this : deleted directory, uninstall template : same sentence …

**Comment by Shnoulle** [comment]
Sorry : @TonisOrmisson : this fix the issue :).  See review comments

**Pull request merged**
