### PR TITLE
Fixed issue #16741: Filtering on responses for questions of type Array Dual Scale was not working in Statistics

### PR DESCRIPTION
**Pull request by gabrieljenik**
Reapplied PR https://github.com/LimeSurvey/LimeSurvey/pull/1062/ on master.

### CODE REVIEW

**Comment by cdorin93** [comment]
Hey @gabrieljenik , have time to check why travis is red?

**Comment by gabrieljenik** [comment]
Seems there is something on this PR that made the installer to fail.
https://github.com/LimeSurvey/LimeSurvey/pull/1589

**Comment by gabrieljenik** [comment]
The strangest is that PR is to LTS, not master. How did that get there?
This is the PR that should have been merged.
https://github.com/LimeSurvey/LimeSurvey/pull/159

I think the best is to reverse this https://github.com/LimeSurvey/LimeSurvey/commit/499ddee66bbe429364e9b481fa934f42ab1e0062
(I don't have the permissions for doing this)

And then all travis will be green, including being able to merge this:
https://github.com/LimeSurvey/LimeSurvey/pull/1591

**Comment by gabrieljenik** [comment]
Haven't tested that those stpes will work, but defintely worth trying thatbefore moving forward with the review :)

**Pull request merged**
