### PR TITLE
FIX: Typecheck the XML variable from the GroupImport method

### PR DESCRIPTION
**Pull request by Kbroeren**
Removed the validation from the groupimport just as the questionimport method becaus the validation always match the false state. So the groupimport can never be used.

### CODE REVIEW

**Comment by tammoterhark** [comment]
Kevin: contactformulier op je site werkt niet, daarom maar zo:

https://www.limesurvey.org/forum/development/111625-dutch-user-group-of-limesurvey

**Comment by Shnoulle** [comment]
Not best with $xml === false ? If lsg it's not an xml ? (and same must be applied to lsq if it's not the case)

**Comment by Kbroeren** [comment]
@Shnoulle thats another option.. that also works. We can do the same for the question import. Then we have also type checking. I will update my PR

**Comment by Kbroeren** [comment]
Thanks @Shnoulle. I have changed the message. Everything OK now ?

**Pull request merged**
