### PR TITLE
Trim entered e-mail addresses

### PR DESCRIPTION
**Pull request by fkroener**
Smartphone keyboards often enter additional whitespaces, trim them.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Must save as trim too , no ? Here you validate as trim, but don't trim when saved .

**Comment by fkroener** [comment]
I tested it and emails were transmitted anyway. Let me check email details.

**Comment by Shnoulle** [comment]
If transmitted/saved in DB but can not be sent ...

**Comment by fkroener** [comment]
How do you mean? I tried " email@example.com " and the email was sent and properly received. When checking partcipant table the email appears as "email@example.com".

**Comment by Shnoulle** [comment]
Ok,

Else : mantis issue please ?
https://github.com/LimeSurvey/LimeSurvey/blob/master/CONTRIBUTING.md#getting-started

**Comment by fkroener** [comment]
https://bugs.limesurvey.org/view.php?id=16037 there you go.

**Comment by olleharstedt** [comment]
If this is a bug in 3.x it has to be a PR to branch 3.x-LTS, not master (or maybe both).

**Comment by olleharstedt** [comment]
I'll cherry pick this into 3.x.

**Pull request merged**
