### PR TITLE
Fixed issue #18158: `Property "CDbCriteria.qid" is not defined` status returned by delete_question

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Fixed issue [#18158](https://bugs.limesurvey.org/view.php?id=18158): `Property "CDbCriteria.qid" is not defined` status returned by `delete_question`

### CODE REVIEW

**Comment by Shnoulle** [comment]
Seems unneeded when use ->delete : https://github.com/LimeSurvey/LimeSurvey/blob/2cced37bb82839792c2e4ecfbcf5d7a0e51163de/application/models/Question.php#L394

Best is to move to $questtion->findByPk($qid)->delete after other control is done.

**Review by Shnoulle — CHANGES_REQUESTED** [review]
At https://github.com/LimeSurvey/LimeSurvey/blob/74db1e4d8dde21f49ccd212eb1eff925d79c8c7a/application/helpers/remotecontrol/remotecontrol_handle.php#L1435

replace by $question->delete please :)

**Comment by edgarrmondragon** [comment]
@Shnoulle thanks for reviewing, I've updated the method to use `->delete()`

**Comment by Shnoulle** [comment]
I do the test , thanks to you !

**Pull request merged**
