### PR TITLE
Fixed issue #15057: Translation screen not working correctly when there are long question text

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by glimz** [comment]
@gabrieljenik We also need a PR for master

**Comment by Shnoulle** [comment]
test failed overflow:auto don't work on cell.
`word-wrap: break-word;` seem best 
Capture d’écran du 2022-02-28 11-39-29

**Review by Shnoulle — CHANGES_REQUESTED** [review]
overflow didn't work.

Maybe update a little html ? Give specific class to each cell ? .code, .text, .input ?

**Comment by Shnoulle** [comment]
I see the change : if we add a div : unsure we need word-wrap …

I don't know here what is the best solution …

**Comment by gabrieljenik** [comment]
I think the word-wrap can help in some cases where we have simple text or formatted text.
It doesn't bother, but it helps.

We forsee some cases that may not be great looking, as below.
But I guess that to tackle those, we may need a new ticket as it needs a bigger intervention and rethinknig this screen (as for example using Flex).

image

**Review by Shnoulle — APPROVED** [review]

**Pull request merged**
