### PR TITLE
Dev : fix for usergroup view when admin

### PR DESCRIPTION
**Pull request by papa-mb**
Fixed issue # : 
New feature # :
Changed feature # :
Dev: fix for usergroup view when admin
Dev:

### CODE REVIEW

**Comment by papa-mb** [comment]
Hi, 
It's just a fix for a bug in the view of groups when you are superadmin. There was a message that said that there's a call to a non object

**Comment by lacrioque** [comment]
You removed a check if the user is not a superadmin, this is a rather critical call.
Can you maybe change it to check if the permission model exists instead of removing the call to it?

**Comment by Shnoulle** [comment]
> You removed a check if the user is not a superadmin, this is a rather critical call.

In fact : this disable super-admin to see all survey … if super admin didn't create an user and not in his group : he don't see this user survey …

@papa-mb : best is to tell us exactly where you have this issue …

**Comment by c-schmitz** [comment]
Closed due to lack of feedback and that the reason for this whole patch is uknown.

**Pull request closed without merging**
