### PR TITLE
Fix some part of new datetime 

### PR DESCRIPTION
**Pull request by Shnoulle**
- Use fontawesome for datetime question
- Add a label for accessibilty : must test whole system with screen reader
- registerScript in replace of included script. Tested : seem not needed ?

### CODE REVIEW

**Comment by c-schmitz** [comment]
See also https://eonasdan.github.io/bootstrap-datetimepicker/Options/#icons

**Comment by Shnoulle** [comment]
No, because yiiwheels update html in PHP not only in JS : https://github.com/LimeSurvey/LimeSurvey/blob/master/application/extensions/yiiwheels/widgets/datetimepicker/WhDateTimePicker.php#L78

You're right : alternate solution can be : 
Add our input only, ,and update it in JS only to add the input-group and icon.

The 2 solution are valid, and we have a third
- Use yiiwheels : actual solution
- Add an input and do it with some JS file and option inside HTML
- Create a LS extension for inpu (near same than SettingsWidget but with views etc ....)

**Comment by c-schmitz** [comment]
You can update the YiiWheels widget directly for the surrounding HTML. I updated it anyway to accomodate the new datetimepicker library.

**Comment by Shnoulle** [comment]
Then : it's not the official yiiwheel ? A sort of LS for of yiiwheel ?

**Comment by c-schmitz** [comment]
The official yiiwheel is inactive, we use the latest version and I modified datetimepicker to get the bugs out.

**Pull request closed without merging**
