### PR TITLE
Fixed issue #16506: Fruity theme: question type Matrix (texts), you do not see the sums of the total columns and grand total.

### PR DESCRIPTION
**Pull request by gabrieljenik**
Updating CSS clasess for the inputs as to have the data to be more visible

### CODE REVIEW

**Comment by Shnoulle** [comment]
There already a css for total ? text-info or something lime this didn't work ?

**Comment by gabrieljenik** [comment]
image
Yes, css class was there

**Comment by Shnoulle** [comment]
:( i didn't like usage of class like this … i prefer to use `ls-total-sum` or a boostrap class.

we remove `.odd` `.even` usage :(

**Comment by gabrieljenik** [comment]
ok, let me try with ls-total-sum

**Comment by gabrieljenik** [comment]
ls-total-sum is not defined in the css.
Adding it may imply bigger changes for updating all the variations and also all the derived themes.

On the other hand, the total class definition is there and seems to fit what was designed for.

Alternatives: 

### 1 - Rename the total clase?
.total -> ls-sum-total

### 2 - Add exception rule
The text is currently very light and is not visible because of this defintion.
image

So, an alternative solution would be to add an exception to that definition in the case they are in the total row / column.
In that case, they would use the inherited.
image

But that again will require to update all variations.

**Comment by Shnoulle** [comment]
> But that again will require to update all variations.

Yes : keep total is the quickest way , but i dislike ;)

**Comment by eddylackmann** [comment]
@Shnoulle  at least we have to review our css classes in the future und redefine them in a proper way but it still a low priority for the moment.

**Review by eddylackmann — APPROVED** [review]

**Comment by Shnoulle** [comment]
Yes , already said that. `total` seems unclear to me . I already update some css class in 3.X , somes other still there like this one 

We must just remind of this when adding new class name …

**Pull request merged**
