### PR TITLE
Dev: missing spaces in title_bar between survey title and brackets

### PR DESCRIPTION
**Pull request by TonisOrmisson**
Dev: missing spaces in title_bar between survey title and brackets

### CODE REVIEW

**Comment by LouisGac** [comment]
good  PR again. 
You just forgot to put "Dev:" in  front of your commit messages
see: https://manual.limesurvey.org/Standard_for_Git_commit_messages

**Comment by TonisOrmisson** [comment]
Thanks. I just was a bit lazy to create/search for an issue :) 
It has just bugged my eye for a while ...

**Comment by Shnoulle** [comment]
We must not use sprint_f here ?

Else @TonisOrmisson maybe you can rebase your repo

**Comment by TonisOrmisson** [comment]
@Shnoulle I am not that fluent with collaboration, so I'm just getting used to that. Thanks, rebased.

**Comment by maziminke** [comment]
Thanks a lot for the - once more - great contributions. I had started fixing some of these issues but it turned out that there are so many files affected...
Well done!

**Pull request merged**
