### PR TITLE
Ckeditor 4, Data Policy, Label Sets, Email Templates, Question Organizer

### PR DESCRIPTION
**Pull request by gabrieljenik**
DEV: Added CKEditor v4
DEV: Restored LS3 Global Settings for HTML Editor
DEV: Rebuild Data Policy Screen
DEV: Rebuild Labelsets Screen
DEV: New HTML Modal Editor: Different than the Regular HTML Editor on PopUp mode, which opens on a new screen.
DEV: Modal HTML Editor for LabelSets

### CODE REVIEW

**Comment by gabrieljenik** [comment]
@olleharstedt For your reviewal

**Comment by Shnoulle** [comment]
@gabrieljenik CKeditor4 can be tested here ?

**Comment by olleharstedt** [comment]
Nice :balloon:

**Comment by gabrieljenik** [comment]
> @gabrieljenik CKeditor4 can be tested here ?

Actually, I think I am missing a file to push.
Sorry, will be back with you soon

**Comment by gabrieljenik** [comment]
Label sets screen needs some refinement.
As for example: 
- When adding new items on the label set, the popup editor is used. Later on the modal one. We should be using always the modal one.
- When adding new items, beahviour is fuzzy when loosing focus.

Will update soon

**Comment by gabrieljenik** [comment]
When testing, please remember to reset the global configuration for the html editor, as that option has been restated also.

**Comment by gabrieljenik** [comment]
I fon't like how labelset adding screen flow is, still is the same as in LS3. We may enhance it, although I am not sure you want to do it now.

**Comment by olleharstedt** [comment]
> We may enhance it, although I am not sure you want to do it now.

Not now, getting LS4 production ready is top priority.

**Comment by gabrieljenik** [comment]
Merged LS/develop into this.

# About porting question orgaizing
- Had to add jquery-ui to AdminTheme.php. Otherwise, it doesn't work when loaded by ajax (jquery-ui goes on HEAD).
- Added Save button using "showSaveButton" from Top Bar Vue component. In LS3, there is also a Save and Close button. Could be added (if it doesn't already work) when Top Bar is reverted.
- There are issues with beforeunload, already present in LS3. Question organizer sets the beforeunload event to show an alert when leaving the page without saving, but there are two issues:
1) Doesn't work when loaded by ajax because it uses window.onload (not needed)
2) Submit is not properly recognized, so the message is also shown when Save button is clicked.

**Comment by Shnoulle** [comment]
> Had to add jquery-ui to AdminTheme.php. Otherwise, it doesn't work when loaded by ajax (jquery-ui goes on HEAD).

Shit, we still use jquery-ui …

I don't check other part but know there are a lot opf issue about «««ajax»»» badly integrated in LimeSurvey …

**Comment by gabrieljenik** [comment]
> I don't check other part but know there are a lot opf issue about «««ajax»»» badly integrated in LimeSurvey …

Something we have been noticing is that pjax doesn't work well with scripts registered as packages. But if we register scripts as registerScript, it works well. Still, this is a good point. Is pjax going to be used on the new LS4? or the whole page will be refreshed all time (old fashioned) @olleharstedt  @Shnoulle

**Comment by Shnoulle** [comment]
registerPackage can be extended … and it must be **before** adding ajax as stable … 

See https://bugs.limesurvey.org/view.php?id=16558 and https://bugs.limesurvey.org/view.php?id=16559

**Comment by olleharstedt** [comment]
We didn't discuss pjax yet, needs to be checked what it does and if it actually brings some value to the customer.

**Comment by olleharstedt** [comment]
This is the wrong URL in the test: 

> "FAILED viewing createSurvey on route survey/sa/newsurvey, full url http://localhost/index.php?r=admin/survey/sa/newsurvey"

Correct URL is

> http://localhost/index.php?r=surveyAdministration/newSurvey

It will be fixed automatically after you resolve the merge conflicts.

**Comment by gabrieljenik** [comment]
@olleharstedt Why the route for surveyadministration uses a different survey i parameter? isn't that going to broke security matters which could be standarized?

**Comment by gabrieljenik** [comment]
> @olleharstedt Why the route for surveyadministration uses a different survey i parameter? isn't that going to broke security matters which could be standarized?

Also, friendly urls I think could have got broken. Have to double check. Not sure if you already have it on your radar

**Comment by gabrieljenik** [comment]
At last, sorry, I need some guidelines on how to move actions to the new surveyAdministration controller.

actionOrganize needs to be migrated.
I stumbled with changed on how to pick parameters and with views. I was able to solve that.

But later I got errors while rendering topbar, which seems to be still in Vue.
Could be good to review that.

**Comment by gabrieljenik** [comment]
@Trischi80 Please, can you look at my comments below? I could use your input and I think some could be interesting for you. Thansk!

**Comment by olleharstedt** [comment]
Thanks, Gabriel!

**Pull request merged**
