### PR TITLE
removed API restriction to prevent survey ownership transfer

### PR DESCRIPTION
**Pull request by gekkedev**
Just thought this would be useful as we are working with a superuser anyway and there is no separate function for this.

Fixed issue # : 
New feature # :
Changed feature # :
Dev: 
Dev:

### CODE REVIEW

**Comment by Shnoulle** [comment]
NOOOOOOOOOOO ! Use Persmission::model . Allowed only if you are able to do.

**Comment by Shnoulle** [comment]
> we are working with a superuser anyway

False : any user can be used for API

**Comment by gekkedev** [comment]
Just checked, and the unset-block is already encapsed by `if (Permission::model()->hasSurveyPermission($iSurveyID, 'surveysettings', 'update'))`. Am I right that this is restricted enough?
I'm just suggesting that we remove this and a few other restrictions on the API to create new possibilities. For example the survey language.

**Comment by Shnoulle** [comment]
Must look at GUI, but i think $aSurveyData['owner_id'] must test too if user are allowed to see the new owner_id (or must be).

But you have right on a part : we allow it to update via admin part (survey settings) => must be allowed in API on the same way.

**Comment by gekkedev** [comment]
I am currently developing a small api connector for testing purposes, and with the default admin i was able to retrieve the user id on a newly created survey. Just changing it was a problem, kinda readonly.

**Comment by Shnoulle** [comment]
Actually : you're right : model must control if update owner is OK for user connected :). Then 👍

**Comment by gekkedev** [comment]
do I need to add anything?

**Pull request merged**
