### PR TITLE
Fixed issue #12422: Error 500 while massive-delete question

### PR DESCRIPTION
**Pull request by TonisOrmisson**
https://bugs.limesurvey.org/view.php?id=12422

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
also fixed 12442: Massive-delete questions fails to delete some questions
https://bugs.limesurvey.org/view.php?id=12442
//TODO would be nice to see the error message in the output also

**Comment by TonisOrmisson** [comment]
ups
I have the 
https://github.com/LimeSurvey/LimeSurvey/pull/696/files
code also in this merge.

**Comment by TonisOrmisson** [comment]
all good now

**Comment by Shnoulle** [comment]
For error : i didn't test here : but seems Yii send a json error if json is asked (see https://github.com/LimeSurvey/LimeSurvey/commit/9e6f7222296bca76813aa111a6f1ceafb62a24f0#diff-981b94432ee932d7e6aee07a1fb7cadbR89 ) . Unsure here, but maybe ....

**Pull request merged**
