### PR TITLE
Fixed issue #16142: Deleting a participant after he/she started the survey keeps the survey available

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: unset invalid token ($oToken is null)

### CODE REVIEW

**Comment by Shnoulle** [comment]
This is a quick fix currently, i think we need a better system to check valid / invalid token .
Unsure if in SurveyRuntimeHelper or somewhere else ?

Maybe a new getCurrentToken function, validate and /or throw error.

**Comment by olleharstedt** [comment]
Should same fix be cherry-picked into master?

**Comment by Shnoulle** [comment]
Yes, surely, i do it after.

**Comment by olleharstedt** [comment]
OK, we just need someone to test this. @cdorin93 Busy, busy?

**Pull request merged**
