### PR TITLE
DEV: Add click tests (travis)

### PR DESCRIPTION
**Pull request by TonisOrmisson**
Added few examples of testing views that need a post click to open the view. 

Also refactored the CreateSurveyTest since I had some trouble with that. Followed the principle of having one assertion per test to keep it more debuggable and clear.

### CODE REVIEW

**Comment by c-schmitz** [comment]
@TonisOrmisson Update needed.
@olleharstedt Review needed - if okay please merge.

**Comment by TonisOrmisson** [comment]
This one depends on the test folder restructure which was redirected to master and is still unmerged. Ill hold on that until this gets done and merged back into develop

**Comment by olleharstedt** [comment]
Cool! 

Sorry, we're busy with breaking bugs in 3.0 right now, so clean-ups will have to wait a little.

**Comment by c-schmitz** [comment]
Why did you close it?

**Comment by TonisOrmisson** [comment]
I do not have time to check this

**Comment by c-schmitz** [comment]
@Olle? Keep or close?

**Comment by olleharstedt** [comment]
If it works, why not merge it into dev?

**Comment by c-schmitz** [comment]
Conflicts?

**Pull request closed without merging**
