### PR TITLE
DEV: Restructure tests folder

### PR DESCRIPTION
**Pull request by TonisOrmisson**
#925 
moved to master

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
I also changed the tests namespace from ls to LimeSurvey. It seems this one is used elsewhere

**Comment by olleharstedt** [comment]
OK, so my understanding of the categories is like this:

1. Acceptance = anything that uses Selenium/headless browser, and/or writes to files/database
2. Functional = anything that writes to files/database but does NOT use Selenium
3. Unit = anything that does NOT write to files/database NOR uses Selenium

Correct?

**Comment by TonisOrmisson** [comment]
I understand it pretty much the same.

**Comment by olleharstedt** [comment]
OK, then I'll merge.

**Pull request merged**
