### PR TITLE
Dev: Allow upload of txt and md files

### PR DESCRIPTION
**Pull request by Jan-E**
Do https://github.com/LimeSurvey/LimeSurvey/pull/316 in the 2.06 branch as well.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Great, but before merging, please : https://manual.limesurvey.org/Standard_for_Git_commit_messages for comit message.
Then here `Dev: Allow ...` ;)

**Comment by Jan-E** [comment]
See changed commit message.

**Comment by Shnoulle** [comment]
No, sorry, you update the title, but not the commit message, see https://github.com/LimeSurvey/LimeSurvey/commit/df6dacc733129482a3f458f8e4c998a842c7ef1b .

I think the easiest is to close this one and do a new commit with just the commit (and more : you can use edit this file at https://github.com/LimeSurvey/LimeSurvey/blob/master/application/config/config-defaults.php to do a new commit and push request :) )

**Comment by Jan-E** [comment]
I had been looking for a way to change the title of a commit that is already pushed, but apparently there is no easy way. Here is a new one:
https://github.com/LimeSurvey/LimeSurvey/pull/318

**Comment by Shnoulle** [comment]
Thanks :)

**Pull request closed without merging**
