### PR TITLE
Fixed issue #16604: Adding condition triggers bulk update for complete database

### PR DESCRIPTION
**Pull request by gabrieljenik**
If surveyId is not given but qid is, fetch surveyd from the question

### CODE REVIEW

**Comment by gabrieljenik** [comment]
Same fix could be applied here.
https://github.com/LimeSurvey/LimeSurvey/blob/bd038776d000dfd4fc629d5f3455a2548e3ec10b/application/helpers/expressions/em_manager_helper.php#L8618

Not sure it is worth it, as it is only called from here.
I would do it, what do you think? @olleharstedt

**Comment by Shnoulle** [comment]
A fix on `$LEM =& LimeExpressionManager::singleton(); ` ???

**Comment by Shnoulle** [comment]
Oh no : you mean : usage of `onlythisqid` variable :).

:+1:

**Comment by gabrieljenik** [comment]
Yes. Not sure it is worth it. What do you think?

**Comment by Shnoulle** [comment]
> Yes. Not sure it is worth it. What do you think?

```
            if (is_null($iSurveyID) && $onlythisqid) {
                $oQuestion = Question::model()->find("qid = :qid", array(":qid"=> $onlythisqid);
                if($oQuestion) {
                    $iSurveyID = array($oQuestion->sid);
                }
            }
```
just before https://github.com/LimeSurvey/LimeSurvey/blob/bd038776d000dfd4fc629d5f3455a2548e3ec10b/application/helpers/expressions/em_manager_helper.php#L8619

This fix without update. But in my opinion : must check if $onlythisqid and $iSurveyID are compatible, throw error if not.

**Comment by gabrieljenik** [comment]
So far I think this can be closed. This will probably not be tested nor merged. Already merged in master. So, let me know if this should be closed.

**Comment by olleharstedt** [comment]
Don't close yet, please. LS3 might live long still.

**Comment by olleharstedt** [comment]
Alternatively we can cherry-pick the fix from master into 3.x-LTS.

**Comment by gabrieljenik** [comment]
This is the patch done for 3.x LTS. Not cherry picked but done with the same spirit. Not sure you can cherry pick.
The biggest issue is testing this is hard

**Comment by olleharstedt** [comment]
But you can test it doesn't break anything?

**Comment by gabrieljenik** [comment]
That's the biggest part to test.

**Comment by olleharstedt** [comment]
Travis is red?

**Comment by gabrieljenik** [comment]
Seems so, but I believe it is not because of the code.

```
0.10s$ wget localhost
--2020-08-25 17:08:38--  http://localhost/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-08-25 17:08:38 ERROR 500: Internal Server Error.
```

**Comment by olleharstedt** [comment]
Or? :) 

PHP Parse error:  syntax error, unexpected ';' in application/helpers/expressions/em_manager_helper.php on line 8628

**Comment by gabrieljenik** [comment]
Strange. This is so old and I am sure we have been through this and did testing!
Nevermind, will review it

**Comment by gabrieljenik** [comment]
Pushed a fix in the code.
Let's see what travis has to say :)

**Review by gabrieljenik — COMMENTED** [review]
> Or? :)
> 
> PHP Parse error: syntax error, unexpected ';' in application/helpers/expressions/em_manager_helper.php on line 8628

Fixed. Travis green

**Pull request merged**
