### PR TITLE
Fixed issue #18184: cpd_importParticipants with encryption turned on, fails to save the participant encrypted in CPDB, causing 500 error to CPDB

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]
Seems OK,

But need big testing in my opinion …

related pull request : https://github.com/LimeSurvey/LimeSurvey/pull/2149/files

**Comment by gabrieljenik** [comment]
@olleharstedt As this seems to require lot of testing, should we push to develop?

**Comment by gabrieljenik** [comment]
Will be creating a ticket for this.

**Comment by gabrieljenik** [comment]
Automatic test added.

**Review by Shnoulle — APPROVED** [review]

**Comment by olleharstedt** [comment]
> @olleharstedt As this seems to require lot of testing, should we push to develop?

This is fixed now? Master is ok?

**Comment by gabrieljenik** [comment]
> This is fixed now? Master is ok?

This PR holds the fix and also an automatic test.

**Pull request merged**
