### PR TITLE
Develop textarea relevance subquestion

### PR DESCRIPTION
**Pull request by Shnoulle**
New feature : Usage of textearea for equation in sub question
Dev: textarea is really great for equation (needed ?)
Dev: here : have a little css glitch …

The css glitch can be easily fixed but since i can't gulpify admin css without error …

### CODE REVIEW

**Comment by Shnoulle** [comment]
Why closing without any information ? It still great to have textarea for relevance and not text input.

And here : only css glitch (one line textarea still biggger than needed)

**Comment by Shnoulle** [comment]
This update 
This
capture d ecran du 2019-02-19 14-23-51

To this
capture d ecran du 2019-02-19 14-25-18

And it's REALLY better for admin usage of Expression !

**Comment by Shnoulle** [comment]
oups

**Comment by maziminke** [comment]
Great improvement!

**Pull request merged**
