### PR TITLE
Fixed issue : enforce the mandatory token field + show warning if the import csv file contains ignored columns

### PR DESCRIPTION
**Pull request by sieutruc**
> Quote here.
>
> -- <cite>@c-schmitz 
f you could create this patch for 2.5 this would be great.
I also note that your variable naming is not correct.
For explanations please have a look at https://manual.limesurvey.org/Coding_guidelines
and 
https://manual.limesurvey.org/Coding_guidelines#Localization
</cite>

I've developped another patch for the version 2.05 and fixed design a bit. Voila, here the result is : 
lime_warning

Can you tell me if it will be accepted ? or any suggestion ?

### CODE REVIEW

**Comment by sieutruc** [comment]
for more infos, the steps in order to use this feature:
* Create a survey
* Create a token table
* Add 3 additional attributes, 2 of them are mandatory (att1, att2)
* Import token by csv : in this csv file, there are 2 attributres  att1, att4

Choose "show warning attributes" when importing the csv.

Result : 

att2 is missing, att4 is ignored.

**Comment by Shnoulle** [comment]
Not sure if it's Cartsen or @LouisGac

**Comment by sieutruc** [comment]
Hello,

Any comment for this feature ?  Or would you like something more ?

**Comment by LouisGac** [comment]
Hey, sorry, we're deeply into debugging right now. But still, it looks great. Carsten will take the decision.

**Comment by sieutruc** [comment]
Hello,

Do you have any news for me on this request ?

**Pull request merged**
