### PR TITLE
Feature/new plugin event after token table create

### PR DESCRIPTION
**Pull request by KRav007**
A new plugin event after a new token table was created.
For example: you could add attribute fields programmatically

### CODE REVIEW

**Comment by Shnoulle** [comment]
Hi, think it can help, but same system for survey table creation can be a great idea ...
Not now, but rename the event to : afterTableCreate (or before, unsure) with something like this:

````
$event = new PluginEvent('afterTableCreate');
$event->set('surveyId', $iSurveyId);
$event->set('type', 'token');
$event->set('name', $tableName);
App()->getPluginManager()->dispatchEvent($event);
````

And this function MUST be moved to model : Token::createTable($iSurveyId); , else it don't happen for Remote control (for example) or with another plugin table creation.

**Comment by SamMousa** [comment]
Let's not do that refactoring in 2.x. LS3 already has Token:: createTable
BTW.

**Comment by KRav007** [comment]
What means "refactoring". Do you talk about the naming? I could need this kind of hook in 2.x.

**Comment by Shnoulle** [comment]
@SamMousa LS3 don't have an event in Token::createTable ? Because LS2 already have Token::createTable function ...... then adding an event in 2 take 5 minutes to add it to 3 too ... same place, function i surely near the same.

**Comment by SamMousa** [comment]
Feel free to add it @shnoulle

**Comment by KRav007** [comment]
I put it in the model right now and make a test

**Comment by Shnoulle** [comment]
@KRav007 : for event name / param : do you thinl it's a good idea to have same event for survey table/timing table (other table ? Why not plugin table ?) .

**Comment by KRav007** [comment]
From my point of view it would be an big advantage to hook in everywhere. This offers us the possibility to build very special custom solutions for our clients. This is the future, I think. I get more and more requests for this.

**Comment by c-schmitz** [comment]
Variable naming needs to be fixed.

**Comment by c-schmitz** [comment]
...and should be based on the latest revision.

**Comment by KRav007** [comment]
done

**Pull request closed without merging**
