### PR TITLE
dynamic group order (#13613)

### PR DESCRIPTION
**Pull request by schulzp**
* use randomization for groups approach
* use consisten handling of group re-mapping in `frontend_helper` (`UpdateGroupList`) and `em_manager_helper` (`getGroupInfoForEM`)

New feature # : https://bugs.limesurvey.org/view.php?id=13613

### CODE REVIEW

**Comment by Shnoulle** [comment]
Totally against such commit. Best way seems to add event to get final group order by ANY plugins.

For example : get group order by TOKEN attribute 

Then i'm for
- Adding new event to get final group order
- Maybe (best) use it for core Group order

**Comment by LouisGac** [comment]
also: those kind of changes should be submitted to the dev branch.

**Comment by Shnoulle** [comment]
Saying it must be submitted to develop branch mean you accept it and think it's a LimeSurvey core feature ?

The i can submit a "order by attribute" feature too … and an another order by (by server name or datetime or …)

**Comment by olleharstedt** [comment]
Can I close this?

**Comment by cdorin93** [comment]
I will close this PR.
Thank you @schulzp for your time!

**Comment by Shnoulle** [comment]
PS : in 4.X : plugin using https://manual.limesurvey.org/SetVariableExpressionEnd can be used for such system.

I do only a quick test for order (set order manually ion plugin … byt qid …), and i do a complete plugin for "hidding question in some condition" : https://gitlab.com/SondagesPro/coreAndTools/organizeSurvey

Must use 

```
       $this->getEvent()->set('knownVars',$knownVars);
        $this->getEvent()->set('questionSeq2relevance',$questionSeq2relevance);
```

**Pull request closed without merging**
