### PR TITLE
Fixed issue #15598: intval : broken interpretation of string start by integer in JS

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue : broken interpretation of boolean var for floatval
Dev: updated expression JS function, inspired by locutus

### CODE REVIEW

**Comment by Shnoulle** [comment]
WIP : don't merge before the test added.

**Comment by Shnoulle** [comment]
Updated to master

**Comment by Shnoulle** [comment]
1 test, 38 assertions

**Comment by olleharstedt** [comment]
> 1 test, 38 assertions

Nice

**Comment by olleharstedt** [comment]
Should be cherry-picked into LTS too?

**Comment by Shnoulle** [comment]
:/ unsure … i want to do it before 4.X : maybe some user use broken JS in survey (don't know how …) ?

**Comment by olleharstedt** [comment]
Good job, Denis, thank you!

**Pull request merged**
