### PR TITLE
Dev: Fixed #15048: Broken HTML in questionexplorer

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: build for production

### CODE REVIEW

**Comment by lacrioque** [comment]
I don't remember exactly why, but i had a reason to not use li there.
I think it would be better to change the <ul> toa <div>

**Comment by Shnoulle** [comment]
No issue with li. And since there are ul : it MUST be li

**Comment by lacrioque** [comment]
It is bootstraps listgroup, meaning that the ulö can easily be made to a div.
I have checked, why I used div instead of li, the rendering needs a block item in the list.
I will change the ul to div.

**Comment by Shnoulle** [comment]
Since it's a list : ul>li is better,

But … make like you want … like all time …

**Pull request merged**
