### PR TITLE
Fixed issue #18180: Calling set_participant_properties with an invalid token id throws an internal server error

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by olleharstedt** [comment]
Uh, code checked or PR tested...? Which one was done? Both?

**Comment by Shnoulle** [comment]
> Uh, code checked or PR tested...? Which one was done? Both?

Oups … code checked, not tested sorry.

**Comment by gabrieljenik** [comment]
@olleharstedt Maybe we can think of pushing to develop as to have mature it and get more testing time?

**Comment by olleharstedt** [comment]
"Testing time" only works if someone is actually testing. :D Else, we need to write unit tests for encrypted/non-encrypted cases.

**Comment by gabrieljenik** [comment]
> "Testing time" only works if someone is actually testing. :D Else, we need to write unit tests for encrypted/non-encrypted cases.

Here you are :)

**Comment by olleharstedt** [comment]
Neat!

**Pull request merged**
