### PR TITLE
Fixed issue #17773: Code name change while we updated from Edit Question screen

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by Shnoulle** [comment]
Maybe we need an option to not list such label sets for response ? Only for subquestions ?

**Comment by gabrieljenik** [comment]
> Maybe we need an option to not list such label sets for response ? Only for subquestions ?

Could be, but fell that would be another story.

Also, I found usefull the idea about moving labelsets from subquestions to answers and viceversa.
Specially when swithcing question types.

**Comment by Shnoulle** [comment]
> Also, I found usefull the idea about moving labelsets from subquestions to answers and viceversa.

Oh yes, but bad moving when subquetsioncode are less than 5 caracters ;)

**Comment by gabrieljenik** [comment]
> but bad moving when subquetsioncode are less than 5 caracters ;)

That's the fix about :)

**Comment by Shnoulle** [comment]
> > but bad moving when subquetsioncode are less than 5 caracters ;)
> 
> That's the fix about :)

And that why i propose to show it in selector , OR : hide it when it's answers.

OK for a new bug report :+1:

**Review by Shnoulle — APPROVED** [review]

**Comment by gabrieljenik** [comment]
> Code OK, must fix conflict

Fixed. Thanks!

**Comment by Shnoulle** [comment]
Still conflict and warning about DB update

**Comment by gabrieljenik** [comment]
No conflicts anymore

**Review by Shnoulle — APPROVED** [review]

**Review by Shnoulle — APPROVED** [review]

**Comment by gabrieljenik** [comment]
> @gabrieljenik pls resolve the conflict so I can merge this PR. Thanks

Done! Thanks

**Comment by glimz** [comment]
@gabrieljenik I think you can merge this after resolving the merge conflict since it might change again before I merge it.

**Comment by glimz** [comment]
Tested Ok

**Comment by gabrieljenik** [comment]
> @gabrieljenik I think you can merge this after resolving the merge conflict since it might change again before I merge it.

OK, I will. Thanks

**Comment by gabrieljenik** [comment]
> > @gabrieljenik I think you can merge this after resolving the merge conflict since it might change again before I merge it.
> 
> OK, I will. Thanks

Done! Merged!

**Pull request merged**
