### PR TITLE
Issue #12678: Save ranking question by model

### PR DESCRIPTION
**Pull request by Shnoulle**
- fix it for RemoteControl too, if RC use model …
- if RC didn't use model : he must use it ;)

### CODE REVIEW

**Comment by Shnoulle** [comment]
@TonisOrmisson at https://github.com/LimeSurvey/LimeSurvey/pull/805/files#diff-1b4fbf906de3cb701eafa9ff1bec25a6R90 : i use `$oQuestion = Question::model()->find("qid=:qid",array('qid'=>$iQuestionID));` but because there are a relation : we can not get it directly ? If you know the good way, i'm happy to learn :)

**Comment by Shnoulle** [comment]
There are issue : need to disable delete expect if question is deleted …

**Comment by Shnoulle** [comment]
Must review whole

**Comment by TonisOrmisson** [comment]
@Shnoulle 
Ideally yes it should be `$this->question`. But the relation is not defined ok
https://github.com/LimeSurvey/LimeSurvey/blob/master/application/models/QuestionAttribute.php#L62
Relation should logically be `question` instead of `qid` and I think it does actually not work well due to the missing language attribute in relation (the key is qid-language)

And `$this->question->survey->isActive` :)

**Comment by TonisOrmisson** [comment]
I think QuestionAttribute also could have a shortcut to `$this->survey` by defining the `getSurvey()`

**Comment by TonisOrmisson** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/806

**Pull request closed without merging**
