### PR TITLE
Fixed issue #17535: Error when logging in with LDAP

### PR DESCRIPTION
**Pull request by wolbernd**
Fixed issue #17535:

### CODE REVIEW

**Comment by Shnoulle** [comment]
Need a test to avoid such issue , no ?

**Comment by olleharstedt** [comment]
Back from vacation, Denis? :) We've missed you.

> Need a test to avoid such issue , no ?

Psalm checks the availability of functions, but it's only used on parts of the code-base.

**Comment by olleharstedt** [comment]
Thanks for the fix!

**Comment by olleharstedt** [comment]
Oh, someone already pushed a fix to master before this...

**Comment by Shnoulle** [comment]
> Back from vacation, Denis? :) We've missed you.
> 

Not officially, but have email.

**Pull request merged**
