### PR TITLE
Fixed issue #16461: Twice contact sentence for some error page

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #16461: Twice contact sentence for some error page
Dev: remove extra, leave contact for theme only.

### CODE REVIEW

**Comment by Shnoulle** [comment]
After
Capture d’écran du 2020-07-06 17-02-19

**Comment by Shnoulle** [comment]
After
Capture d’écran du 2020-07-06 17-09-26

**Comment by sushmanadendlals** [comment]
Tested the issue by pulling the PR. Working as expected.

**Comment by olleharstedt** [comment]
Thanks!

**Comment by Shnoulle** [comment]
Must look at master :/

**Pull request merged**
