### PR TITLE
added new PluginEvent beforeAction

### PR DESCRIPTION
**Pull request by mbischof**
Fixed issue # : 
New feature # : new PluginEvent beforeAction
Changed feature # :
Dev: 
Dev:

### CODE REVIEW

**Comment by Shnoulle** [comment]
We already have beforeControllerAction https://github.com/LimeSurvey/LimeSurvey/blob/580f4e8d201d340254b6caccf3dcd3d299d21b41/application/core/LSYii_Application.php#L314

I really think we don't need another event

**Comment by mbischof** [comment]
hmm, maybe duplicates https://github.com/LimeSurvey/LimeSurvey/blob/master/application/core/LSYii_Application.php#L320

**Comment by Shnoulle** [comment]
https://manual.limesurvey.org/BeforeControllerAction

**Comment by mbischof** [comment]
Plugin Event "beforeControllerAction" needs to be mentioned in the wiki at least

**Comment by Shnoulle** [comment]
It was : https://manual.limesurvey.org/Plugin_events

**Pull request closed without merging**
