### PR TITLE
Fixed issue #16288: Bad character encoding when export file as zip

### PR DESCRIPTION
**Pull request by gabrieljenik**
Porting fix from commit 7dc3a93 to LS4

### CODE REVIEW

**Comment by olleharstedt** [comment]
Pull new Travis config.

**Comment by gabrieljenik** [comment]
> Pull new Travis config.

Will wait to see how this goes. If good, will update the rest.

**Comment by gabrieljenik** [comment]
> > Pull new Travis config.
> 
> Will wait to see how this goes. If good, will update the rest.

Ready

**Comment by olleharstedt** [comment]
Thanks!

**Pull request merged**
