### PR TITLE
token email fix and feature

### PR DESCRIPTION
**Pull request by Shnoulle**
- Feature [#09668:](https://bugs.limesurvey.org/view.php?id=9668) attachment in beforeTokenEmail
- Fix [#12243](https://bugs.limesurvey.org/view.php?id=12243): beforeTokenEmail didn't happen for remote control
- Feature [#12244](https://bugs.limesurvey.org/view.php?id=12244): customheaders in beforeTokenEmail

### CODE REVIEW

**Comment by LouisGac** [comment]
why just a PR? are you 100% it's working? If yes, we should merge it.

**Comment by Shnoulle** [comment]
Becaus : i think there are more work too to do finally 

1. Create a real new Class/helper to send email
2. Add the event beforeEmail globally
3. And there are a new feature => develop or master ?

**Comment by LouisGac** [comment]
I think right now we should close the PR for master, and ask people to do their PR in develop branch. That's why I'm cleaning the PR queue. If you want to close this PR to merge it to develop: seems good to me... at the same time, it's fixing some bugs... so it's up to you.

**Comment by Shnoulle** [comment]
I'm working on https://framagit.org/SondagePro-LimeSurvey-plugin/eventBeforeTokenEmailExtended currently

**Pull request closed without merging**
