### PR TITLE
Remove sourceMappingURL from assets

### PR DESCRIPTION
**Pull request by ddzieduch**
Remove sourceMappingURL from js and css files which generates 404 error in console.

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]

**Comment by Shnoulle** [comment]
Thanks !

@c-schmitz : really think it's a good improvment :) we can merge ?

**Comment by c-schmitz** [comment]
@thedirtypanda can you please check this?

**Review by thedirtypanda — APPROVED** [review]
Looks fine.

**Comment by c-schmitz** [comment]
@thedirtypanda  Please update the commit message before you squash/merge.

**Pull request merged**
