### PR TITLE
Fixed issue #18808: Mandatory soft only works once per survey if over multiple pages/groups

### PR DESCRIPTION
**Pull request by Shnoulle**

### CODE REVIEW

**Comment by Shnoulle** [comment]
Shit … `   │ Facebook\WebDriver\Exception\UnrecognizedExceptionException: Element <a id="mandatory-soft-alert-box-modal" class=" btn btn-outline-secondary "> could not be scrolled into view`

Have same issue locally with submit button.

**Comment by Shnoulle** [comment]
OK :) 

`Curl error thrown for http POST to /session with params:`

**Review by gabrieljenik — APPROVED** [review]
Code looks OK. Seems it was added not long ago for mandSoft.

**Comment by gabrieljenik** [comment]
> Have same issue locally with submit button.

You can look at screenshots (if error) or take a screenshots. They will be uploaded to the job-run as artifacts.

**Comment by Shnoulle** [comment]
> You can look at screenshots (if error) or take a screenshots. They will be uploaded to the job-run as artifacts.

I found it : 

```
            $mandatorysoftButton = self::$webDriver->wait(10)->until(
                WebDriverExpectedCondition::elementToBeClickable(
                WebDriverExpectedCondition::elementToBeClickable(
                    WebDriverBy::cssSelector('#mandatory-soft-alert-box-modal')
                    WebDriverBy::id('mandatory-soft-alert-box-modal')
                )
                )
            );
            );
```

Same for button on my local test, but : button appear in screenshot because screenshot seems to be ~250ms after ;)

I add a global wait for button pof 1 second here to do local test in all condition (see discord)

**Comment by tiborpacalat** [comment]
Tested and verified the fix.

**Comment by olleharstedt** [comment]
This PR was merged without being green. Reverting.

**Comment by olleharstedt** [comment]
OK? Gonna try to revert the other fix too, by Gabriel, and see if that helps.

**Comment by olleharstedt** [comment]
> > This PR was merged without being green. Reverting.
> 
> [b119999](https://github.com/LimeSurvey/LimeSurvey/commit/b119999d02ae481dfa03d4b4d45cd7701fec86ff)

That commit is still red in CI, sooo

**Comment by olleharstedt** [comment]
> > That commit is still red in CI, sooo
> 
> Sh… was green in PR : #3186

OK, then the fault is probably due to Gabriel's PR. Perhaps. :) It can get confusing with PRs overlap like this.

**Comment by gabrieljenik** [comment]
This one https://github.com/LimeSurvey/LimeSurvey/pull/3165 ?

**Pull request merged**
