### PR TITLE
Fixed issue #12116: Change input class from input-lg to input

### PR DESCRIPTION
**Pull request by tammoterhark**

### CODE REVIEW

**Comment by tammoterhark** [comment]
@lacrioque In discussion with schnoulle we saw that changing this to input-sm may even be better. I leave it to you to decide on this. It is only a visual change.

**Comment by Shnoulle** [comment]
I ask : you test and see :) 

I test now , with a big screen

Actual : really too big ....
actual-bigscreen

Normal : better
normal-bigscreen

sm : OK , why not 
sm-bigscreen

**Comment by olleharstedt** [comment]
:+1:

**Comment by tammoterhark** [comment]
Is there something I need to do?

**Pull request merged**
