### PR TITLE
Fixed issue #18653: getSuperAdmin return simple user

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: check with read_p = '1'
Dev: add forcedsuperadmin

### CODE REVIEW

**Review by gabrieljenik — APPROVED** [review]
Code looks OK. Haven't tested it.

**Comment by Shnoulle** [comment]
Seems cool :)

**Comment by Shnoulle** [comment]
> @Shnoulle What do you think about the tests here? https://github.com/LimeSurvey/LimeSurvey/compare/bug/18653_superadminlist-tests

you add it ?

**Comment by gabrieljenik** [comment]
Oh, I was thinking you would merge them to your branch when you feel like.
I can do it if you prefer. Didn't wan't to mess with your branch :)

**Comment by Shnoulle** [comment]
I have test to add but for Script, bnot here :)

Go :)

**Comment by gabrieljenik** [comment]
@Shnoulle Just add the "tested ok" label when comfortable. After that, I believe this can be merged, right?

**Pull request merged**
