### PR TITLE
Fixed issue #18547: Response browsing on MSSQL server could go to 500 error

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #18420: Bad behaviour on grid with MSSQL
Dev: same fix than master(5.X)

### CODE REVIEW

**Comment by Shnoulle** [comment]
https://github.com/yiisoft/yii/issues/4491

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/2673

**Review by gabrieljenik — APPROVED** [review]
Same commit as in master, right?
Haven't tested it.

**Comment by Shnoulle** [comment]
https://github.com/yiisoft/yii/pull/4501

Waiting the new Yii version to create another PR

**Comment by Shnoulle** [comment]
Not related to this commit …

**Comment by Shnoulle** [comment]
https://github.com/yiisoft/yii/pull/4501

**Pull request closed without merging**
