### PR TITLE
Fixed some notices appeared while in debug mode

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by c-schmitz** [comment]
Hello gabriel,

you patch seems to fix issues which should not occur in the first place.
It looks like you have entries in your survey table without related entries in the survey_languagesettings table. If you run the integrity check it  should fix this automatically. Can you verify, please?

**Comment by gabrieljenik** [comment]
I will review that. Strange as this happened with a survey which I had imported

**Comment by Shnoulle** [comment]
I'm not sure we call function fixLanguageSetting after import a survey, maybe only for TSV mode.

And maybe some other fix : http://bugs.limesurvey.org/view.php?id=9559

**Comment by gabrieljenik** [comment]
Actually, this appeared on an survey imported from the documentation sample surveys.

**Comment by gabrieljenik** [comment]
Sorry, how shall I check integrity? Haven't done it before!

**Comment by Shnoulle** [comment]
You have the icon at top, just next of 'backup DB'. What is the survey you imported from doc ?

**Comment by gabrieljenik** [comment]
No errors in the DB are shown.
Have rolled back the fixed, tried to reproduce error, but I can't. :(

**Comment by c-schmitz** [comment]
The check probably fixed it - not all fixes are reported.

**Comment by Shnoulle** [comment]
Maybe we can fix notice even if we have to check integrity , and send an alert if user are super admin ?

**Pull request closed without merging**
