### PR TITLE
New Feature: listifop EM function

### PR DESCRIPTION
**Pull request by Jugen**
New feature # : 8490

Dev:  Added listifop function to EM to address feature request #8490

### CODE REVIEW

**Comment by Shnoulle** [comment]
And javascript ?

**Comment by Shnoulle** [comment]
remind : in 4.0 : you can add any function in Expression.

**Comment by Jugen** [comment]
javascript version committed.

@Shnoulle  Thanks, but thought this would be a useful function that others would like and also a small contribution to this amazing tool.

**Comment by maziminke** [comment]
Please don't forget to update the manual, especially the list of available functions at https://manual.limesurvey.org/Expression_Manager#Implemented_Functions. 
Maybe you can also add a small example to https://manual.limesurvey.org/Expression_Manager_examples ?

**Comment by Shnoulle** [comment]
@maziminke still not in master (or develop)

**Comment by Jugen** [comment]
@maziminke No problem, if this PR is accepted I'll gladly update the manual and provide an example.

**Comment by LouisGac** [comment]
Jugen: here we go :)

**Comment by Jugen** [comment]
Thank you very much for including this in the latest release.
The manual and examples have been updated.

**Pull request merged**
