### PR TITLE
FIX 12479 (partial): Add DB property descriptions in models 

### PR DESCRIPTION
**Pull request by TonisOrmisson**
Let's see how this model looks. 
Some gaps there I was unsure how to describe.

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
https://bugs.limesurvey.org/view.php?id=12479

**Comment by TonisOrmisson** [comment]
Maybe some feedback if in general this style is OK, then I can take on other models as well

**Comment by LouisGac** [comment]
great job ;-) 
thank you very much

**Comment by Shnoulle** [comment]
And WE (all) must fix it, review it when we update a file :)

**Comment by Shnoulle** [comment]
PS : $savetimings Whether survey timings are saved (Y/N) is really better than Y : .... N : blah 👍

**Pull request merged**
