### PR TITLE
New feature: shows logo_statistics.jpg as headerlogo in pdf statistics export if available in admintheme images folder

### PR DESCRIPTION
**Pull request by mbischof**
Fixed issue # : 
New feature # :
Changed feature # :
Dev: 
Dev:

### CODE REVIEW

**Comment by Shnoulle** [comment]
Oh, i think it can be best in Survey theme ? No ?

**Comment by maziminke** [comment]
> Oh, i think it can be best in Survey theme ? No ?

Exactly, weare checking the survey theme for the existence of such a statistics logo file.

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/1169/files#diff-e76864557e20e1665c59f13b104620d2R3883

It's admin theme only for me …

**Comment by maziminke** [comment]
> https://github.com/LimeSurvey/LimeSurvey/pull/1169/files#diff-e76864557e20e1665c59f13b104620d2R3883
> 
> It's admin theme only for me …

You are right. I meant to say that we are checking the **admin** theme for the image file. This is similar to how embedding such an image was done at older Limesurvey versions. 
I agree that using the survey theme may also be useful but since the statistics export is an admin feature we agreed to take the image file from there.

**Comment by c-schmitz** [comment]
Please amend the patch for the /dev branch. We do not accept new feature for the master branch.

**Comment by c-schmitz** [comment]
Also the patch seems to touch alot of unrelated files. It is probably easier to close it and re-open a new PR targeted towards /dev

**Pull request closed without merging**
