### PR TITLE
Dev: review stat management screen

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: remove a potential XSS (echo $oQuestion->question) or broken HTML

Before 
capture du 2017-03-10 15-06-09

After
capture du 2017-03-10 16-06-48

### CODE REVIEW

**Comment by Shnoulle** [comment]
@TonisOrmisson : what do you think of this new screen ?
Maybe btn-small for the Add answer and Remove (answer) button 

Usage of real table is really better than usage of style ;) (in fact : always use tag and class, never use stymle is the best solution)

**Comment by Shnoulle** [comment]
I think we need bigger completed and limit too ....

**Comment by TonisOrmisson** [comment]
see my original post regarding why I did not use <table> in this case:
https://github.com/LimeSurvey/LimeSurvey/pull/643

is your massive actions submitting correct ids with <tables>??
did not work for me and seems also for others:
https://github.com/yiisoft/yii/issues/3241

**Comment by Shnoulle** [comment]
Oh shit ... / i look at it :)

**Comment by Shnoulle** [comment]
Just tested : after this commit , with decativate/actvate and delete. Seems OK for me.

I test with more answers on quota and more quotas too

Tested on firefox

**Comment by TonisOrmisson** [comment]
I had some serious trouble getting the right ids posted. Any `<tr>` items inside the gridview's `<tr>` did not work correctly for me. I suggest varying different selections.

**Comment by Shnoulle** [comment]
I test again : really no issue for me , didn't update anything else than this commit.

Browser specific issue ?

**Comment by Shnoulle** [comment]
I remove an extra div too : maybe this was the original bug

**Comment by TonisOrmisson** [comment]
didn't seem to be browser related to me. 
this issue:
https://github.com/yiisoft/yii/issues/3241
coming from:
https://github.com/yiisoft/yii/blob/ce3fdd21a90cd85a7ac0cb0610977e5d0d2c0209/framework/zii/widgets/assets/gridview/jquery.yiigridview.js#L392
related to how gridview gets the checked ids. I played around for some time with that. This is why the funny format instead of table.

anyway. of course tables would be better if it works. If you say it works, I can pull your version on test this also to confirm

**Comment by Shnoulle** [comment]
Please : test and confirm : i fix 4 XSS security issue (2 in last commit ,and 2 previously).

**Comment by Shnoulle** [comment]
About bthe Yii issue : think it can be fixed with a good settings.tableClass , but really : can not reproduce here ....

**Comment by Shnoulle** [comment]
jqgrid class : .table-striped.table-condensed.table

I don't add .table-striped class. Just let me add a more specific class 'table-quota' and 'table-quota-items' seems goo, no ?

**Comment by TonisOrmisson** [comment]
got your version and at the beginning it seemed to work fine. 
I was about to say its ok, but then again funny stuff started. Its a weird problem. I'll post a video. and try to see how I can reproduce.

**Comment by Shnoulle** [comment]
Maybe other things then because https://github.com/LimeSurvey/LimeSurvey/pull/659/commits/9c6fe8b97d1a655f8720a9f7688cebcddff7e83f surely fix the issue with https://github.com/yiisoft/yii/blob/ce3fdd21a90cd85a7ac0cb0610977e5d0d2c0209/framework/zii/widgets/assets/gridview/jquery.yiigridview.js#L392 :)

**Comment by TonisOrmisson** [comment]
Sent you a short video on email

**Comment by Shnoulle** [comment]
Please, i merge because of the XSS, if i can fix the issue you have i revert.

**Comment by TonisOrmisson** [comment]
I would suggest to fix the XSS on the current version.

**Comment by Shnoulle** [comment]
Too late, already released

**Comment by TonisOrmisson** [comment]
posted the video here also
https://youtu.be/CO637fYgIfc

**Comment by Shnoulle** [comment]
Trying to reproduce currently ... exactly same situation than your : 4 quota without answers 
????

**Comment by TonisOrmisson** [comment]
Its a weird thing. at first looks like its working. Ill try to get it on video from beginning.

**Comment by TonisOrmisson** [comment]
a bit longer video. 
first actions look ok, then errors. 
https://youtu.be/EswfAM1L7ww

**Comment by Shnoulle** [comment]
Not needed a video, just a clean way of reproduce , i put some console.log currently in listActions.js , and i alrady try to activate/deactivate, check item, open a new tab, look at validation etc .....

**Comment by TonisOrmisson** [comment]
I can not say clean way of reproducing. 
As I said originally - removing any nested table elements from inside the grid row makes the thing work flawlessly for me. Adding any table elements made this error re-occur.

**Comment by Shnoulle** [comment]
Yes : but looking at code  : i don't see how this can happen ...

**Comment by Shnoulle** [comment]
If i find any thing i fix it monday morning (and test with different browser too).
Can you take time on paginations ?

**Comment by TonisOrmisson** [comment]
I can look at paginations yes. 
are you able to reproduce at least?

**Comment by Shnoulle** [comment]
Yep : in fact check 1/2/3 -> console.log here https://github.com/LimeSurvey/LimeSurvey/blob/master/application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js#L26 receive the 3 first id : seems OK. But after come back : 4 items are updated.

Thanks for reproduce, no, i try to understand what happen after ;)

**Comment by Shnoulle** [comment]
OK,

Can not reproduce now, and understand what happen : the bug surely can happen elsewhere : https://bugs.limesurvey.org/view.php?id=12193

**Comment by Shnoulle** [comment]
Fixed in https://github.com/LimeSurvey/LimeSurvey/commit/4ae6395e9701d05649f609c826cedf62d1b36958

**Pull request merged**
