### PR TITLE
Fixed issue #18071: Import question

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #18071: Importing Question through Remote Control may fail if the imported question already exists
Dev: check title unicity before import
Dev: set autorename to true if new title is set
Fixed issue #18070: Importing Question through Remote Control doesn't set text for all languages
Dev: review permission (sureycontent/import or update)
Dev: most biggest issue : title broken too :)
Dev: set for all language and return error if not validate

### CODE REVIEW

**Comment by Shnoulle** [comment]
@gabrieljenik : you can review the test for 3.X ?

**Comment by gabrieljenik** [comment]
Can you apply the fix on master as well on the "18071-importing-question-through-remote-control-may-fail-test-II" branch?

**Comment by gabrieljenik** [comment]
> @gabrieljenik : you can review the test for 3.X ?

Seems to be failing gracefully now on PHP 7.4.
https://github.com/LimeSurvey/LimeSurvey/actions/runs/4358493797/jobs/7619141286#step:12:22

I will keep on reviewing the PHP5.6 version of the test

**Comment by Shnoulle** [comment]
> Seems to be failing gracefully now on PHP 7.4.

Yes , and it's possible then this one came from a difference between 3.X and master …

**Comment by gabrieljenik** [comment]
> Yes , and it's possible then this one came from a difference between 3.X and master …

Youtake care of it right?

**Comment by Shnoulle** [comment]
> Youtake care of it right?

Not in the test.

**Comment by gabrieljenik** [comment]
> one came from

You think the test is failing its purpose (as opposite to not passing)?

**Comment by gabrieljenik** [comment]
> > it's possible then this one came from a difference between 3.X and master …
> 
> You think the test is failing its purpose (as opposite to not passing)?

Let me review the test

**Comment by gabrieljenik** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/2972/files#diff-22d09ac4b2de7e29721c3fc14eb239f215498a280b8c37f4b718074646f01f5dR1419

The check seems to be done only if newTitle is requested.

**Comment by Shnoulle** [comment]
> The check seems to be done only if newTitle is requested.

I didn't update the previous system `autorename = false` is the default. Then if question code already exist and you don't set a new title : it stay false.

But you right : i can remove the $importOptions part : test still broken i think. Lets' go.

**Comment by Shnoulle** [comment]
I review the test : it **must** return in array to don't break API version.

**Comment by gabrieljenik** [comment]
> test still broken i think

I am not sure about this.

We are testing the following: Import a Question with a code which already exists.
Test is not passed. Getting this as output
```
 'status' => 'Error: <div class="errorSummary">The question could not be imported for the following reasons:
<ul>
<li>Question codes must be unique.</li>
</ul></div>'
```

That message comes from question model.
So maybe that error message should not be html? (not sure it is worth working on that)

As you say, the test needs to be adjusted as to use the `sNewQuestionTitle` parameter. Right now doesn't reflect the situation reported.

**Comment by Shnoulle** [comment]
OK : got it … (and remind why i puit this code)

- Default is `autorename = false` : must break import
- If new title is set  : must import with rename set  `autorename = true` 

> As you say, the test needs to be adjusted as to use the sNewQuestionTitle parameter. Right now doesn't reflect the situation reported.

Yes : i add a 3rd test here

**Comment by Shnoulle** [comment]
Arg phpunit version https://docs.phpunit.de/en/10.0/assertions.html#assertisarray

**Comment by gabrieljenik** [comment]
> Arg phpunit version https://docs.phpunit.de/en/10.0/assertions.html#assertisarray

Yep, old version of PHPUnit:
Just use the assertIsType it was before, but with "array" instead of "int"

**Comment by Shnoulle** [comment]
> > Arg phpunit version https://docs.phpunit.de/en/10.0/assertions.html#assertisarray
> 
> Yep, old version of PHPUnit: Just use the assertIsType it was before, but with "array" instead of "int"

Yes already done

**Comment by Shnoulle** [comment]
autotest don't do 18070 : you do ot or i do it ?
It's different for 3.X and 5.X

**Comment by gabrieljenik** [comment]
> autotest don't do 18070 : you do ot or i do it ?
> It's different for 3.X and 5.X

I do it

**Comment by Shnoulle** [comment]
For master : i can start from https://github.com/LimeSurvey/LimeSurvey/tree/bug/18071-importing-question-through-remote-control-may-fail-test-II  ?

Ypu create the merge request and assign it to me ? (or redo the fix).

**Comment by gabrieljenik** [comment]
> For master : i can start from https://github.com/LimeSurvey/LimeSurvey/tree/bug/18071-importing-question-through-remote-control-may-fail-test-II ?

Yes

> Ypu create the merge request and assign it to me ? (or redo the fix).

I can. But also you can create the PR, can you?

**Comment by Shnoulle** [comment]
> I can. But also you can create the PR, can you?

Oh right … :+1: 

Done as draft

**Review by gabrieljenik — APPROVED** [review]

**Comment by gabrieljenik** [comment]
Set it to "tested ok" as it has the automatic tests

**Comment by olleharstedt** [comment]
Guys guys guys, please make sure the PR title is either "New feature #123: ...", "Fixed issue #123: ..." or "Dev: ..."

**Comment by Shnoulle** [comment]
> Guys guys guys, please make sure the PR title is either "New feature #123: ...", "Fixed issue #123: ..." or "Dev: ..."

There are 2 fixed issue here.

Maybe Dev: fix issue #1 and #2

Otherare in comment ?

**Pull request merged**
