### PR TITLE
[WIP] New feature #14156:easily disable no more table for specific questions

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: need to review theme.css too …  seem OK when testing
Dev: but not tested with radio/checkbox, silly boy …

### CODE REVIEW

**Comment by Shnoulle** [comment]
Except if someone else take it => move it to develop (too many template update needed)

**Comment by Shnoulle** [comment]
Advice, reason ?

**Comment by Shnoulle** [comment]
Maybe best solution : add no-more-table if table-fixed or table-responsive is not set : see https://gitlab.com/SondagesPro/SurveyThemes/skelvanilla/commit/78bee8d379f931f3c2995e227a8e046ff016360e

**Comment by maziminke** [comment]
So this feature did not make it into the core?

Currently, what is the best approach to prevent certain questions from being broken down to smaller questions on mobile devices?

**Comment by Shnoulle** [comment]
Theme related issue : not a **core** issue !

https://extensions.sondages.pro/themes-and-templates/skelvanilla-a11y-and-usuability/documentation.html#Table-fixed-or-no-more-table

**Comment by maziminke** [comment]
@Shnoulle So at your theme one can simply add _table-fixed_ and _table-responsive_ CSS classes at question level in order to control the behavior?

**Comment by Shnoulle** [comment]
>  So at your theme one can simply add table-fixed and table-responsive CSS classes at question level in order to control the behavior?


RTFM

**Comment by maziminke** [comment]
RTFM-> That's what I actually did and where I took the class names from. It just wasn't that clear to me how exactly this works. Is it just adding the CSS classes?

**Comment by Shnoulle** [comment]
> you can add table-fixed and table-responsive class to disable this update

**Pull request closed without merging**
