### PR TITLE
Cr 1045 formextension rendering

### PR DESCRIPTION
**Pull request by kevin-foster-uk**
Refactor form extension to avoid duplication in rendering code.

### CODE REVIEW

**Comment by olleharstedt** [comment]
Looks good, but are changes needed to the LimeSurvey professional plugin now? Because you changed namespace names.

**Comment by kevin-foster-uk** [comment]
@olleharstedt This has been hanging around for a while. Maybe we should discuss?

**Comment by kevin-foster-uk** [comment]
> Looks good, but are changes needed to the LimeSurvey professional plugin now? Because you changed namespace names.

I tend to avoid plurals in namespaces.

The plural indicates a collection but you have classes which are not of type "Input":  Inputs\DefaultBaseRenderer and Inputs\GlobalSettingsRenderer.

**Comment by olleharstedt** [comment]
>      I tend to avoid plurals in namespaces.

Isn't there a PSR standard for that tho?

**Comment by kevin-foster-uk** [comment]
@olleharstedt Not sure why this was never merged? Should be abandon this PR?

**Comment by olleharstedt** [comment]
> @olleharstedt Not sure why this was never merged? Should be abandon this PR?

Hm not sure. It needs to be tested with the cloud plugin before merge, else it looks good, I think. :)

**Pull request closed without merging**
