### PR TITLE
New feature #12690: Allow super-admin set by other user's than 1

### PR DESCRIPTION
**Pull request by Shnoulle**
- this add [supermadmin][create] by DB used for managing (set supermadmin/read and supermadmin/create)
- add a App()->getConfig('superadmin_force');
- Strangely : any superadmin can update email of user->uid == 1 before, leave like this

### CODE REVIEW

**Comment by Shnoulle** [comment]
@LouisGac and @c-schmitz : i'm just unsure of the 'config' name ? https://github.com/LimeSurvey/LimeSurvey/pull/810/files#diff-ff00978f239a45254dac07e3320c7a8bR600 `'forcedSuperAdmin'` maybe ? Then `public static function isForcedSuperAdmin()` seems clearly related ? An advice ?

I merge it after.

**Comment by LouisGac** [comment]
seems good to me.

**Comment by Shnoulle** [comment]
Keep old name or rename it ?

**Comment by tammoterhark** [comment]
you choose, cannot decide.

**Pull request merged**
