### PR TITLE
Fixed issue #12349: RTL languages not dispayed correctly in the admin editor

### PR DESCRIPTION
**Pull request by gabrieljenik**
Corrected it for the editor of both the question and help, as well as for subquestions and answers.
We can apply the correction on other places as well.

Added a function to twig extensions as to check if the language is RTL. That function feeds the editor settings

### CODE REVIEW

**Comment by olleharstedt** [comment]
500 in Travis?

**Comment by olleharstedt** [comment]
> Error
> Call to undefined function Twig\xdebug_break() 

Namespace error?

**Comment by gabrieljenik** [comment]
> > Error
> > Call to undefined function Twig\xdebug_break()
> 
> Namespace error?

Will review

**Comment by gabrieljenik** [comment]
Seems fixed now :)

**Comment by olleharstedt** [comment]
Thanks!

**Pull request merged**
