### PR TITLE
Fixed issue #18936: User count in group is not OK after deleting a user

### PR DESCRIPTION
**Pull request by gabrieljenik**
- Moved code to a new function on a service class
- Added the "remove from groups" operation

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]
No problem in code, bu we really need all this code ?

**Comment by gabrieljenik** [comment]
> bu we really need all this code ?

Well, we moved some stuff from controller to a service class.
We needed a way to communicate in between both.
Did something reusable for it.

**Comment by Shnoulle** [comment]
> Did something reusable for it.

A lot of things reusable never reused in LS … :(

Maybe we need page for reusable part in manual ?

**Comment by gabrieljenik** [comment]
> A lot of things reusable never reused in LS … :(

Keep the faith (and use it :) )

**Pull request merged**
