### PR TITLE
New feature #19299: Unmask token field

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: add input-group-text to hide/show tokn
Dev: add inline javascript : can be move to theme.js
Dev: but maybe more understandable for updationg by other theme user (beginner and not developer)

### CODE REVIEW

**Comment by Shnoulle** [comment]
It's currently a choice to leave JS in this file. Make for user who are not developer, easy to understand and to update only this part.

**Review by tiborpacalat — APPROVED** [review]
Looks good!

**Comment by olleharstedt** [comment]
New feature in master branch? Why not dev?

**Comment by Shnoulle** [comment]
> New feature in master branch? Why not dev?

Really ? 

I thin,k dev is more for big feature, not for minor feature, no ?

**Comment by olleharstedt** [comment]
No, all features go into dev, master is for bug fixes only. But this was small, so no problem.

**Comment by Shnoulle** [comment]
> No, all features go into dev, master is for bug fixes only. But this was small, so no problem.

OK, remind for next time (or move feature request to ergnomy issue ;) )

**Comment by olleharstedt** [comment]
Hehe

**Pull request merged**
