### PR TITLE
Add afterQuestionTypesBuilt event

### PR DESCRIPTION
**Pull request by yuriybabenko**
Event allows plugins to alter the possible question types.

Use-case involves removing question types deemed not necessary.

### CODE REVIEW

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/tree/questionobject_prototype1

**Comment by yuriybabenko** [comment]
@Shnoulle - Can you explain what you mean by that link?

**Comment by olleharstedt** [comment]
Why would you want to remove question types? Not sure I understand your use-case.

We are working with question types etc, there's a lot of information about it here: https://manual.limesurvey.org/Question_object_types

**Comment by yuriybabenko** [comment]
@olleharstedt - Our use-case is rather proprietary. Certain types need to be removed as they're not needed and will cause problems with the downstream processing (outside of LS) of survey data.

This same event can be used to add/rename, or otherwise alter existing question types, which would be a more common use-case.

**Comment by olleharstedt** [comment]
Hm, OK. Why don't you fork the repo and remove question types instead?

**Comment by Shnoulle** [comment]
@yuriybabenko : in fact : Olle already start to rework completely Question Object system. Then when we are ready : you can deactivate some Question Object directly in the GUI (maybe) and add yourself some.

Then : i don't think we need adding an event on this purpose actually.

**Pull request closed without merging**
