### PR TITLE
New feature: added afterSurveyActivate, afterSurveyDeactivate Plugin Events

### PR DESCRIPTION
**Pull request by mbischof**
Fixed issue # : 
New feature # :
Changed feature # :
Dev: 
Dev:

### CODE REVIEW

**Comment by Shnoulle** [comment]
related forum post : https://www.limesurvey.org/fr/forum/development/116889-new-pluginevents-aftersurveyactivate,-aftersurveydeactivate 

And right : survey activation is really a important event and hard to track currently.

**Comment by maziminke** [comment]
@mbischof Please update https://manual.limesurvey.org/Plugin_events once the pull request was merged. Please add missing events there and add short note about how they work and when they get fired at the new sub-pages of the wiki.

**Comment by Shnoulle** [comment]
For 3.X and before : something near beforeSurveyActivate : it happen after survey db creation, just before survey is finally set to active.

```
$savedSurvey = $this->getEvent()->get("model");
if($savedSurvey->sid && $savedSurvey->active == "Y") {
    $oldSurvey => Survey::model()->findByPk($savedSurvey->sid);
    if($oldSurvey && $oldSurvey->active != "Y") {
        // We are before survey is activated, after response DB created
    }
}
```

For this one and this pull request  : i don't know what happen when import a LSA file ?

**Comment by Shnoulle** [comment]
I know i use it somewhere … https://gitlab.com/SondagesPro/coreAndTools/reloadAnyResponse/blob/ab8ba58e15bb6168c389c5947ada752eeba9e15b/reloadAnyResponse.php#L246

Here : afterSurveyDeactivate : more easy current model and updated model are same. With before : you really have the difference.

**Comment by olleharstedt** [comment]
Please update the manual with relevant information first: https://manual.limesurvey.org/Plugin_events

**Comment by mbischof** [comment]
added the following pages to wiki:

- [AfterSurveyActivate](https://manual.limesurvey.org/AfterSurveyActivate)
- [AfterSurvexDeactivate](https://manual.limesurvey.org/AfterSurveyDeactivate)

**Comment by olleharstedt** [comment]
Great! Can you also please add a description of what the return value `simulate` means?

**Comment by Shnoulle** [comment]
I think we must have a beforeSurveyActivate , the we can set `simulate` via plugin.

**Comment by olleharstedt** [comment]
What I can see in the source code, we do already.

**Comment by olleharstedt** [comment]
I added it two years ago but forgot to document it. Shame on me!

**Comment by olleharstedt** [comment]
Nope, it's documented, the link was just missing, for some reason. https://manual.limesurvey.org/BeforeSurveyActivate

**Comment by Shnoulle** [comment]
Thanks and sorry for this :)

**Pull request merged**
