### PR TITLE
Fixed issue #15696: Multiple email addresses in token are not working

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue : Allow to update bad Opt out or set Opt out manually

### CODE REVIEW

**Comment by Shnoulle** [comment]
I don't use email : i report another issue …

**Comment by Shnoulle** [comment]
Why i didn't use email input : [15712: When doing error in token create : unable to submit, need to reload page](https://bugs.limesurvey.org/view.php?id=15712)

else : email multiple allow , and ; but not |. Model control allow  , and ; and | . Then it's an API broker.

**Comment by olleharstedt** [comment]
Thanks, will test and merge.

**Comment by olleharstedt** [comment]
Test failed.

**Comment by olleharstedt** [comment]
Merged but need more info.

**Pull request merged**
