### PR TITLE
Update Token.php

### PR DESCRIPTION
**Pull request by BertHankes**
In a tokentable the additional attribute fields are sometimes to small. 
I propose a TEXT type field instead of VARCHAR(255) just like extrafields

### CODE REVIEW

**Comment by SamMousa** [comment]
Varchar is not limited to 255 char, it can go up to 65535... there is no need for text fields.

**Comment by BertHankes** [comment]
VARCHAR(21844) for UTF8... But extrafields are TEXT.. so why not make it the same?

**Comment by SamMousa** [comment]
AFAIK the extra fields column contains a name mapping for the token table. It is only retrieved as a whole and there is always a limited number of surveys in a system. 
A token table however can have many custom attribute and making them all `TEXT` is very slow and not needed for the majority of cases.

**Comment by BertHankes** [comment]
Then maybe an option in management (e.q. higher impact programmewise) to vary an attribute in length. 
For our surveys it has become mandatory to have 'attribute_4' type TEXT (or larger then 255). So with this in mind I made this PR

**Comment by SamMousa** [comment]
Thanks for your time, @BertHankes.
@c-schmitz I do not think we should merge this in master.

**Comment by BertHankes** [comment]
We can live with that :-). 
We have procedures in place to do just that.. change attribute_4 to type TEXT

**Comment by SamMousa** [comment]
@BertHankes what we (probably) would accept is an event that fires before the token table gets created / updated. Then you could create a plugin that changes the column type before the command is sent to the database.

**Comment by BertHankes** [comment]
Thanks.. but for now it is not a big issue. Our procedure is working like a charm. Making an event is an option indeed. I even made an event myself a while ago and wrote a plugin for it (a nasty one: afterEdit :-)
So maybe I will PR some later. For now there is a lot to do for making 2.50+ stable (important)

**Comment by olleharstedt** [comment]
There might be an issue on SQL Server: http://stackoverflow.com/questions/4350060/where-clause-on-sql-server-text-data-type

Still, I will merge, and we will see.

**Pull request merged**
