### PR TITLE
Fixed Issue #18120: Server Error 500 when editing global settings: alias "application.controllers.admin.GlobalSettings" invalid

### PR DESCRIPTION
**Pull request by hydroid7**
Fixed issue #18120.
Correct naming of the components fixes the issue.

### CODE REVIEW

**Comment by gabrieljenik** [comment]
I wasn't able to reproduce it. But I have docker on top of windows, so that could be tricky with the filenames.
Will let @Shnoulle review it. Seems OK

**Comment by Shnoulle** [comment]
> I wasn't able to reproduce it. But I have docker on top of windows, so that could be tricky with the filenames. Will let @Shnoulle review it. Seems OK

Can not reproduce too, but nginx, let me try on debian/apache

**Comment by Shnoulle** [comment]
Capture d’écran du 2022-05-18 09-56-05

With fix …

**Comment by Shnoulle** [comment]
Fixed both on https://github.com/LimeSurvey/LimeSurvey/pull/2430

Great thanks to you

**Pull request closed without merging**
