### PR TITLE
Fixed issue #16777: Add list_survey_groups to RemoteControl API

### PR DESCRIPTION
**Pull request by gabrieljenik**
Ported PR 1109 and adapted it. Added Basic Unit Test

### CODE REVIEW

**Comment by Shnoulle** [comment]
I really think we need a plugin event to add function in API ...

remotecontrol_handle.php file are already too big ....

**Comment by gabrieljenik** [comment]
I the idea.
I would do that for custom methods.

For current methods I would do a class structure.
Each api endpoint with a class. (And more events like beforeRCMethod).

**Comment by Shnoulle** [comment]
> I the idea.

Waht do you mean ?

**Comment by gabrieljenik** [comment]
Like the idea.
 Missed word through the cell phone

**Comment by Shnoulle** [comment]
Yep,

See related https://github.com/LimeSurvey/LimeSurvey/pull/1663 

Using https://gitlab.com/SondagesPro/RemoteControl/extendRemoteControl i see we can use any connection fr url, `$sSessionKey` is the same :)

**Comment by edgarrmondragon** [comment]
This is great @gabrieljenik. I like the idea of methods similar to `list_surveys` and `get_survey_properties` but for survey groups. It would also be great to have a direct way to access the global survey settings (which I think is just a special survey group) to fully determine inherited values. wdyt?

I'm not very proficient in PHP but I can probably contribute some of those.

**Comment by gabrieljenik** [comment]
Hi @edgarrmondragon Sure, just bring them in!

**Comment by olleharstedt** [comment]
> I really think we need a plugin event to add function in API ...

No, it should be split-up using the command object pattern. There's a dev issue in Mantis, I think.

**Comment by olleharstedt** [comment]
Waaaait - new feature --> LS4.5 --> dev branch???

**Comment by Shnoulle** [comment]
> No, it should be split-up using the command object pattern. There's a dev issue in Mantis, I think.

Yes,
**and** offer a way to add own function ;)

**Comment by olleharstedt** [comment]
> > No, it should be split-up using the command object pattern. There's a dev issue in Mantis, I think.
> 
> Yes,
> **and** offer a way to add own function ;)

Of course, but not new function, new class.

**Comment by Shnoulle** [comment]
> Of course, but not new function, new class.

New RemoteControl function ? No ?  Done by adding class, but final objective is new function ;)

**Comment by olleharstedt** [comment]
https://bugs.limesurvey.org/view.php?id=15817

**Comment by gabrieljenik** [comment]
> Waaaait - new feature --> LS4.5 --> dev branch???

Oops. Sorry. Should I rebase?

**Comment by olleharstedt** [comment]
> > Waaaait - new feature --> LS4.5 --> dev branch???
> 
> Oops. Sorry. Should I rebase?

Yes, please. :+1:

**Comment by olleharstedt** [comment]
Close this branch after and ping me in the Mantis ticket.

**Comment by gabrieljenik** [comment]
Already rebased it.

**Comment by olleharstedt** [comment]
Hooray! New feature. :D

**Pull request merged**
