### PR TITLE
Logging management, usage of Yii

### PR DESCRIPTION
**Pull request by Shnoulle**
- log warning and error to web without broke totally page with 0<debug<2
- allow to use tracevar without debug
- unsure for CFileLogRoute by default : can be interesting, but runtime path have web direct access issue

Maybe add a way to show php notice at the same way with  1<debug<2 with [ErrorHandler](http://www.yiiframework.com/doc/api/1.1/CErrorHandler) ?

### CODE REVIEW

**Comment by Shnoulle** [comment]
Because you seem interested, maybe another way ? We can use PHP functin, but then replace the handler.

**Comment by olleharstedt** [comment]
I'm not sure... Shouldn't this be up to the dev to configure?

**Comment by Shnoulle** [comment]
It's already the case today, but we don't offer an easiest way . We already use log/trace for tracevar : we make a choice for the user :). 

We can examplain on forum how to update config.php to set debug=1, maybe add a system to log it when user make manually the choice (something in session for this user etc ....) . But exaplain how to put this in config.php it's more hard (on forum).

Here : the user can update it in config.php, but with a clean example . Maybe enable limesurveyErrorAndWarning (by default) only if debug >0 too ? The config.php file replace internal.php config part.

**Comment by LouisGac** [comment]
I think we should merge it.

**Comment by Shnoulle** [comment]
Maybe in develop only but still 

> but runtime path have web direct access issue

I'm really not sure here , we can disable direct access with .htacess , but only for apache then ?

**Comment by Shnoulle** [comment]
http://www.yiiframework.com/extension/syslogroute/ and set it by default seems the best solution. no ?

**Comment by c-schmitz** [comment]
@Shnoulle Can you update it so we can merge it to dev?

**Comment by Shnoulle** [comment]
Oups, don't see the update. But don't log it `CFileLogRoute` else a lot of user can show error log publicly …

**Comment by maziminke** [comment]
Denis, does this support logging any warnings or errors to a log file at e.g. /tmp?

**Comment by Shnoulle** [comment]
See https://manual.limesurvey.org/Optional_settings#Logging_settings 

And if you wait 5 minutes i update it to don't log 404 error (there are a lot …)

**Comment by Shnoulle** [comment]
The commit is here : https://github.com/LimeSurvey/LimeSurvey/commit/e08fbc018f89bf55173fecd5b86bc56686d42c39

But, manual explain it : https://manual.limesurvey.org/Optional_settings#Logging_settings

**Comment by maziminke** [comment]
Thanks, Denis. The documentation at the manual is a little vague: Does the sample code log to a file and if so, where is it found?

**Comment by Shnoulle** [comment]
https://manual.limesurvey.org/Optional_settings#Introduction + https://manual.limesurvey.org/Optional_settings#Yii_settings … i really think it can be more clear …

**Pull request closed without merging**
