### PR TITLE
Fixed issue [security] #19873: RC : Any user can create or update any participant in CPDB

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: check permission and continue if no permission

### CODE REVIEW

**Review by gabrieljenik — APPROVED** [review]
Code structure looks good. I am not sure if there is a way to inform about the operations not permitted. If not, people will not know about the error.

**Comment by Shnoulle** [comment]
> Code structure looks good. I am not sure if there is a way to inform about the operations not permitted. If not, people will not know about the error.

There are a result : https://github.com/LimeSurvey/LimeSurvey/blob/47083aad164ecaa5fb85bd5cb0d92e890b034d0b/application/helpers/remotecontrol/remotecontrol_handle.php#L3909

We don't need to send value with issue : you send 10 lines : you get one update and one created : you know there are 8 with issues

PS : i start to send 403 … and understand it's a bad solution ;)

**Comment by gabrieljenik** [comment]
> We don't need to send value with issue : you send 10 lines : you get one update and one created : you know there are 8 with issues

Maybe just a messages item in the reposnse array: "You don't have permission to ..."

**Comment by Shnoulle** [comment]
> > We don't need to send value with issue : you send 10 lines : you get one update and one created : you know there are 8 with issues
> 
> Maybe just a messages item in the reposnse array: "You don't have permission to ..."

I really don't think we need to add it

**Comment by gabrieljenik** [comment]
Maybe we should add some automatic testing for this?

**Comment by Shnoulle** [comment]
> Maybe we should add some automatic testing for this?

On a second time : currently i think we need to fix security :)

I create a mantis for permission check on RC tomorrow.

**Comment by Shnoulle** [comment]
> Maybe we should add some automatic testing for this?

We already have some but the current Remote Control Export Statistics Array Questions (ls\tests\RemoteControlExportStatisticsArrayQuestions) gide it.

There are an error in permission checking here.

**Pull request merged**
