### PR TITLE
New feature: Export responses by multiple tokens

### PR DESCRIPTION
**Pull request by dcore94**
Make it possible to optionally export responses with several tokens as filter instead of only one.

Fixed issue #<Mantis issue number>:
New feature #<Mantis issue number>:
Dev:

### CODE REVIEW

**Comment by dcore94** [comment]
This helps us reduce by one order of magnitude the number of REST calls in some scenarios.

**Comment by olleharstedt** [comment]
Looks good. I assume it doesn't break backwards compatibility, since string is still accepted as argument for token?

**Comment by olleharstedt** [comment]
Would it be possible to write a unit test for this new feature? There are many tests already written for the RPC API, which you can look at for inspiration.

**Comment by dcore94** [comment]
> Looks good. I assume it doesn't break backwards compatibility, since string is still accepted as argument for token?

We are temporarily using a version of LimeSurvey with this change built in and we do not experience any break of backward compatibility.

**Comment by olleharstedt** [comment]
Thanks for adding the unit test and for you contribution to LimeSurvey! :)

**Comment by olleharstedt** [comment]
This feature will be released in LimeSurvey 6.3.0, by the way.

**Pull request merged**
