### PR TITLE
Fixed issue #17422: Survey Deletion view/read permission seems to be granted

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: Check if forced by minimal read : don't display checkbox in view
Dev: Alt : show checkbox as checked and disable ?

### CODE REVIEW

**Comment by Shnoulle** [comment]
Since it's a view issue : i prefer to keep tha checked value but send forced information.

Maybe show it as disable/checked ? 

English sentence to review

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/1959/files#diff-00af2c01500e0952ff7930f31e4214ac81d90d4af5d897ec34a579a0b3e42914R26

Or : something like this ` && ($aCurrentPermissions['minimal'] == $sPermission && $sKey == 'read')` ?

**Comment by olleharstedt** [comment]
@glimz test

**Comment by olleharstedt** [comment]
@glimz You tested this? What failed?

**Comment by Shnoulle** [comment]
I like to know what is failed ?

**Pull request merged**
