### PR TITLE
New feature: Function list_survey_groups for RemoteControl API

### PR DESCRIPTION
**Pull request by cord**
allow to retrieve survey groups

Fixed issue # : 0
New feature # : 1
Changed feature # :0 
Dev: 
Dev:

### CODE REVIEW

**Comment by LouisGac** [comment]
seems great. 
thank you for that PR. 
survey groups will become more and more importants in the comming months, and will provide fine way of tuning most default settings.

**Comment by olleharstedt** [comment]
Looks good, but:

1. Needs a Mantis issue for feature request
2. Needs acceptance tests

**Comment by cdorin93** [comment]
@olleharstedt , please check the updated branch :)

**Comment by c-schmitz** [comment]
Merged in #1660

**Pull request closed without merging**
