### PR TITLE
New feature : else part in Expression Manager function optionnable

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: just set default value to ""
Dev: use "" because if function is more used for show something (string) to user

### CODE REVIEW

**Comment by maziminke** [comment]
Denis, can you explain this new feature in a sentence? Does it simply mean that I do not have to add details for the ELSE part anymore?

**Comment by Shnoulle** [comment]
:) You're right …

A lot of time, i use EM if like that

`{if(QCODE=="Y","A sentence for you","")} {if(QCODE_SQ1=="Y","Another sentence for you","")}`

It's just a quick way to have `{if(QCODE=="Y","A sentence for you")} {if(QCODE_SQ1=="Y","Another sentence for you")}`

Some user on forum make error. And seems clean to have

If “condition is true” do “this”

No need the else part.

**Comment by maziminke** [comment]
Thanks for the clarification, indeed a nice and very useful adjustment!

**Comment by Shnoulle** [comment]
@maziminke : the n why did you close it ???? :(

**Comment by c-schmitz** [comment]
@Shnoulle Please make sure to update the manual. Thank you.

**Comment by maziminke** [comment]
@Shnoulle I closed it accidentally, sorry.

I also want to remind you that the manual has to be updated. If a new feature is not documented, no one will use it and that would be a pity.

**Pull request merged**
