### PR TITLE
DEV: code inspection application/helpers - clean 1

### PR DESCRIPTION
**Pull request by TonisOrmisson**
various fixes (see commits descriptions)

I'll try to keep it in smaller pieces to keep track of things

### CODE REVIEW

**Comment by LouisGac** [comment]
thank you very much for all this work, greatly appreciated. 
I just hope it's not going to make the merge with master a real hell 😅

**Comment by maziminke** [comment]
Thanks for all your valuable work!

Am 09.06.2017 um 10:05 schrieb LouisGac:

**Comment by TonisOrmisson** [comment]
you are very welcome :)

**Comment by LouisGac** [comment]
here the conflict comming 😅

**Comment by Shnoulle** [comment]
Must merge master all day maybe ;)

**Comment by TonisOrmisson** [comment]
posting such things to develop is probably also not that great idea. or would you prefer that?

**Comment by LouisGac** [comment]
I prefer PR to develop. Master should remain as stable as possible now.

**Pull request merged**
