### PR TITLE
Best practise to talk about LibreOffice rather than OpenOffice

### PR DESCRIPTION
**Pull request by jinformatique**
Changed # : replaced OpenOffice occurence by LibreOffice

### CODE REVIEW

**Comment by Shnoulle** [comment]
I think i prefer something like 

> major spreadsheet tool

🙂

**Comment by jinformatique** [comment]
Sure, but people who only heard of OpenOffice will believe OpenOffice is the major spreadsheet and  won't know about LibreOffice until someone tell them. This could be a written way to let them know about LibreOffice.

**Comment by c-schmitz** [comment]
I would suggest 'default for most Spreadsheet tools', that way we don't give a preference to anyone.

**Comment by Shnoulle** [comment]
@jinformatique : please, review your pull request using 
> default for most Spreadsheet tools

:)

**Comment by c-schmitz** [comment]
Since OP did not took care of it I fixed it myself.

**Pull request closed without merging**
