### PR TITLE
Fixed issue #15940: Export as printable : PHP Notice with debug

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: Really get current Survey template folder
Dev: not reset to default

### CODE REVIEW

**Comment by olleharstedt** [comment]
Can we get some introduction on how to reproduce the issue without the fix?

**Comment by Shnoulle** [comment]
https://bugs.limesurvey.org/view.php?id=15940

**Comment by cdorin93** [comment]
Hello @Shnoulle , is it possible to update the branch to have the conflicts resolved? It will be merged after :) - thx for your work!

**Comment by Shnoulle** [comment]
I don't reproduce the notice , but extended template seems empty 

Lezt me check and report another issue

**Comment by Shnoulle** [comment]
@cdorin93 : https://bugs.limesurvey.org/view.php?id=16742 think the feature is broken

**Comment by Shnoulle** [comment]
@gabrieljenik already done a fix (merged) https://github.com/LimeSurvey/LimeSurvey/pull/1449/files

**Pull request closed without merging**
