### PR TITLE
Fixed issue #18373: Saving statistics exports to excel fails

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by Shnoulle** [comment]
Why ? It's merged in master : then when we merge master in develop : it's OK ? No ?
https://github.com/LimeSurvey/LimeSurvey/pull/2634

**Comment by gabrieljenik** [comment]
Because the file being updated on the previous PR is not present in develop anymore.
https://github.com/LimeSurvey/LimeSurvey/commit/cbffb1482a9c193f4bfc2b239954a54268628503#commitcomment-86005958

**Review by Shnoulle — APPROVED** [review]

**Comment by Shnoulle** [comment]
Right :)

**Comment by gabrieljenik** [comment]
@olleharstedt Maybe this can be merged in develop?

**Pull request merged**
