### PR TITLE
New feature #15513: Missing function floatval() in EM

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: check 150.03_page-section php vs js : OK

### CODE REVIEW

**Comment by olleharstedt** [comment]
Acceptance test needed. Could be done as unit-test, not functional, right? See my tiny test added to EM warning.

**Comment by Shnoulle** [comment]
I already started survey test but … [15598: intval : broken interpretation of string start by integer in JS](https://bugs.limesurvey.org/view.php?id=15598)

**Comment by Shnoulle** [comment]
My opinon : fix intval in 4.0 : add a test for intval + floatval in 4.X

**Comment by olleharstedt** [comment]
My question is why LEMintval is *worse* than the JS standard `parseInt`?

**Comment by Shnoulle** [comment]
Don't know …
Seems it was implemented like this : https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/237c43a5ca362d1d1591f01ae2ea202e7454b789

**Comment by olleharstedt** [comment]
```
function LEMis_string(a)
{
    return isNaN(a);
}
```

???

**Comment by olleharstedt** [comment]
Looks like Carsten moved the file without using `git mv`.

**Comment by Shnoulle** [comment]
Apr 2012 : 8 years ago …

Previous : https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/41fe91a45ce37ce5a0a304fa012b8afe07acf401

**Comment by olleharstedt** [comment]
What about replacing LEMintval with parseInt in JS?

**Comment by olleharstedt** [comment]
Missing acceptance test, but maybe I can write that later.

**Comment by Shnoulle** [comment]
@olleharstedt I'm out of office this week. I can write acceptance test for floatval only (i already start but intval broken).

**Comment by olleharstedt** [comment]
Maybe we can use nodejs to run the expression both in PHP and JS? I did this for an earlier test.

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/blob/master/tests/surveys/MinMaxCompareTest.php already check JS vs PHP

It does

1. JS vs PHP compare
2. Fixed string compare (current way)

**Comment by olleharstedt** [comment]
Yes, but it could be done without using the browser, I mean, in a unit test.

But good. :)

**Comment by Shnoulle** [comment]
Maybe : but using the browser : you are sure it use expressionmanager js : no ?

**Comment by olleharstedt** [comment]
I'm not sure about anything. :|

**Comment by Shnoulle** [comment]
Right … «You have more chance it use the same js than a survey participant» …

**Pull request merged**
