### PR TITLE
Fixed issue #17188: {GROUPNAME} and other variables not rendered

### PR DESCRIPTION
**Pull request by gabrieljenik**
Adding EM processing to group description

### CODE REVIEW

**Comment by c-schmitz** [comment]
I think the patch is totally uncritical and could be merged to master.

**Comment by gabrieljenik** [comment]
Will create a new PR

**Comment by Shnoulle** [comment]
I don't know if we must update $gl['description']

See https://github.com/LimeSurvey/LimeSurvey/blob/435badbd8f103673ece463a6c2bea8a4296ff25f/themes/survey/vanilla/views/subviews/survey/group_subviews/group_desc.twig#L25

**Comment by gabrieljenik** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/1821
New PR

**Pull request closed without merging**
