### PR TITLE
Dev: TypeHints in QuestionEditorController

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: related #16470

### CODE REVIEW

**Comment by Shnoulle** [comment]
Capture d’écran du 2020-07-08 15-31-18
Capture d’écran du 2020-07-08 15-52-53

**Comment by olleharstedt** [comment]
This breaks travis.

**Comment by Shnoulle** [comment]
Yep :) i check.

Still think it's a good idea, but i create another pull request for https://bugs.limesurvey.org/view.php?id=16469 

Currently : permssion access in LimeSurvey 4 is broken

**Comment by olleharstedt** [comment]
> Currently : permssion access in LimeSurvey 4 is broken

It's always been broken.

**Comment by Shnoulle** [comment]
OK : 
Capture d’écran du 2020-07-09 14-04-05

Since call didn't check … i close

**Pull request closed without merging**
