### PR TITLE
Fixed issue #16748: Upload file (logo) missing in fruity and bootswatch

### PR DESCRIPTION
**Pull request by gabrieljenik**
Added file upload to core options

### CODE REVIEW

**Comment by vharris2020** [comment]
Images are being uploaded to the global directory and not the survey directory.

**Comment by Shnoulle** [comment]
Right …
https://github.com/LimeSurvey/LimeSurvey/commit/502fd7338d4e588dccbc9e2b5a6254c0d3461e7a#diff-b33e4f71f599748bc345d629d6204f4a893de9ebcccac6562903cce137d960cb

It was (but with an issue : surveyid must be checked) in master vanilla

https://github.com/LimeSurvey/LimeSurvey/blob/70507e27f6d1886bb50d52d3833284450639c684/themes/survey/vanilla/options/options.twig#L388

**Comment by gabrieljenik** [comment]
Nice! So, your patch already fixes the upload location, right?
Or do I need to patch something in my fix?

**Comment by Shnoulle** [comment]
> Nice! So, your patch already fixes the upload location, right?

Yes,

>  Or do I need to patch something in my fix?

Send the `surveyid` param (set to `{{ templateConfiguration.sid }}`) seems vanilla have it.

**Comment by gabrieljenik** [comment]
Sending `surveyid` now @Shnoulle  :)

**Review by eddylackmann — APPROVED** [review]

**Pull request merged**
