### PR TITLE
Fixed issues #16954 & #16237: Rebase Master

### PR DESCRIPTION
**Pull request by gabrieljenik**
Porting https://github.com/LimeSurvey/LimeSurvey/pull/1718 to master

### CODE REVIEW

**Comment by cdorin93** [comment]
Looks good, @gabrieljenik . Is it possible to have Variation displayed under the Fonts tab?  Then it can be merged :)

**Comment by gabrieljenik** [comment]
I suggest to merge it and then let's create a new ticket for that. I think it will simpify. I mean this is already tested. What do you think?

**Comment by cdorin93** [comment]
Sure, let's do it like that then :)

**Comment by gabrieljenik** [comment]
> Sure, let's do it like that then :)

Ticket created: https://bugs.limesurvey.org/view.php?id=17019

**Review by eddylackmann — APPROVED** [review]

**Pull request merged**
