### PR TITLE
Fix editor of template-files within subdirs

### PR DESCRIPTION
**Pull request by weberhofer**

### CODE REVIEW

**Comment by Shnoulle** [comment]
Hi,

This doesn't allow any directory. Why not assets, fonts etc .... And a new function in template_helper.

Can you post a feature request ?

**Comment by weberhofer** [comment]
Shall I add additional file-types or do you like to implement this feature totally different? Btw. I have just added feature request 10232 "Fix editor for templates in Limesurvey 2.5"

**Comment by Shnoulle** [comment]
Oups , i don't see 2.5 .... sorry .....

**Comment by weberhofer** [comment]
Will this be solved in another way?

**Comment by olleharstedt** [comment]
Hi @weberhofer , I will have a look at this.

**Comment by olleharstedt** [comment]
I added these changes to commit 075014ae962c63455398c2ed78158b8294ef50fb

**Comment by olleharstedt** [comment]
Still major problems with the template editor, though.

**Comment by weberhofer** [comment]
I know, it didn't solve all the issues but several main issues. If you like I can have another look on it the next days

**Comment by olleharstedt** [comment]
Yep, I will. Thanks for your contribution!

**Pull request closed without merging**
