### PR TITLE
Fixed issue #19262: Invalid fruity_twentythree template directory on …

### PR DESCRIPTION
**Pull request by olleharstedt**
…PostgreSQL

Fixed issue #<Mantis issue number>:
New feature #<Mantis issue number>:
Dev:

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]
Need testing

How get multiple theme, i need to  add it manually ?

**Comment by olleharstedt** [comment]
> Need testing
> 
> How get multiple theme, i need to add it manually ?

A fresh install from dbversion 615 or 616 is enough, using Postgres. Then updating to 617 will clear all settings, without this fix. Again, using Postgres.

**Comment by Shnoulle** [comment]
> A fresh install from dbversion 615 or 616 is enough, using Postgres. Then updating to 617 will clear all settings, without this fix. Again, using Postgres.

But : i don't have multiple theme lines, then i can not control if the update fix the DB

**Comment by olleharstedt** [comment]
> > A fresh install from dbversion 615 or 616 is enough, using Postgres. Then updating to 617 will clear all settings, without this fix. Again, using Postgres.
> 
> But : i don't have multiple theme lines, then i can not control if the update fix the DB

You don't have entries in table `lime_template_configuration` after a fresh install?

**Comment by Shnoulle** [comment]
> > > A fresh install from dbversion 615 or 616 is enough, using Postgres. Then updating to 617 will clear all settings, without this fix. Again, using Postgres.
> > 
> > 
> > But : i don't have multiple theme lines, then i can not control if the update fix the DB
> 
> You don't have entries in table `lime_template_configuration` after a fresh install?

I have : but not multiple :)

**Comment by Shnoulle** [comment]
Need to test if deleteDuplicateTemplateConfigurationEntries really delete NOT used TemplateConfiguration

**Comment by Shnoulle** [comment]
Tested : seems there are an issue with the original commit …

Seems it must keep the minimal id, not the max.  
I try again

**Comment by Shnoulle** [comment]
Yep : confirm the issue in case of multiple theme

1. get a 216 DB version
2. Create a survey and set a theme
3. Clone the theme line in DB
4. Update an option in theme option, and save
5. Update to this commit
6. You loose update done in #4

find get the 1st element, not the last.

**Comment by olleharstedt** [comment]
@Shnoulle  did you do both code-review and test?

**Comment by Shnoulle** [comment]
> @Shnoulle did you do both code-review and test?

I test : but i can not do both …

I have to report the issue about them option loose, but i don't know how to get it except do it in DB (and it's  not related to pgsql)

**Comment by Shnoulle** [comment]
Test way and result : https://github.com/LimeSurvey/LimeSurvey/pull/3642#issuecomment-1832207053

**Pull request merged**
