### PR TITLE
DB error don't show whole information

### PR DESCRIPTION
**Pull request by Shnoulle**
* Yii always return'CDbConnection failed to open the DB connection.' increatePdoInstance
* adding quicly a new dbTest
* this must be done only when installing (public user don't have to see exact error) then not extend DBconnection

### CODE REVIEW

**Comment by Shnoulle** [comment]
With new system : 
capture du 2016-02-07 13-55-57

**Comment by Shnoulle** [comment]
Unsure it's the best method here :)

**Comment by c-schmitz** [comment]
looks good to me, lets see how it works out

**Comment by Shnoulle** [comment]
Maybe Yii 2 have better solution, i take a look for 3.XX release ;)

**Pull request merged**
