### PR TITLE
New feature "template_copy" and "set_template_permission" on remote control

### PR DESCRIPTION
**Pull request by gabrieljenik**
New features on remote control.

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
https://manual.limesurvey.org/LimeSurvey_roadmap#Limesurvey_v2.50_.28Feb_2016.29_-_Status:_Archived

**Comment by gabrieljenik** [comment]
Sorry. What do you mean?

**Comment by TonisOrmisson** [comment]
The version you want to push to is archived. 
All new features should be going into V3 develop branch as far as I have understood.

**Comment by gabrieljenik** [comment]
I understand. But this could be considered as an update more than as a new feature.

**Comment by Shnoulle** [comment]
ANd more : @c-schmitz ask new feature only in develop version ( next 4.0 …)

**Comment by maziminke** [comment]
Why should we not add this to the next 3.x release? It can hardly break anything and that version will be in use the next months.

**Comment by maziminke** [comment]
@gabrieljenik Did this feature made it into Limesurvey?

I consider it a very useful feature for the API.

**Comment by gabrieljenik** [comment]
Nope... I think it was left behind :)

**Comment by olleharstedt** [comment]
How about adding it to 4.x?

**Comment by maziminke** [comment]
LS4 -> Of course!

But I'd love to see that also at LS3 as well since most users are using that version.

**Pull request closed without merging**
