### PR TITLE
Fixed issue #18108: Unable to save existing question with button

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: really validate whole title using validate
Dev: rename badly named function

### CODE REVIEW

**Comment by Shnoulle** [comment]
Oh shit …
`Facebook\WebDriver\Exception\UnrecognizedExceptionException: Element <div id="heading_single_choice_questions" class="panel-heading"> could not be scrolled into view`

**Comment by gabrieljenik** [comment]
Tested OK

**Comment by olleharstedt** [comment]
Not so sure about the "on-blur" check... Can't get the test to work on my machine, but not sure when it broke either.

**Comment by olleharstedt** [comment]
Yep, another "click()" fixed it.

**Comment by Shnoulle** [comment]
> I _think_ the problem is that the test code sends keys to the input field _without_ causing an _unblur_ event.

See https://github.com/LimeSurvey/LimeSurvey/pull/2440/files#diff-738d78a37df841dff8d9b693de92387fca60d44d94488875b8376d8d1b3985d3R81

i click on relevance to send a blurout.

**Comment by olleharstedt** [comment]
> i click on relevance to send a blurout.

Yes, but that only works if there's already a blur, which there wasn't. :) Fixed now, anyway.

**Comment by Shnoulle** [comment]
> Yes, but that only works if there's already a blur, which there wasn't. :) Fixed now, anyway.

Still don't understand ? I mean : sometimes it work without any issue, and sometimes it don't work. It's not a timing issue ?

**Comment by Shnoulle** [comment]
See:

1. Broken 1st time : https://github.com/LimeSurvey/LimeSurvey/runs/7264357838?check_suite_focus=true#step:14:144
2. No update, just launch : https://github.com/LimeSurvey/LimeSurvey/actions/runs/2641412964

**Comment by olleharstedt** [comment]
I could reproduce the issue on my local machine.

**Comment by Shnoulle** [comment]
> I could reproduce the issue on my local machine.

Maybe but it work sometimes : https://github.com/LimeSurvey/LimeSurvey/runs/7278683887?check_suite_focus=true OK ?

**Comment by olleharstedt** [comment]
No idea. Now it works anyway. :)

**Pull request merged**
