### PR TITLE
added new PluginEvent onBeginRequest

### PR DESCRIPTION
**Pull request by mbischof**
Fixed issue # : 
New feature #14615 :
Changed feature # :
Dev: 
Dev:

### CODE REVIEW

**Comment by maziminke** [comment]
Denis, please review and merge into master (and develop?) if everything looks fine.

**Comment by Shnoulle** [comment]
@maziminke i'm not the one to allow merging new feature in master …

**Comment by c-schmitz** [comment]
What is that event needed for? What would be an example application?

**Comment by mbischof** [comment]
see https://bugs.limesurvey.org/view.php?id=14615

**Pull request merged**
