### PR TITLE
Fixed issue #10934: EM regexMatch function don't show pattern error

### PR DESCRIPTION
**Pull request by Shnoulle**
- add a geterrors_$funcName possibility to all function
capture du 2016-04-13 16-25-17

### CODE REVIEW

**Comment by maziminke** [comment]
Great improvement, now our users know where this fails.

**Comment by Shnoulle** [comment]
@SamMousa : just to know if you have already another solution to "test validity of parameters" on a EM function.
I know you already work a lot on EM, but don't know if it's for EM core or only manager.

**Comment by SamMousa** [comment]
No, I don't, haven't implemented a general solution for this.

**Comment by Shnoulle** [comment]
Hi Sam, did you update EM core a lot or only EM manager ?

**Pull request merged**
