### PR TITLE
Fixed issue #17554 - more than one email associated the methods mail_registered_participants and invite_participants fail

### PR DESCRIPTION
**Pull request by VladRoscaDev**
Fixed issue #17554:

### CODE REVIEW

**Comment by olleharstedt** [comment]
Nice! But the indentation looks off?

**Comment by VladRoscaDev** [comment]
I have reformatted the code, can you please add this if all things are ok?

**Comment by VladRoscaDev** [comment]
Any updates on this?

**Comment by VladRoscaDev** [comment]
When is this due to be merged?

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/pull/2041 ?

**Comment by olleharstedt** [comment]
Gabriel did an updated copy of this PR, it seems.

**Pull request closed without merging**
