### PR TITLE
Fixed issue #13392 : new token form set useleft to 1

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: **All form must use Models** …

### CODE REVIEW

**Comment by olleharstedt** [comment]
This fix breaks Travis.

**Comment by Shnoulle** [comment]
Login page ? And ? Where i touch login page ????

**Comment by Shnoulle** [comment]
Login page broke before 
https://travis-ci.org/LimeSurvey/LimeSurvey/builds/344260830?utm_source=github_status&utm_medium=notification

**Comment by olleharstedt** [comment]
Ah, you just happened to get in between two fixes. OK, then I'll merge.

**Comment by Shnoulle** [comment]
PS : the `application/views/admin/token/tokenform.php` view are … …  :dizzy_face:

**Comment by olleharstedt** [comment]
Then submit a PR that fixes it? :D

**Pull request merged**
