### PR TITLE
Fixed issue #18480: User SurveyTheme could not be renamed

### PR DESCRIPTION
**Pull request by Shnoulle**
Dev: sanitize final dirnamle not whole directory name

### CODE REVIEW

**Comment by olleharstedt** [comment]
Welp, now there's a conflict that needs to be resolved :(

**Comment by Shnoulle** [comment]
> Welp, now there's a conflict that needs to be resolved :(

Nov 9, 2022 PR then for 5.X …

**Comment by Shnoulle** [comment]
Looking at diff : maybe already fixed by another PR here ?

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/commit/1337418e4a02e3a8be83f0740912e89a39dec0c5 

For 6.X

**Comment by Shnoulle** [comment]
https://github.com/LimeSurvey/LimeSurvey/commit/f18310cf00044d2031af2bfd5cf344ea80df1b94

**Comment by Shnoulle** [comment]
Not needed in 3.X
https://github.com/LimeSurvey/LimeSurvey/blob/9e1af46ca9a01f3e8ecb22ad29feef2e9191bd54/application/controllers/admin/themes.php#L557

**Pull request closed without merging**
