### PR TITLE
Response grid 14384

### PR DESCRIPTION
**Pull request by mbischof**
Fixed issue # : 
New feature # : 14384
Changed feature # :
Dev: 
Dev: 

added a new event "modifyResponseGridButtons", which allows plugins to modify the ButtonColumn in ResponseGridView

### CODE REVIEW

**Comment by mbischof** [comment]
sample Code within a Plugin, which adds a copy button to the list of responses

```php
public function modifyResponseGridButtons()
    {
        $event = $this->getEvent();
        $survey = $event->get('survey');
        $buttons = $event->get('buttons');

        $url = 'Yii::app()->createUrl("plugins/direct", array(
            "plugin" => "CopyResponse",
            "function" => "copy",
            "surveyId" => ' . $survey->sid . '
        ));';

        $buttons['copy'] = array(
            'label' => '<span class="sr-only">'.gT("Copy").'</span><span class="fa fa-copy" aria-hidden="true"></span>',
            'imageUrl' => false,
            'url' => $url,
            'options' => array(
                'class' => "btn btn-default btn-xs",
                'target' => "_blank",
                'data-toggle' => "tooltip",
                'title' => gT("Copy Response")
            ),
            'visible'=> 'boolval(' . Permission::model()->hasSurveyPermission($survey->sid, 'responses', 'update').')',
        );

        $event->set('buttons', $buttons);
    }
```

**Comment by c-schmitz** [comment]
@LouisGac ?

**Comment by dominikvitt** [comment]
This is a great feature.
Can you close this one and create a new pull request in develop branch?
All new features go there.
As soon as you are finished, I'll review it.

**Comment by maziminke** [comment]
@mbischof Was this added to develop? Is there a new pull request?

Would be great to have the ability to easily modify the buttons at grids for adding plugin icons. 

@olleharstedt Would it be possible to add something like this to a future 4.x version?

**Comment by olleharstedt** [comment]
We can discuss it.

**Comment by maziminke** [comment]
> We can discuss it.

We'd appreciate that :-)

**Comment by olleharstedt** [comment]
Please re-open this PR for the develop branch.

**Pull request closed without merging**
