### PR TITLE
Fixed issue #18814: Array question statistics fail for Remote Control.

### PR DESCRIPTION
**Pull request by gabrieljenik**
Dev: Remote Control export statistics tests.
Fixed issue #18814: Array question statistics fail for Remote Control.

### CODE REVIEW

**Review by Shnoulle — APPROVED** [review]

**Comment by olleharstedt** [comment]
Merged with red CI. Reverting.

**Comment by olleharstedt** [comment]
> Last status here was: 22 successful and 1 failing checks

Yeah weird, wonder if it was a random failure :thinking:

**Comment by gabrieljenik** [comment]
Sometimes CI fails on PLuginStats. 
Ex: https://github.com/LimeSurvey/LimeSurvey/actions/runs/5177300819/jobs/9327228684#step:11:21

Just re-running makes the trick.

**Comment by gabrieljenik** [comment]
Yes yes... it was an example (wrong example probably) Sorry, will leave you work :)

**Pull request merged**
