### PR TITLE
Fixed issue #16316: Condition for "image_select" didn't work on same …

### PR DESCRIPTION
**Pull request by Shnoulle**
Fixed issue #16316: Condition for "image_select" didn't work on same page
Dev: radio-item, not checkbox item
Dev: remove all onclick part

### CODE REVIEW

**Comment by Shnoulle** [comment]
@gabrieljenik : please can you review (seems github don't save my previous comment)

**Comment by Shnoulle** [comment]
@gabrieljenik i remove other part.

**Comment by gabrieljenik** [comment]
Now is the same patch I have on my env. I just haven't uploaded yet :)

**Comment by olleharstedt** [comment]
Uh, maybe you guys should synchronize your efforts?

**Comment by gabrieljenik** [comment]
We can say somewhoe we got it solved in collaboration

**Comment by Shnoulle** [comment]
Yep, pull request allow discusssion. Sometimes : more quick to do another pull request than explain ;)

**Comment by olleharstedt** [comment]
Just assign the bugs you work on in Mantis.

**Comment by gabrieljenik** [comment]
On top of Dorin's assignment you mean?

**Comment by olleharstedt** [comment]
Dorin should never be assign IMO, only the devs should be assigned. But yeah, workflow clashes.

**Comment by gabrieljenik** [comment]
I mean Dorin assigns me the tickets.

**Comment by Shnoulle** [comment]
@olleharstedt : this pull request was done for discussion of this https://github.com/LimeSurvey/LimeSurvey/pull/1436 :)

@gabrieljenik : if you update your, i close this one ;)

**Comment by olleharstedt** [comment]
> I mean Dorin assigns me the tickets.

That should be enough.

> @olleharstedt : this pull request was done for discussion of this #1436 :)

Got it!

**Comment by Shnoulle** [comment]
To be clearer : i close this one :)

**Pull request closed without merging**
